// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/event_store/validate.rs. Do not edit.
//! The envelope judge: every store write is schema-checked here, once.
//!
//! Ported rule-by-rule from the Python judge this store retired; the
//! diagnostics are the contract, one line each, naming the failed field.
//! The rule set arrives as `events_schema.json` (generated from
//! cli/src/fno/events/schema.yaml by build.rs) and the type-specific
//! behavioral rules are code. Diagnostics reproduce Python's repr shapes
//! (single-quoted strings, sorted single-quoted lists) so callers that
//! matched the old lines keep matching them.
//!
//! The review_attestation pass-with-branch rule consults the PR coverage
//! chain. That read lives in the pr family, which ports in its own child;
//! until it lands the read degrades exactly as the Python judge's
//! instrument-failure path did: an empty nonterminal set, never a refusal.

use serde_json::{Map, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::sync::OnceLock;

const MAX_SAFE_EVENT_INTEGER: i64 = 9_007_199_254_740_991;

/// The projected rule set. Deserialization is the load check: a missing or
/// malformed projection fails the build that embeds it.
#[derive(serde::Deserialize)]
struct EventsSchema {
    envelope_required: Vec<String>,
    allowed_sources: Vec<String>,
    #[serde(default)]
    source_patterns: Vec<String>,
    max_data_bytes: u64,
    #[serde(default)]
    gates: Vec<String>,
    #[serde(default)]
    protocol_family: ProtocolFamily,
    event_types: BTreeMap<String, TypeSpec>,
}

#[derive(serde::Deserialize, Default)]
struct ProtocolFamily {
    #[serde(default)]
    types: Vec<String>,
    #[serde(default)]
    version: i64,
    #[serde(default)]
    envelope_allowed: Vec<String>,
    #[serde(default)]
    envelope_required: Vec<String>,
    #[serde(default)]
    outcome_enum: Vec<String>,
    #[serde(default)]
    outcome_present_on: Vec<String>,
}

#[derive(serde::Deserialize)]
struct TypeSpec {
    #[serde(default)]
    sources: Vec<String>,
    #[serde(default)]
    required: Vec<String>,
    #[serde(default)]
    forbidden: Vec<String>,
    #[serde(default)]
    enums: BTreeMap<String, Vec<Value>>,
}

/// The projected schema, loaded once.
fn schema() -> &'static EventsSchema {
    static SCHEMA: OnceLock<EventsSchema> = OnceLock::new();
    if SCHEMA.get().is_none() {
        let parsed: EventsSchema = serde_json::from_str(include_str!("events_schema.json"))
            .expect("events_schema.json must deserialize (generated by build.rs)");
        let _ = SCHEMA.set(parsed);
    }
    SCHEMA.get().expect("schema set above")
}

/// Compile the envelope source patterns once.
fn source_patterns() -> &'static Vec<regex::Regex> {
    static PATTERNS: OnceLock<Vec<regex::Regex>> = OnceLock::new();
    if PATTERNS.get().is_none() {
        let mut compiled = Vec::new();
        for p in schema().source_patterns.iter() {
            compiled.push(regex::Regex::new(p).expect("schema source pattern must compile"));
        }
        let _ = PATTERNS.set(compiled);
    }
    PATTERNS.get().expect("patterns set above")
}

/// The verdict one envelope can earn.
#[derive(Debug, PartialEq)]
pub enum Verdict {
    /// Schema-valid; the store commits it.
    Valid,
    /// Refused with the one-line diagnostic.
    Invalid(String),
    /// Not judged: unparseable JSON or not an object. The store has its own
    /// pre-judge checks that answer these; the door maps them to exit 2.
    Substrate(String),
}

/// Judge one raw envelope line: parse, then schema-check.
pub fn judge_line(line: &str) -> Verdict {
    match serde_json::from_str::<Value>(line) {
        Ok(v) if v.is_object() => match validate_envelope(v.as_object().expect("object")) {
            Ok(()) => Verdict::Valid,
            Err(msg) => Verdict::Invalid(msg),
        },
        Ok(_) => Verdict::Substrate("payload must be a JSON object".into()),
        Err(e) => Verdict::Substrate(format!("payload is not valid JSON: {e}")),
    }
}

/// The judge: returns Err carrying the Python-identical one-line diagnostic.
pub fn validate_envelope(obj: &Map<String, Value>) -> Result<(), String> {
    let schema = schema();
    // 1. Envelope required fields, in schema order.
    for field in schema.envelope_required.iter() {
        if !obj.contains_key(field) {
            return Err(format!("event missing required field: {field}"));
        }
    }
    // 2. Envelope source: enum membership or a declared pattern.
    let source = &obj["source"];
    let source_str = source.as_str();
    let mut source_ok = false;
    if let Some(s) = source_str {
        if schema.allowed_sources.iter().any(|a| a == s) {
            source_ok = true;
        } else {
            for p in source_patterns().iter() {
                if p.is_match(s) {
                    source_ok = true;
                }
            }
        }
    }
    if !source_ok {
        return Err(format!(
            "unknown source: {} (allowed: {} or patterns {})",
            py_repr(source),
            py_sorted_strs(&schema.allowed_sources),
            py_str_list(&schema.source_patterns),
        ));
    }
    // 3. Known type.
    let type_value = &obj["type"];
    let type_name = type_value.as_str().unwrap_or_default();
    if type_value.is_null() || (type_name.is_empty() && !type_value.is_string()) {
        return Err(format!("unknown event type: {}", py_repr(type_value)));
    }
    let Some(spec) = schema.event_types.get(type_name) else {
        return Err(format!("unknown event type: {}", py_value_str(type_value)));
    };
    // A type with no sources list is undeclared, not unenforced-by-oversight,
    // so it fails open rather than blocking producers predating the key.
    if !spec.sources.is_empty() {
        let mut in_declared = false;
        for s in spec.sources.iter() {
            if Some(s.as_str()) == source_str {
                in_declared = true;
            }
        }
        let mut pattern_hit = false;
        for p in source_patterns().iter() {
            if p.is_match(source_str.unwrap_or_default()) {
                pattern_hit = true;
            }
        }
        if !in_declared && !pattern_hit {
            return Err(format!(
                "event type {type_name} does not allow source {} (declared: {})",
                py_repr(source),
                py_sorted_strs(&spec.sources),
            ));
        }
    }
    // 4. data: absent and JSON-null both read as {} in the Python judge
    // (event.get returns None for both), so only non-null non-objects fail.
    let empty = Map::new();
    let data: &Map<String, Value> = match obj.get("data") {
        Some(Value::Object(m)) => m,
        Some(Value::Null) | None => &empty,
        Some(_) => return Err("event data must be an object".into()),
    };
    for field in spec.required.iter() {
        if field == "gate" && !truthy(data.get("gate_bearing")) {
            continue;
        }
        if !data.contains_key(field) {
            return Err(format!(
                "event type {type_name} missing required data field: {field}"
            ));
        }
    }
    for field in spec.forbidden.iter() {
        if data.contains_key(field) {
            return Err(format!(
                "event type {type_name} forbids data field: {field}"
            ));
        }
    }
    claim_pid_rules(type_name, data)?;
    protocol_family_rules(type_name, obj)?;
    if type_name == "phase_transition"
        && truthy(data.get("gate_bearing"))
        && !truthy(data.get("gate"))
    {
        return Err("phase_transition with gate_bearing=true must include data.gate".to_string());
    }
    failover_rules(type_name, data, source_str)?;
    context_snapshot_rules(type_name, data)?;
    verification_receipt_rules(type_name, obj, data, spec)?;
    small_enum_rules(type_name, data, spec)?;
    review_attestation_rules(type_name, data, spec)?;
    mail_escalation_rule(type_name, data, spec)?;
    gate_escape_rule(type_name, data, spec)?;
    post_merge_rule(type_name, data, spec)?;
    worktree_overlap_rules(type_name, data)?;
    serialization_cap(data, schema)?;
    Ok(())
}

/// The claim-family PID truthfulness rules: a null PID must carry the
/// positive marker and a TTL expiry, an integer PID must not carry the
/// marker. Without the cross-field check a missing instrument and a
/// deliberate PID-unavailable claim are indistinguishable in the audit log.
fn claim_pid_rules(type_name: &str, data: &Map<String, Value>) -> Result<(), String> {
    if !type_name.starts_with("claim_") || !data.contains_key("pid") {
        return Ok(());
    }
    let pid = &data["pid"];
    if let Some(pu) = data.get("pid_unavailable") {
        if !pu.is_boolean() {
            return Err(format!(
                "event type {type_name} pid_unavailable must be boolean"
            ));
        }
    }
    let unavailable = data.get("pid_unavailable") == Some(&Value::Bool(true));
    if pid.is_null() && (!unavailable || data.get("expires_at").is_none_or(|v| v.is_null())) {
        return Err(format!(
            "event type {type_name} null pid requires pid_unavailable=true and expires_at"
        ));
    }
    if !pid.is_null() && unavailable {
        return Err(format!(
            "event type {type_name} pid_unavailable=true requires pid=null"
        ));
    }
    Ok(())
}

/// The a2a status-breakpoint family: the extended envelope. Routable fields
/// live at envelope level; surrounding additionalProperties:false applies to
/// this family ONLY (legacy types keep today's tolerance).
fn protocol_family_rules(type_name: &str, obj: &Map<String, Value>) -> Result<(), String> {
    let pf = &schema().protocol_family;
    if !pf.types.iter().any(|t| t == type_name) {
        return Ok(());
    }
    for field in pf.envelope_required.iter() {
        if !obj.contains_key(field) {
            return Err(format!(
                "event type {type_name} missing required envelope field: {field}"
            ));
        }
    }
    let mut extra: Vec<&str> = Vec::new();
    for k in obj.keys() {
        if !pf.envelope_allowed.contains(k) {
            extra.push(k.as_str());
        }
    }
    if !extra.is_empty() {
        extra.sort_unstable();
        return Err(format!(
            "event type {type_name} has unknown envelope field(s): {} (allowed: {})",
            py_sorted_strs(&extra),
            py_sorted_strs(&pf.envelope_allowed),
        ));
    }
    // Python compares `event.get("v") != version` numerically: 1.0 and even
    // true (bool is an int, True == 1) pass an int version there.
    let v_ok = match obj.get("v") {
        Some(Value::Number(n)) => n.as_f64() == Some(pf.version as f64),
        Some(Value::Bool(b)) => (*b as i64) == pf.version,
        _ => false,
    };
    if !v_ok {
        let got = py_repr(obj.get("v").unwrap_or(&Value::Null));
        return Err(format!(
            "event type {type_name} envelope v must be {} (got {})",
            pf.version, got
        ));
    }
    let has_outcome = obj.contains_key("outcome");
    let on_type = pf.outcome_present_on.iter().any(|t| t == type_name);
    if on_type {
        if !has_outcome {
            return Err(format!(
                "event type {type_name} requires envelope field: outcome"
            ));
        }
        let outcome = &obj["outcome"];
        let mut ok = false;
        if let Some(s) = outcome.as_str() {
            for e in pf.outcome_enum.iter() {
                if e == s {
                    ok = true;
                }
            }
        }
        if !ok {
            return Err(format!(
                "unknown {type_name} outcome: {} (allowed: {})",
                py_repr(outcome),
                py_sorted_strs(&pf.outcome_enum),
            ));
        }
    } else if has_outcome {
        return Err(format!(
            "event type {type_name} must not carry envelope field outcome (allowed only on {})",
            py_sorted_strs(&pf.outcome_present_on),
        ));
    }
    Ok(())
}

/// failover_swapped: the daemon-only source and the abandonment-reason rule.
fn failover_rules(
    type_name: &str,
    data: &Map<String, Value>,
    source_str: Option<&str>,
) -> Result<(), String> {
    if type_name != "failover_swapped" {
        return Ok(());
    }
    if source_str != Some("daemon") {
        return Err("failover_swapped source must be daemon".to_string());
    }
    let short_id_ok = match data.get("short_id") {
        Some(Value::String(s)) => !s.is_empty(),
        _ => false,
    };
    if !short_id_ok {
        return Err("failover_swapped short_id must be a non-empty string".to_string());
    }
    let redispatched_bool = match data.get("redispatched") {
        Some(Value::Bool(b)) => Some(*b),
        _ => None,
    };
    if redispatched_bool.is_none() {
        return Err("failover_swapped redispatched must be boolean".to_string());
    }
    // Python: `str(data.get("reason") or "").strip()` - every falsy value
    // (0, 0.0, False, empty containers) collapses to the empty default.
    let reason_empty = match data.get("reason") {
        None | Some(Value::Null) => true,
        Some(v) if !truthy(Some(v)) => true,
        Some(v) => py_value_str(v).trim().is_empty(),
    };
    if redispatched_bool == Some(false) && reason_empty {
        return Err("failover_swapped with redispatched=false must name a reason".to_string());
    }
    Ok(())
}

/// context_snapshot: the self-consistency rules over the measurement record.
fn context_snapshot_rules(type_name: &str, data: &Map<String, Value>) -> Result<(), String> {
    if type_name != "context_snapshot" {
        return Ok(());
    }
    let sid = data.get("session_id");
    let mut sid_ok = false;
    if let Some(Value::String(s)) = sid {
        sid_ok = !s.trim().is_empty();
    }
    if !sid_ok {
        return Err("context_snapshot session_id cannot be empty".to_string());
    }
    let harness = data.get("harness");
    let mut harness_ok = false;
    if let Some(Value::String(s)) = harness {
        if s == "claude" {
            harness_ok = true;
        }
        if s == "codex" {
            harness_ok = true;
        }
        if s == "gemini" {
            harness_ok = true;
        }
    }
    if !harness_ok {
        return Err(format!(
            "unknown context_snapshot harness: {}",
            py_repr(harness.unwrap_or(&Value::Null))
        ));
    }
    let entry = data.get("entry_state");
    let mut entry_ok = false;
    if let Some(Value::String(s)) = entry {
        entry_ok = ["startup", "resume", "clear", "post_compact"].contains(&s.as_str());
    }
    if !entry_ok {
        return Err(format!(
            "unknown context_snapshot entry_state: {}",
            py_repr(entry.unwrap_or(&Value::Null))
        ));
    }
    // The manifest and its cross-checks.
    let manifest = data.get("source_manifest");
    let errors = data.get("measurement_errors");
    let manifest_ok = match manifest {
        Some(Value::Array(a)) => {
            let mut all_obj = true;
            for item in a.iter() {
                if !item.is_object() {
                    all_obj = false;
                }
            }
            all_obj
        }
        _ => false,
    };
    if !manifest_ok {
        return Err("context_snapshot source_manifest must contain objects".to_string());
    }
    // Python reads `data.get("measurement_errors", [])`: absent defaults to
    // the empty list and passes; an explicit null is not a list and fails.
    let errors_ok = match errors {
        None => true,
        Some(Value::Array(a)) => {
            let mut all_str = true;
            for item in a.iter() {
                if !item.is_string() {
                    all_str = false;
                }
            }
            all_str
        }
        Some(_) => false,
    };
    if !errors_ok {
        return Err("context_snapshot measurement_errors must contain strings".to_string());
    }
    let manifest_items = manifest.unwrap().as_array().expect("checked above");
    let mut observed: Vec<&Value> = Vec::new();
    for item in manifest_items.iter() {
        if item.get("status") == Some(&Value::String("observed".to_string())) {
            observed.push(item);
        }
    }
    let mut observed_ok = true;
    for item in observed.iter() {
        if !is_nonneg_integral(item.get("bytes")) {
            observed_ok = false;
        }
        match item.get("content_hash") {
            Some(Value::String(_)) => {}
            _ => observed_ok = false,
        }
    }
    if !observed_ok {
        return Err(
            "context_snapshot observed sources require nonnegative bytes and content_hash"
                .to_string(),
        );
    }
    // Byte and token counts compare as f64: Python's int() of an integral
    // float is exact, and the f64 values here are the same numbers the JSON
    // carried, so equality on the f64 avoids the saturating-cast divergence
    // at magnitudes past i128. Every member passed is_nonneg_integral above,
    // so the values are whole and nonnegative.
    let mut expected_bytes: f64 = 0.0;
    for item in observed.iter() {
        expected_bytes += f64_of(item.get("bytes"));
    }
    let mut expected_hashes: Vec<&str> = Vec::new();
    for item in observed.iter() {
        expected_hashes.push(item["content_hash"].as_str().unwrap_or_default());
    }
    let expected_context_hash: Option<String> = if expected_hashes.is_empty() {
        None
    } else {
        let joined = expected_hashes.join("\n");
        Some(hex(&Sha256::digest(joined.as_bytes())))
    };
    let context_bytes = data.get("context_bytes");
    let mut cb_ok = is_nonneg_integral(context_bytes);
    if cb_ok {
        if f64_of(context_bytes) != expected_bytes {
            cb_ok = false;
        }
    }
    if !cb_ok {
        return Err("context_snapshot context_bytes disagrees with source_manifest".to_string());
    }
    let estimated = data.get("estimated_tokens");
    let mut est_ok = is_nonneg_integral(estimated);
    if est_ok {
        let want = ((expected_bytes + 3.0) / 4.0).floor();
        if f64_of(estimated) != want {
            est_ok = false;
        }
    }
    if !est_ok {
        return Err("context_snapshot estimated_tokens disagrees with context_bytes".to_string());
    }
    let want_hashes = json_array_of_strs(&expected_hashes);
    if data.get("source_hashes") != Some(&want_hashes) {
        return Err("context_snapshot source_hashes disagree with source_manifest".to_string());
    }
    let ctx = data.get("context_hash");
    let ctx_ok = match (ctx, &expected_context_hash) {
        (Some(Value::String(s)), Some(want)) => s == want,
        (None, None) => true,
        (Some(Value::Null), None) => true,
        _ => false,
    };
    if !ctx_ok {
        return Err("context_snapshot context_hash disagrees with source_hashes".to_string());
    }
    let mc = data.get("measurement_complete");
    let mut mc_ok = false;
    if let Some(Value::Bool(_)) = mc {
        mc_ok = true;
    }
    if !mc_ok {
        return Err("context_snapshot measurement_complete must be boolean".to_string());
    }
    let complete = mc == Some(&Value::Bool(true));
    let all_observed = !manifest_items.is_empty() && observed.len() == manifest_items.len();
    let errors_empty = match data.get("measurement_errors") {
        Some(Value::Array(a)) => a.is_empty(),
        _ => true,
    };
    if complete != (all_observed && errors_empty) {
        return Err("context_snapshot completeness disagrees with manifest and errors".to_string());
    }
    Ok(())
}

/// verification_receipt: the full evidence contract.
fn verification_receipt_rules(
    type_name: &str,
    obj: &Map<String, Value>,
    data: &Map<String, Value>,
    spec: &TypeSpec,
) -> Result<(), String> {
    if type_name != "verification_receipt" {
        return Ok(());
    }
    if utc_timestamp(obj.get("ts")).is_none() {
        return Err("verification_receipt envelope ts must be RFC3339 UTC".to_string());
    }
    let mode = data.get("mode");
    if !enum_contains(spec.enums.get("mode"), mode) {
        return Err(format!(
            "unknown verification_receipt data.mode: {}",
            py_repr(mode.unwrap_or(&Value::Null)),
        ));
    }
    let result = data.get("result");
    if !enum_contains(spec.enums.get("result"), result) {
        return Err(format!(
            "unknown verification_receipt data.result: {}",
            py_repr(result.unwrap_or(&Value::Null)),
        ));
    }
    let candidate_sha = data.get("candidate_sha");
    let mut sha_ok = false;
    if let Some(Value::String(s)) = candidate_sha {
        sha_ok = is_hex(s, 40, true);
    }
    if !sha_ok {
        return Err("verification_receipt candidate_sha must be full 40-hex".to_string());
    }
    let command = data.get("command");
    if !bounded_str_list(command, 4096, 4096) {
        return Err("verification_receipt command must contain bounded argv strings".to_string());
    }
    let scope = data.get("scope");
    if !bounded_str_list(scope, 128, 512) {
        return Err("verification_receipt scope must contain bounded step names".to_string());
    }
    let environment = data.get("environment");
    let env_ok = match environment {
        Some(Value::Object(m)) => {
            let mut ok = true;
            for field in ["host", "platform", "runner"].iter() {
                let v = m.get(*field);
                let good = match v {
                    Some(Value::String(s)) => !s.trim().is_empty(),
                    _ => false,
                };
                if !good {
                    ok = false;
                }
            }
            ok
        }
        _ => false,
    };
    if !env_ok {
        return Err(
            "verification_receipt environment requires host, platform, and runner".to_string(),
        );
    }
    let producer = data.get("producer");
    let producer_ok = match producer {
        Some(Value::Object(m)) => {
            let mut ok = true;
            for field in ["kind", "id"].iter() {
                let good = match m.get(*field) {
                    Some(Value::String(s)) => !s.trim().is_empty(),
                    _ => false,
                };
                if !good {
                    ok = false;
                }
            }
            ok
        }
        _ => false,
    };
    if !producer_ok {
        return Err("verification_receipt producer requires kind and id".to_string());
    }
    let started = utc_timestamp(data.get("started_at"));
    let finished = utc_timestamp(data.get("finished_at"));
    let mut ordered = false;
    if let (Some(s), Some(f)) = (&started, &finished) {
        if f >= s {
            ordered = true;
        }
    }
    if !ordered {
        return Err("verification_receipt timestamps must be ordered RFC3339 UTC".to_string());
    }
    let generation = data.get("generation");
    let expected = data.get("steps_expected");
    let executed = data.get("steps_executed");
    // Counts compare as f64 for the same reason as the context_snapshot
    // arithmetic: no saturating-cast divergence at absurd magnitudes.
    let gen = f64_of(generation);
    let exp = f64_of(expected);
    let exe = f64_of(executed);
    let mut counts_ok =
        is_nonneg_integral(generation) && gen >= 1.0 && gen <= MAX_SAFE_EVENT_INTEGER as f64;
    counts_ok = counts_ok && is_nonneg_integral(expected) && is_nonneg_integral(executed);
    counts_ok = counts_ok && exe <= exp;
    counts_ok = counts_ok && exp == scope_len(data) as f64;
    if !counts_ok {
        return Err("verification_receipt step counts are invalid".to_string());
    }
    let mode_str = mode.and_then(|v| v.as_str()).unwrap_or_default();
    let result_str = result.and_then(|v| v.as_str()).unwrap_or_default();
    if mode_str == "full" && result_str == "passed" && (exp == 0.0 || exe != exp) {
        return Err("verification_receipt full pass requires every nonzero step".to_string());
    }
    if mode_str == "void" && result_str == "passed" {
        return Err("verification_receipt void mode cannot pass".to_string());
    }
    Ok(())
}

/// One enum-membership rule: `data.<field>` must be a member of the
/// schema enum, when present. A missing member fails the rule exactly as
/// the Python judge does (None is never a member).
fn field_enum_rule(
    type_name: &str,
    data: &Map<String, Value>,
    spec: &TypeSpec,
    enum_key: &str,
    fields: &[&str],
) -> Result<(), String> {
    for field in fields.iter() {
        let allowed = enum_list(spec.enums.get(enum_key));
        let member = data.get(*field);
        let mut ok = false;
        if let Some(member) = member {
            for e in allowed.iter() {
                if e == member {
                    ok = true;
                }
            }
        }
        if !ok {
            return Err(format!(
                "unknown {type_name} data.{field}: {} (allowed: {})",
                py_repr(member.unwrap_or(&Value::Null)),
                py_value_list(allowed),
            ));
        }
    }
    Ok(())
}

/// The per-type enum rules that share one shape. Order matches the Python
/// judge: phase gate enum, mission_complete status, the session_satisfied
/// pair, termination, transition_rejected, the human_touch pair, then the
/// operator_submit and skill_eval_finding pairs.
fn small_enum_rules(
    type_name: &str,
    data: &Map<String, Value>,
    spec: &TypeSpec,
) -> Result<(), String> {
    if type_name == "phase_transition" {
        if let Some(g) = data.get("gate") {
            let mut known = false;
            if let Some(s) = g.as_str() {
                for gate in schema().gates.iter() {
                    if gate == s {
                        known = true;
                    }
                }
            }
            if truthy(Some(g)) && !known {
                return Err(format!(
                    "unknown gate: {} (allowed: {})",
                    py_repr(g),
                    py_sorted_strs(&schema().gates),
                ));
            }
        }
    }
    if type_name == "mission_complete" {
        let status = data.get("status");
        let allowed = spec.enums.get("status");
        let nonempty = allowed.is_some_and(|l| !l.is_empty());
        if !enum_contains(allowed, status) && nonempty {
            return Err(format!(
                "unknown status: {} (allowed: {})",
                py_repr(status.unwrap_or(&Value::Null)),
                py_value_list(enum_list(allowed)),
            ));
        }
    }
    if type_name == "session_satisfied" || type_name == "auto_complete_triggered" {
        field_enum_rule(type_name, data, spec, "source", &["source"])?;
    }
    if type_name == "termination" {
        field_enum_rule(type_name, data, spec, "reason", &["reason"])?;
    }
    if type_name == "transition_rejected" {
        for field in ["kind", "event", "from"].iter() {
            if let Some(member) = data.get(*field) {
                let allowed = enum_list(spec.enums.get(*field));
                let mut ok = false;
                for e in allowed.iter() {
                    if e == member {
                        ok = true;
                    }
                }
                if !ok {
                    return Err(format!(
                        "unknown transition_rejected data.{field}: {} (allowed: {})",
                        py_repr(member),
                        py_value_list(allowed),
                    ));
                }
            }
        }
    }
    if type_name == "human_touch" {
        field_enum_rule(type_name, data, spec, "source", &["source"])?;
        field_enum_rule(type_name, data, spec, "resolution", &["resolution"])?;
    }
    if type_name == "operator_submit" {
        field_enum_rule(type_name, data, spec, "via", &["via"])?;
        field_enum_rule(type_name, data, spec, "resolution", &["resolution"])?;
    }
    if type_name == "skill_eval_finding" {
        field_enum_rule(type_name, data, spec, "dimension", &["dimension"])?;
        field_enum_rule(type_name, data, spec, "verdict", &["verdict"])?;
    }
    if type_name == "decision_span" {
        // span_kind/route/class drive the eval grouping (one decision path
        // per trace_id), so a typo'd hop refuses here rather than landing as
        // an unrecognized bucket. span_kind is always checked (the required
        // check already refused a missing key); route and class only when
        // present.
        let allowed = enum_list(spec.enums.get("span_kind"));
        let member = data.get("span_kind");
        let mut ok = false;
        if let Some(m) = member {
            for e in allowed.iter() {
                if e == m {
                    ok = true;
                }
            }
        }
        if !ok {
            return Err(format!(
                "unknown decision_span data.span_kind: {} (allowed: {})",
                py_repr(member.unwrap_or(&Value::Null)),
                py_value_list(enum_list(spec.enums.get("span_kind"))),
            ));
        }
        for field in ["route", "class"] {
            if let Some(member) = data.get(field) {
                let allowed = enum_list(spec.enums.get(field));
                let mut ok = false;
                for e in allowed.iter() {
                    if e == member {
                        ok = true;
                    }
                }
                if !ok {
                    return Err(format!(
                        "unknown decision_span data.{field}: {} (allowed: {})",
                        py_repr(member),
                        py_value_list(allowed),
                    ));
                }
            }
        }
    }
    Ok(())
}

/// One bounded argv/step-name list: non-empty strings within both caps.
fn bounded_str_list(v: Option<&Value>, max_items: usize, max_bytes: usize) -> bool {
    match v {
        Some(Value::Array(items)) => {
            !items.is_empty()
                && items.len() <= max_items
                && items.iter().all(|item| match item {
                    Value::String(s) => !s.is_empty() && s.len() <= max_bytes,
                    _ => false,
                })
        }
        _ => false,
    }
}

/// review_attestation: the verdict enum, the count fields, the findings and
/// dispositions shapes, and the pass-with-branch disposition obligation. The
/// coverage-chain read lands with the pr family port; until then the
/// nonterminal set degrades empty exactly as the Python judge's
/// instrument-failure path did, so the refusal below is unreachable but kept
/// faithful for that port to fill in.
fn review_attestation_rules(
    type_name: &str,
    data: &Map<String, Value>,
    spec: &TypeSpec,
) -> Result<(), String> {
    if type_name != "review_attestation" {
        return Ok(());
    }
    field_enum_rule(type_name, data, spec, "verdict", &["verdict"])?;
    for count_field in ["findings_blocking", "findings_nonblocking", "review_round"].iter() {
        if let Some(value) = data.get(*count_field) {
            if !value.is_null()
                && (!is_nonneg_integral(Some(value))
                    || py_int(value) > MAX_SAFE_EVENT_INTEGER as i128)
            {
                return Err(format!(
                    "review_attestation data.{count_field} must be a non-negative integer"
                ));
            }
        }
    }
    match data.get("findings_truncated") {
        Some(v) if !v.is_null() && !v.is_boolean() => {
            return Err("review_attestation data.findings_truncated must be boolean".to_string());
        }
        _ => {}
    }
    if let Some(findings) = data.get("findings") {
        if !findings.is_null() {
            let ok = match findings {
                Value::Array(items) => items.iter().all(|item| {
                    let obj = match item {
                        Value::Object(m) => m,
                        _ => return false,
                    };
                    matches!(obj.get("blocking"), Some(Value::Bool(_)))
                        && matches!(obj.get("has_required_fields"), Some(Value::Bool(_)))
                        && matches!(obj.get("finding_key"),
                            Some(Value::String(s)) if !s.trim().is_empty())
                        && matches!(
                            obj.get("category"),
                            None | Some(Value::Null) | Some(Value::String(_))
                        )
                        && matches!(
                            obj.get("verdict"),
                            None | Some(Value::Null) | Some(Value::String(_))
                        )
                }),
                _ => false,
            };
            if !ok {
                return Err("review_attestation data.findings must be an array of \
                     {category, verdict, blocking, has_required_fields, finding_key} primitives"
                    .to_string());
            }
        }
    }
    if let Some(dispositions) = data.get("dispositions") {
        if !dispositions.is_null() {
            let disposition_enum = spec.enums.get("dispositions[].disposition");
            let ok = match dispositions {
                Value::Array(items) => items.iter().all(|item| {
                    let obj = match item {
                        Value::Object(m) => m,
                        _ => return false,
                    };
                    matches!(obj.get("finding_key"),
                        Some(Value::String(s)) if !s.trim().is_empty())
                        && enum_contains(disposition_enum, obj.get("disposition"))
                        && matches!(obj.get("reason"),
                            Some(Value::String(s)) if !s.trim().is_empty())
                }),
                _ => false,
            };
            if !ok {
                return Err(format!(
                    "review_attestation data.dispositions must be an array of \
                     {{finding_key, disposition in {}, reason}} objects",
                    py_value_list(enum_list(disposition_enum)),
                ));
            }
        }
    }
    if matches!(data.get("verdict"), Some(Value::String(s)) if s == "pass") {
        if let Some(Value::String(branch)) = data.get("branch") {
            if !branch.trim().is_empty() {
                // The cap_verdict read lands with the pr family port; the
                // degrade keeps the rule's shape so that port fills in one
                // expression.
                let nonterminal: Vec<String> = Vec::new();
                let mut disposing: std::collections::HashSet<&str> =
                    std::collections::HashSet::new();
                if let Some(Value::Array(items)) = data.get("dispositions") {
                    for entry in items.iter() {
                        if let Value::Object(m) = entry {
                            if matches!(m.get("disposition"),
                                Some(Value::String(s)) if s == "fixed" || s == "declined")
                            {
                                if let Some(Value::String(k)) = m.get("finding_key") {
                                    disposing.insert(k.as_str());
                                }
                            }
                        }
                    }
                }
                let outstanding: Vec<&str> = nonterminal
                    .iter()
                    .filter(|key| !disposing.contains(key.as_str()))
                    .map(|key| key.as_str())
                    .collect();
                if !outstanding.is_empty() {
                    return Err(format!(
                        "review_attestation refused: a pass disposes nothing \
                         by itself, and branch {branch} still holds blocking \
                         finding(s) without a disposition here: {}; dispose \
                         each one here as fixed, or as declined carrying a \
                         reason (a decline with a reason is terminal)",
                        outstanding.join(", "),
                    ));
                }
            }
        }
    }
    Ok(())
}
/// mail_escalation: the reason drives the overlay evidence text and the
/// question-vs-attended-miss split, so a typo fails loud.
fn mail_escalation_rule(
    type_name: &str,
    data: &Map<String, Value>,
    spec: &TypeSpec,
) -> Result<(), String> {
    if type_name != "mail_escalation" {
        return Ok(());
    }
    field_enum_rule(type_name, data, spec, "reason", &["reason"])
}

/// gate_escape: the reason drives the retro autonomy-debt ranking, so a typo
/// fails closed here rather than landing a silent bucket.
fn gate_escape_rule(
    type_name: &str,
    data: &Map<String, Value>,
    spec: &TypeSpec,
) -> Result<(), String> {
    if type_name != "gate_escape" {
        return Ok(());
    }
    field_enum_rule(type_name, data, spec, "reason", &["reason"])
}

/// post_merge_dispatch_receipt: the phase drives the reserved-before-accepted
/// lifecycle; the typed helper constrains it too, but the generic emit CLI is
/// also a writer.
fn post_merge_rule(
    type_name: &str,
    data: &Map<String, Value>,
    spec: &TypeSpec,
) -> Result<(), String> {
    if type_name != "post_merge_dispatch_receipt" {
        return Ok(());
    }
    for field in ["phase", "route"].iter() {
        field_enum_rule(type_name, data, spec, field, std::slice::from_ref(&field))?;
    }
    Ok(())
}

/// worktree_overlap_observed: the recurrence key for `fno agents workspace
/// worktree overlaps`. Peers must be a sorted unique non-empty string list, the
/// observation id a digest recomputable from its fields, and the observer
/// never its own peer; a hand-crafted event is rejected rather than counted.
fn worktree_overlap_rules(type_name: &str, data: &Map<String, Value>) -> Result<(), String> {
    if type_name != "worktree_overlap_observed" {
        return Ok(());
    }
    let peers = match data.get("peer_session_ids") {
        Some(Value::Array(items)) => {
            let mut peers: Vec<String> = Vec::new();
            let mut shape_ok = !items.is_empty();
            for item in items.iter() {
                match item {
                    Value::String(s) if !s.is_empty() => peers.push(s.clone()),
                    _ => shape_ok = false,
                }
            }
            if !shape_ok {
                return Err(
                    "worktree_overlap_observed peer_session_ids must be a non-empty \
                     list of non-empty strings"
                        .to_string(),
                );
            }
            peers
        }
        _ => {
            return Err(
                "worktree_overlap_observed peer_session_ids must be a non-empty \
                 list of non-empty strings"
                    .to_string(),
            )
        }
    };
    let mut unique: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for p in peers.iter() {
        unique.insert(p.as_str());
    }
    let deduped: Vec<&str> = unique.into_iter().collect();
    if peers.iter().map(String::as_str).collect::<Vec<&str>>() != deduped {
        return Err(
            "worktree_overlap_observed peer_session_ids must be sorted and unique".to_string(),
        );
    }
    let oid = data.get("observation_id");
    let mut oid_ok = false;
    if let Some(Value::String(s)) = oid {
        oid_ok = is_hex(s, 64, false);
    }
    if !oid_ok {
        return Err(
            "worktree_overlap_observed observation_id must be a 64-hex sha256 digest".to_string(),
        );
    }
    let repo = data.get("repository_key");
    let wt = data.get("worktree_key");
    let obs = data.get("observer_session_id");
    let triple_ok = match (repo, wt, (obs)) {
        (Some(Value::String(a)), Some(Value::String(b)), Some(Value::String(c))) => {
            !a.is_empty() && !b.is_empty() && !c.is_empty()
        }
        _ => false,
    };
    if !triple_ok {
        return Err(
            "worktree_overlap_observed requires non-empty repository_key, \
             worktree_key, and observer_session_id strings"
                .to_string(),
        );
    }
    let repo = repo.and_then(|v| v.as_str()).unwrap_or_default();
    let wt = wt.and_then(|v| v.as_str()).unwrap_or_default();
    let obs = obs.and_then(|v| v.as_str()).unwrap_or_default();
    if peers.iter().any(|p| p == obs) {
        return Err("worktree_overlap_observed observer cannot be its own peer".to_string());
    }
    if oid.and_then(|v| v.as_str()) != Some(overlap_observation_id(repo, wt, obs, &peers).as_str())
    {
        return Err(
            "worktree_overlap_observed observation_id does not match its fields".to_string(),
        );
    }
    Ok(())
}

/// The single digest implementation; validate recomputes it exactly as the
/// fold does. sha256 over the compact JSON array [repo, wt, obs, peers].
fn overlap_observation_id(repo: &str, wt: &str, obs: &str, peers: &[String]) -> String {
    let mut deduped: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for p in peers.iter() {
        deduped.insert(p.as_str());
    }
    let peer_array: Vec<Value> = deduped
        .into_iter()
        .map(|p| Value::String(p.to_string()))
        .collect();
    let arr = Value::Array(vec![
        Value::String(repo.to_string()),
        Value::String(wt.to_string()),
        Value::String(obs.to_string()),
        Value::Array(peer_array),
    ]);
    let compact = serde_json::to_string(&arr).unwrap_or_default();
    hex(&Sha256::digest(compact.as_bytes()))
}

/// The final gate: data must serialize within the size cap. The Python judge
/// also refused non-serializable data there; a serde Value is always
/// serializable, so only the cap can fire here.
fn serialization_cap(data: &Map<String, Value>, schema: &EventsSchema) -> Result<(), String> {
    let len = py_ascii_json_len(data);
    if len > schema.max_data_bytes as usize {
        return Err(format!(
            "event data exceeds max_data_bytes (got {len}, limit {})",
            schema.max_data_bytes
        ));
    }
    Ok(())
}

/// Byte length of Python `json.dumps(data, separators=(",", ":"),
/// ensure_ascii=True).replace("\x7f", "\\u007f")`. serde_json's compact
/// output matches Python's for ASCII (same short escapes, same lowercase
/// control-char \\uXXXX), so this post-processes chars >= 0x80 to \\uXXXX and
/// rewrites the raw DEL char to its six-character escape.
fn py_ascii_json_len(data: &Map<String, Value>) -> usize {
    let compact = serde_json::to_string(data).unwrap_or_default();
    let mut out = String::with_capacity(compact.len());
    for c in compact.chars() {
        match c {
            '\u{7f}' => out.push_str("\\u007f"),
            c if (c as u32) < 0x80 => out.push(c),
            c if (c as u32) <= 0xFFFF => {
                out.push_str(&format!("\\u{:04x}", c as u32));
            }
            c => {
                let cp = c as u32;
                let hi = 0xD800 + ((cp - 0x10000) >> 10);
                let lo = 0xDC00 + ((cp - 0x10000) & 0x3FF);
                out.push_str(&format!("\\u{:04x}\\u{:04x}", hi, lo));
            }
        }
    }
    out.len()
}
/// Python bool() over a JSON value.
fn truthy(v: Option<&Value>) -> bool {
    match v {
        None | Some(Value::Null) => false,
        Some(Value::Bool(b)) => *b,
        Some(Value::Number(n)) => n.as_f64().map(|f| f != 0.0).unwrap_or(false),
        Some(Value::String(s)) => !s.is_empty(),
        Some(Value::Array(a)) => !a.is_empty(),
        Some(Value::Object(o)) => !o.is_empty(),
    }
}
/// The JSON number as f64, NEG_INFINITY when absent (a sentinel no real
/// count equals, so an absent member fails the comparison).
fn f64_of(v: Option<&Value>) -> f64 {
    v.and_then(|x| x.as_f64()).unwrap_or(f64::NEG_INFINITY)
}

/// Python int() truncation over a JSON number (0 for non-numbers; callers
/// guard integrality separately).
fn py_int(v: &Value) -> i128 {
    match v {
        Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                i as i128
            } else if let Some(u) = n.as_u64() {
                u as i128
            } else {
                n.as_f64().map(|f| f.trunc() as i128).unwrap_or(0)
            }
        }
        _ => 0,
    }
}

/// Python `type(v) is int` (bools excluded) or an integral float: finite,
/// nonnegative, whole. Mirrors _is_nonnegative_integral_number.
fn is_nonneg_integral(v: Option<&Value>) -> bool {
    match v {
        Some(Value::Number(n)) => {
            if let Some(i) = n.as_i64() {
                i >= 0
            } else if n.as_u64().is_some() {
                true
            } else {
                n.as_f64()
                    .map(|f| f.is_finite() && f >= 0.0 && f.fract() == 0.0)
                    .unwrap_or(false)
            }
        }
        _ => false,
    }
}
/// Python repr() over a JSON value: None/True/False capitalization, digit
/// strings, quoted strings, `['a', 'b']` lists, insertion-ordered dicts.
fn py_repr(v: &Value) -> String {
    match v {
        Value::Null => "None".to_string(),
        Value::Bool(true) => "True".to_string(),
        Value::Bool(false) => "False".to_string(),
        Value::Number(n) => {
            if let Some(i) = n.as_i64() {
                i.to_string()
            } else if let Some(u) = n.as_u64() {
                u.to_string()
            } else {
                n.as_f64().map(py_repr_f64).unwrap_or_default()
            }
        }
        Value::String(s) => py_repr_str(s),
        Value::Array(a) => format!("[{}]", a.iter().map(py_repr).collect::<Vec<_>>().join(", ")),
        Value::Object(o) => format!(
            "{{{}}}",
            o.iter()
                .map(|(k, v)| format!("{}: {}", py_repr_str(k), py_repr(v)))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}
/// Python repr() of a float. Rust's Display is shortest-round-trip like
/// Python's, differing only in the `.0` integer floats need and the exponent
/// forms Python switches to past 1e16.
fn py_repr_f64(f: f64) -> String {
    if f.is_nan() {
        return "nan".to_string();
    }
    if f.is_infinite() {
        return if f > 0.0 { "inf" } else { "-inf" }.to_string();
    }
    if f == f.trunc() && f.abs() < 1e16 {
        format!("{f:.1}")
    } else {
        format!("{f}")
    }
}

/// Python repr() of a str: single quotes, the five short escapes, and
/// \\xNN for the other control chars and DEL.
fn py_repr_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || (c as u32) == 0x7f => {
                out.push_str(&format!("\\x{:02x}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}
/// Python str() over a JSON value: strings raw, everything else its repr.
fn py_value_str(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        other => py_repr(other),
    }
}

/// Python repr() of a list of strings.
fn py_str_list(items: &[String]) -> String {
    format!(
        "[{}]",
        items
            .iter()
            .map(|s| py_repr_str(s))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

/// Python `sorted(...)` then list repr, generic over the element borrow.
fn py_sorted_strs<S: AsRef<str>>(items: &[S]) -> String {
    let mut strs: Vec<&str> = items.iter().map(|s| s.as_ref()).collect();
    strs.sort_unstable();
    format!(
        "[{}]",
        strs.iter()
            .map(|s| py_repr_str(s))
            .collect::<Vec<_>>()
            .join(", ")
    )
}
/// Python repr() of a list of JSON values.
fn py_value_list(items: &[Value]) -> String {
    format!(
        "[{}]",
        items.iter().map(py_repr).collect::<Vec<_>>().join(", ")
    )
}

/// The schema enum for a key, or the empty list.
fn enum_list(e: Option<&Vec<Value>>) -> &[Value] {
    e.map(|v| v.as_slice()).unwrap_or(&[])
}

/// Python `x in enum` with None never a member.
fn enum_contains(e: Option<&Vec<Value>>, member: Option<&Value>) -> bool {
    let Some(member) = member else { return false };
    enum_list(e).iter().any(|m| m == member)
}

/// Full-match hex of a fixed length; `ci` allows uppercase (candidate_sha is
/// case-insensitive, observation_id lowercase-only).
fn is_hex(s: &str, len: usize, ci: bool) -> bool {
    s.len() == len
        && s.bytes().all(|b| match b {
            b'0'..=b'9' | b'a'..=b'f' => true,
            b'A'..=b'F' => ci,
            _ => false,
        })
}

// Lowercase hex encoding is the parent module's encoder; shared here so the
// digest form has one spelling.
use super::hex;

/// The scope array's length, 0 when absent or not an array.
fn scope_len(data: &Map<String, Value>) -> i128 {
    match data.get("scope") {
        Some(Value::Array(a)) => a.len() as i128,
        _ => 0,
    }
}

/// JSON array-of-strings value for cross-checking source_hashes.
fn json_array_of_strs(items: &[&str]) -> Value {
    Value::Array(items.iter().map(|s| Value::String(s.to_string())).collect())
}
/// The Python `_utc_timestamp`: RFC3339 UTC shape (uppercase T, fractional
/// seconds 1-6 digits, Z or +00:00 offset) plus full calendar validity, as an
/// ordered tuple a `>=` comparison orders chronologically. Leap seconds
/// (sec=60) reject exactly as fromisoformat does.
fn utc_timestamp(value: Option<&Value>) -> Option<(i64, u32, u32, u32, u32, u32, u32)> {
    let s = match value {
        Some(Value::String(s)) if !s.is_empty() => s,
        _ => return None,
    };
    let b = s.as_bytes();
    if b.len() < 20
        || b[4] != b'-'
        || b[7] != b'-'
        || b[10] != b'T'
        || b[13] != b':'
        || b[16] != b':'
    {
        return None;
    }
    let seg = |r: std::ops::Range<usize>| -> Option<u32> {
        let sub = &b[r.clone()];
        if sub.iter().all(|c| c.is_ascii_digit()) {
            s[r].parse::<u32>().ok()
        } else {
            None
        }
    };
    let year: i64 = s[0..4].parse().ok()?;
    let month = seg(5..7)?;
    let day = seg(8..10)?;
    let hour = seg(11..13)?;
    let min = seg(14..16)?;
    let sec = seg(17..19)?;
    let mut rest = &b[19..];
    let mut micro = 0u32;
    if rest.first() == Some(&b'.') {
        let digits_end = b[20..]
            .iter()
            .position(|c| !c.is_ascii_digit())
            .map(|p| 20 + p)?;
        let frac_len = digits_end - 20;
        if !(1..=6).contains(&frac_len) {
            return None;
        }
        micro = format!("{:0<6}", &s[20..digits_end]).parse().ok()?;
        rest = &b[digits_end..];
    }
    match rest {
        b"Z" => {}
        b"+00:00" => {}
        _ => return None,
    }
    if year < 1
        || !(1..=12).contains(&month)
        || day == 0
        || day > days_in_month(year, month)
        || hour > 23
        || min > 59
        || sec > 59
    {
        return None;
    }
    Some((year, month, day, hour, min, sec, micro))
}

/// Days in month with the Gregorian leap-year rule.
fn days_in_month(year: i64, month: u32) -> u32 {
    match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 => {
            if (year % 4 == 0 && year % 100 != 0) || year % 400 == 0 {
                29
            } else {
                28
            }
        }
        _ => 0,
    }
}
