//! `fno config paths emit-shell`: generate scripts/lib/paths.sh natively.
//!
//! One verb per PR (law d-450caaeb): this file serves `emit-shell`; the
//! other three paths verbs still answer in Python (cli/src/fno/paths_cli.py)
//! until their child nodes port. The defaults emitter reproduces the
//! checked-in scripts/lib/paths.sh byte for byte; the include_bytes! parity
//! test fails the build the moment the two drift.

use std::path::PathBuf;
use std::process::Command;

/// The parity fixture: the checked-in stub this emitter must reproduce.
/// Test-only: the include path leaves the crate, which packaging forbids.
#[cfg(test)]
const FIXTURE: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../scripts/lib/paths.sh"
));

/// Quote a value for a bash assignment, the shape of Python `_bash_quote`:
/// a value carrying `$` takes double quotes so bash expands it at runtime
/// (literal `"` and `\` escaped first); anything else takes shlex single
/// quotes, unquoted when every char is shell-safe.
fn bash_quote(value: &str) -> String {
    if value.contains('$') {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        return format!("\"{escaped}\"");
    }
    if value.is_empty() {
        return "''".to_string();
    }
    let safe = value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "@%+=:,./-_".contains(c));
    if safe {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Convert a tilde-prefixed raw value to a `$HOME`-relative template; an
/// absolute path passes through. Trailing slashes strip for consistency.
fn home_relative(raw: &str) -> String {
    let stripped = raw.trim_end_matches('/');
    if let Some(rest) = stripped.strip_prefix("~/") {
        return format!("$HOME/{rest}");
    }
    if stripped == "~" {
        return "$HOME".to_string();
    }
    stripped.to_string()
}

/// True for a bare relative path (no `~`, `/`-root, `$`, or `{` template
/// anywhere -- `plans/{project}` is NOT project-relative).
fn is_project_relative(raw: &str) -> bool {
    let stripped = raw.trim();
    if stripped.is_empty() {
        return false;
    }
    !(stripped.starts_with('/')
        || stripped.starts_with('~')
        || stripped.starts_with('$')
        || stripped.contains('{'))
}

/// True when the raw value carries a `{template}` variable (a `{{` escape
/// never counts, mirroring the Python regex's lookarounds).
fn has_template(raw: &str) -> bool {
    let bytes = raw.as_bytes();
    for i in 0..bytes.len() {
        if bytes[i] != b'{' || (i > 0 && bytes[i - 1] == b'{') {
            continue;
        }
        if let Some(close) = raw[i + 1..].find('}') {
            let close_idx = i + 1 + close;
            let next_dbl = close_idx + 1 < bytes.len() && bytes[close_idx + 1] == b'}';
            let inner = &raw[i + 1..close_idx];
            if !next_dbl && !inner.is_empty() && !inner.contains('{') && !inner.contains('}') {
                return true;
            }
        }
    }
    false
}

fn header_lines() -> Vec<String> {
    let header = r#"#!/usr/bin/env bash
# AUTO-GENERATED by `fno config paths emit-shell`. Do not hand-edit.
# Regenerate after any change to settings.yaml or the schema:
#   fno config paths emit-shell --output scripts/lib/paths.sh
#
# This stub is config-BLIND by design: it is emitted with use_defaults=True so
# regeneration is byte-stable across machines and the checked-in hash verifies.
# It does NOT honor a project's settings.yaml. A bash caller that needs the
# current config's resolved paths (vault-aware handoffs dir, overridden
# state_dir, etc.) must use the config-aware door instead:
#   source "$(fno config paths shell-stub)"
# which regenerates a temp stub from the live settings on every call.

# Self-set REPO_ROOT if unset so this file is safe to source under set -u.
# Callers may still pre-set REPO_ROOT before sourcing to pin the value.
REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
HOME="${HOME:-$(getent passwd "$(id -un)" 2>/dev/null | cut -d: -f6 || echo ~)}"
"#;
    header.lines().map(String::from).collect()
}

/// Emit the config-blind stub from schema defaults only (`use_defaults=True`):
/// `$HOME` and `$REPO_ROOT` stay literal so the bytes are machine-stable and
/// the checked-in hash verifies. Byte-for-byte port of the defaults path of
/// Python `emit_paths_sh`; the include_bytes! parity test pins it.
pub fn emit_paths_sh_defaults() -> String {
    let mut lines = header_lines();
    lines.push(String::new());
    lines.push(format!(
        "export STATE_DIR={}",
        bash_quote(&home_relative("~/.fno/"))
    ));
    for (name, sub) in [
        ("LEDGER_JSON_PATH", "ledger.json"),
        ("BRIEFS_DIR", "briefs"),
        ("FLEET_DIR", "fleet"),
        ("POSTMORTEMS_DIR", "postmortems"),
        ("WORKTREES_BASE", "worktrees"),
        ("MEMORY_DIR", "memory"),
        ("HOOK_LOGS_DIR", "hook-logs"),
        ("LATCHES_DIR", "latches"),
    ] {
        let v = bash_quote(&format!("$STATE_DIR/{sub}"));
        lines.push(format!("export {name}={v}"));
    }
    lines.push(format!(
        "export PLANS_DIR={}",
        bash_quote("$REPO_ROOT/.fno/plans")
    ));
    lines.push(format!(
        "export INBOX_DIR={}",
        bash_quote("$REPO_ROOT/.fno/inbox")
    ));
    // Defaults mode: no handoffs override, obsidian off, project.id unset --
    // the literal fallback line keeps the stub machine-stable; the basename
    // resolves at source-time from the consumer's repo.
    lines
        .push("export HANDOFFS_DIR=\"$STATE_DIR/handoffs/$(basename \"$REPO_ROOT\")\"".to_string());
    lines.push(format!(
        "export CONFIG_FILE={}",
        bash_quote("$STATE_DIR/config.toml")
    ));
    lines.push(String::new());
    lines.push("paths_plan_file() {".to_string());
    lines.push("  local name=\"$1\"".to_string());
    lines.push("  echo \"${PLANS_DIR}/${name}\"".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push("paths_inbox_thread() {".to_string());
    lines.push("  local thread=\"$1\"".to_string());
    lines.push("  echo \"${INBOX_DIR}/${thread}\"".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push("# Mirrors fno.paths.project_log(): <repo>/.fno/<name>, anchored to".to_string());
    lines
        .push("# $REPO_ROOT (never CWD). Hooks route ad-hoc .fno/ writes through this".to_string());
    lines.push("# instead of hand-building \".fno/\" + name strings.".to_string());
    lines.push("paths_project_log() {".to_string());
    lines.push("  local name=\"$1\"".to_string());
    lines.push("  echo \"${REPO_ROOT}/.fno/${name}\"".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.join("\n")
}

/// The repo root, Python `resolve_repo_root` semantics: `FNO_REPO_ROOT` env
/// first, then `git rev-parse --show-toplevel`. None when git fails (the
/// caller refuses rather than write to a guessed root).
fn repo_root() -> Option<PathBuf> {
    if let Some(p) = std::env::var_os("FNO_REPO_ROOT") {
        return Some(PathBuf::from(p));
    }
    let out = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() {
        None
    } else {
        Some(PathBuf::from(s))
    }
}

/// `emit-shell [--output P]`: write the stub atomically (temp sibling +
/// rename, the shape fno.state.io.atomic_write uses) and print
/// `wrote N bytes to P`. Default output is `<repo>/scripts/lib/paths.sh`.
fn run_emit_shell(args: &[String]) -> i32 {
    let mut output: Option<PathBuf> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--output" => match it.next() {
                Some(v) => output = Some(PathBuf::from(v)),
                None => {
                    eprintln!("fno config paths emit-shell: --output needs a path");
                    return 2;
                }
            },
            "--help" | "-h" => {
                println!("usage: fno config paths emit-shell [--output P]");
                return 0;
            }
            other => {
                eprintln!("fno config paths emit-shell: unknown argument {other:?}");
                return 2;
            }
        }
    }
    let out = match output {
        Some(p) => p,
        None => match repo_root() {
            Some(root) => root.join("scripts/lib/paths.sh"),
            None => {
                eprintln!("fno config paths emit-shell: no repo root; pass --output");
                return 1;
            }
        },
    };
    write_stub(&out)
}

/// Atomic write: temp sibling + rename (fno.state.io.atomic_write shape).
fn write_stub(out: &std::path::Path) -> i32 {
    let content = emit_paths_sh_defaults();
    if let Some(parent) = out.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!(
                "fno config paths emit-shell: cannot create {}: {e}",
                parent.display()
            );
            return 1;
        }
    }
    let tmp = out.with_extension(format!("sh.tmp.{}", std::process::id()));
    if let Err(e) = std::fs::write(&tmp, &content) {
        eprintln!(
            "fno config paths emit-shell: cannot write {}: {e}",
            tmp.display()
        );
        return 1;
    }
    if let Err(e) = std::fs::rename(&tmp, out) {
        eprintln!("fno config paths emit-shell: cannot rename into place: {e}");
        let _ = std::fs::remove_file(&tmp);
        return 1;
    }
    println!("wrote {} bytes to {}", content.len(), out.display());
    0
}

/// Worker lane entry for `--paths-exec <verb> [args...]`.
pub fn run(args: &[String]) -> i32 {
    match args.first().map(String::as_str) {
        Some("emit-shell") => run_emit_shell(&args[1..]),
        _ => {
            eprintln!("usage: fno-agents-worker --paths-exec emit-shell [--output P]");
            2
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_defaults_matches_checked_in_fixture() {
        assert_eq!(emit_paths_sh_defaults(), String::from_utf8_lossy(FIXTURE));
    }

    #[test]
    fn helpers_quote_and_relative() {
        assert_eq!(bash_quote("$HOME/.fno"), "\"$HOME/.fno\"");
        assert_eq!(bash_quote("plain"), "plain");
        assert_eq!(home_relative("~/.fno/"), "$HOME/.fno");
        assert_eq!(home_relative("/abs"), "/abs");
        assert!(is_project_relative(".fno/plans"));
        assert!(!is_project_relative("plans/{project}"));
        assert!(has_template("a/{vault}/b"));
        assert!(!has_template("a/{{vault}}/b"));
    }

    #[test]
    fn run_emit_shell_writes_output_file() {
        let dir = std::env::temp_dir().join(format!("fno-paths-cli-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let out = dir.join("out.sh");
        let code = run(&[
            "emit-shell".to_string(),
            "--output".to_string(),
            out.to_string_lossy().into_owned(),
        ]);
        assert_eq!(code, 0);
        let written = std::fs::read(&out).unwrap();
        assert_eq!(written, FIXTURE.to_vec());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn run_refuses_unknown_verb() {
        assert_eq!(run(&["bogus".to_string()]), 2);
    }
}
