//! `fno config paths emit-shell` and `shell-stub`: generate paths.sh natively.
//!
//! One verb per PR (law d-450caaeb): this file serves `emit-shell` and
//! and `handoff`; only `verify` still answers in Python
//! (cli/src/fno/paths_cli.py) until its child node ports. The defaults
//! emitter reproduces the checked-in scripts/lib/paths.sh byte for byte;
//! the include_bytes! parity test fails the build the moment the two drift.
//! The live emitter is the config-aware door: every call regenerates from
//! the settings the caller resolves and prints a sourceable temp path.

use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::finalize::resolve_handoffs_dir;
use crate::identity::canonical_handle;
use crate::lead_checkin::sanitize_scope_key;
use crate::plans_path::{expanduser, project_name, resolve_template, vault_root};

/// The parity fixture: the checked-in stub this emitter must reproduce.
/// Test-only: the include path leaves the crate, which packaging forbids.
#[cfg(test)]
const FIXTURE: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../scripts/lib/paths.sh"
));

/// Quote a value for a bash assignment, the shape of Python `_bash_quote`:
/// a value carrying `$` takes double quotes so bash expands it at runtime
/// (literal `"` and `\` escaped first); anything else takes shlex single
/// quotes, unquoted when every char is shell-safe.
fn bash_quote(value: &str) -> String {
    if value.contains('$') {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        return format!("\"{escaped}\"");
    }
    if value.is_empty() {
        return "''".to_string();
    }
    let safe = value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "@%+=:,./-_".contains(c));
    if safe {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Convert a tilde-prefixed raw value to a `$HOME`-relative template; an
/// absolute path passes through. Trailing slashes strip for consistency.
fn home_relative(raw: &str) -> String {
    let stripped = raw.trim_end_matches('/');
    if let Some(rest) = stripped.strip_prefix("~/") {
        return format!("$HOME/{rest}");
    }
    if stripped == "~" {
        return "$HOME".to_string();
    }
    stripped.to_string()
}

/// True for a bare relative path (no `~`, `/`-root, `$`, or `{` template
/// anywhere -- `plans/{project}` is NOT project-relative).
fn is_project_relative(raw: &str) -> bool {
    let stripped = raw.trim();
    if stripped.is_empty() {
        return false;
    }
    !(stripped.starts_with('/')
        || stripped.starts_with('~')
        || stripped.starts_with('$')
        || stripped.contains('{'))
}

/// True when the raw value carries a `{template}` variable (a `{{` escape
/// never counts, mirroring the Python regex's lookarounds).
fn has_template(raw: &str) -> bool {
    let bytes = raw.as_bytes();
    for i in 0..bytes.len() {
        if bytes[i] != b'{' || (i > 0 && bytes[i - 1] == b'{') {
            continue;
        }
        if let Some(close) = raw[i + 1..].find('}') {
            let close_idx = i + 1 + close;
            let next_dbl = close_idx + 1 < bytes.len() && bytes[close_idx + 1] == b'}';
            let inner = &raw[i + 1..close_idx];
            if !next_dbl && !inner.is_empty() && !inner.contains('{') && !inner.contains('}') {
                return true;
            }
        }
    }
    false
}

fn header_lines() -> Vec<String> {
    let header = r#"#!/usr/bin/env bash
# AUTO-GENERATED by `fno config paths emit-shell`. Do not hand-edit.
# Regenerate after any change to settings.yaml or the schema:
#   fno config paths emit-shell --output scripts/lib/paths.sh
#
# This stub is config-BLIND by design: it is emitted with use_defaults=True so
# regeneration is byte-stable across machines and the checked-in hash verifies.
# It does NOT honor a project's settings.yaml. A bash caller that needs the
# current config's resolved paths (vault-aware handoffs dir, overridden
# state_dir, etc.) must use the config-aware door instead:
#   source "$(fno config paths shell-stub)"
# which regenerates a temp stub from the live settings on every call.

# Self-set REPO_ROOT if unset so this file is safe to source under set -u.
# Callers may still pre-set REPO_ROOT before sourcing to pin the value.
REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
HOME="${HOME:-$(getent passwd "$(id -un)" 2>/dev/null | cut -d: -f6 || echo ~)}"
"#;
    header.lines().map(String::from).collect()
}

/// Emit the config-blind stub from schema defaults only (`use_defaults=True`):
/// `$HOME` and `$REPO_ROOT` stay literal so the bytes are machine-stable and
/// the checked-in hash verifies. Byte-for-byte port of the defaults path of
/// Python `emit_paths_sh`; the include_bytes! parity test pins it.
pub fn emit_paths_sh_defaults() -> String {
    let mut lines = header_lines();
    lines.push(String::new());
    lines.push(format!(
        "export STATE_DIR={}",
        bash_quote(&home_relative("~/.fno/"))
    ));
    for (name, sub) in [
        ("LEDGER_JSON_PATH", "ledger.json"),
        ("BRIEFS_DIR", "briefs"),
        ("FLEET_DIR", "fleet"),
        ("POSTMORTEMS_DIR", "postmortems"),
        ("WORKTREES_BASE", "worktrees"),
        ("MEMORY_DIR", "memory"),
        ("HOOK_LOGS_DIR", "hook-logs"),
        ("LATCHES_DIR", "latches"),
    ] {
        let v = bash_quote(&format!("$STATE_DIR/{sub}"));
        lines.push(format!("export {name}={v}"));
    }
    lines.push(format!(
        "export PLANS_DIR={}",
        bash_quote("$REPO_ROOT/.fno/plans")
    ));
    lines.push(format!(
        "export INBOX_DIR={}",
        bash_quote("$REPO_ROOT/.fno/inbox")
    ));
    // Defaults mode: no handoffs override, obsidian off, project.id unset --
    // the literal fallback line keeps the stub machine-stable; the basename
    // resolves at source-time from the consumer's repo.
    lines
        .push("export HANDOFFS_DIR=\"$STATE_DIR/handoffs/$(basename \"$REPO_ROOT\")\"".to_string());
    lines.push(format!(
        "export CONFIG_FILE={}",
        bash_quote("$STATE_DIR/config.toml")
    ));
    lines.extend(functions_lines());
    lines.push(String::new());
    lines.join("\n")
}

/// The three lazy bash helpers every stub carries, prefaced by one blank
/// line; the caller appends the trailing blank so the join ends in `\n`.
fn functions_lines() -> Vec<String> {
    [
        "",
        "paths_plan_file() {",
        "  local name=\"$1\"",
        "  echo \"${PLANS_DIR}/${name}\"",
        "}",
        "",
        "paths_inbox_thread() {",
        "  local thread=\"$1\"",
        "  echo \"${INBOX_DIR}/${thread}\"",
        "}",
        "",
        "# Mirrors fno.paths.project_log(): <repo>/.fno/<name>, anchored to",
        "# $REPO_ROOT (never CWD). Hooks route ad-hoc .fno/ writes through this",
        "# instead of hand-building \".fno/\" + name strings.",
        "paths_project_log() {",
        "  local name=\"$1\"",
        "  echo \"${REPO_ROOT}/.fno/${name}\"",
        "}",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect()
}

/// The repo root, Python `resolve_repo_root` semantics: `FNO_REPO_ROOT` env
/// first, then `git rev-parse --show-toplevel`. None when git fails (the
/// caller refuses rather than write to a guessed root).
fn repo_root() -> Option<PathBuf> {
    if let Some(p) = std::env::var_os("FNO_REPO_ROOT") {
        return Some(PathBuf::from(p));
    }
    let out = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() {
        None
    } else {
        Some(PathBuf::from(s))
    }
}

/// `emit-shell [--output P]`: write the stub atomically (temp sibling +
/// rename, the shape fno.state.io.atomic_write uses) and print
/// `wrote N bytes to P`. Default output is `<repo>/scripts/lib/paths.sh`.
fn run_emit_shell(args: &[String]) -> i32 {
    let mut output: Option<PathBuf> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--output" => match it.next() {
                Some(v) => output = Some(PathBuf::from(v)),
                None => {
                    eprintln!("fno config paths emit-shell: --output needs a path");
                    return 2;
                }
            },
            "--help" | "-h" => {
                println!("usage: fno config paths emit-shell [--output P]");
                return 0;
            }
            other => {
                eprintln!("fno config paths emit-shell: unknown argument {other:?}");
                return 2;
            }
        }
    }
    let out = match output {
        Some(p) => p,
        None => match repo_root() {
            Some(root) => root.join("scripts/lib/paths.sh"),
            None => {
                eprintln!("fno config paths emit-shell: no repo root; pass --output");
                return 1;
            }
        },
    };
    write_stub(&out)
}

/// Atomic write: temp sibling + rename (fno.state.io.atomic_write shape).
fn write_stub(out: &std::path::Path) -> i32 {
    let content = emit_paths_sh_defaults();
    if let Some(parent) = out.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!(
                "fno config paths emit-shell: cannot create {}: {e}",
                parent.display()
            );
            return 1;
        }
    }
    let tmp = out.with_extension(format!("sh.tmp.{}", std::process::id()));
    if let Err(e) = std::fs::write(&tmp, &content) {
        eprintln!(
            "fno config paths emit-shell: cannot write {}: {e}",
            tmp.display()
        );
        return 1;
    }
    if let Err(e) = std::fs::rename(&tmp, out) {
        eprintln!("fno config paths emit-shell: cannot rename into place: {e}");
        let _ = std::fs::remove_file(&tmp);
        return 1;
    }
    println!("wrote {} bytes to {}", content.len(), out.display());
    0
}

/// Today's local date as YYYYMMDD, the Python `datetime.now().strftime`
/// filename prefix.
fn local_date() -> String {
    chrono::Local::now().format("%Y%m%d").to_string()
}

/// `handoff [--session-id S | --slug S | --scope S] [--name-only]`: print the
/// save path for a canon handoff doc (Python `paths_cli.handoff` parity). The
/// filename key is the session's canonical handle (first-8) unless --slug
/// overrides. --scope keys the doc on the crown instead -- a crown outlives
/// its sessions -- and returns the newest existing doc for that scope, so a
/// successor session resolves its predecessor's doc; today's dated name when
/// none exists yet. Every argv refusal exits 2, the typer BadParameter code.
fn handoff_out(args: &[String], cwd: &Path, home: Option<&Path>) -> Result<String, String> {
    let mut session_id: Option<String> = None;
    let mut slug: Option<String> = None;
    let mut scope: Option<String> = None;
    let mut name_only = false;
    // Attached `--flag=value` spellings split here: the retired Click command
    // accepted them, so a port matching only the separated spelling would
    // refuse callers that never were wrong.
    let split: Vec<(String, Option<String>)> = args
        .iter()
        .map(|a| match a.split_once('=') {
            Some((flag @ ("--session-id" | "--slug" | "--scope"), v)) => {
                (flag.to_string(), Some(v.to_string()))
            }
            _ => (a.clone(), None),
        })
        .collect();
    let mut it = split.into_iter();
    while let Some((a, attached)) = it.next() {
        match a.as_str() {
            "--session-id" => {
                session_id = Some(match attached {
                    Some(v) => v,
                    None => it
                        .next()
                        .map(|(v, _)| v)
                        .ok_or_else(|| "--session-id needs a value".to_string())?,
                })
            }
            "--slug" => {
                slug = Some(match attached {
                    Some(v) => v,
                    None => it
                        .next()
                        .map(|(v, _)| v)
                        .ok_or_else(|| "--slug needs a value".to_string())?,
                })
            }
            "--scope" => {
                scope = Some(match attached {
                    Some(v) => v,
                    None => it
                        .next()
                        .map(|(v, _)| v)
                        .ok_or_else(|| "--scope needs a value".to_string())?,
                })
            }
            "--name-only" => name_only = true,
            "--help" | "-h" => {
                return Ok(
                    "usage: fno config paths handoff [--session-id S | --slug S | --scope S] [--name-only]"
                        .into(),
                )
            }
            other => return Err(format!("unknown argument {other:?}")),
        }
    }
    let directory = resolve_handoffs_dir(None, None, cwd, home);
    if let Some(scope) = scope {
        if session_id.is_some() || slug.is_some() {
            return Err("--scope cannot be combined with --session-id/--slug".into());
        }
        let key = format!("crown-{}", sanitize_scope_key(&scope));
        if key == "crown-" {
            return Err("a crown scope is required (--scope)".into());
        }
        let suffix = format!("-{key}.md");
        let mut best: Option<(std::time::SystemTime, String)> = None;
        if let Ok(rd) = std::fs::read_dir(&directory) {
            for entry in rd.flatten() {
                let name = entry.file_name();
                let Some(name) = name.to_str() else {
                    continue;
                };
                if !name.ends_with(&suffix) || !entry.path().is_file() {
                    continue;
                }
                // A concurrent refresh can unlink between read_dir and stat;
                // a vanished candidate sorts oldest and the writer recreates
                // the file anyway (Python `_mtime` parity).
                let mtime = entry
                    .metadata()
                    .and_then(|m| m.modified())
                    .unwrap_or(std::time::UNIX_EPOCH);
                if best.as_ref().map_or(true, |(t, _)| mtime > *t) {
                    best = Some((mtime, name.to_string()));
                }
            }
        }
        let filename = best
            .map(|(_, n)| n)
            .unwrap_or_else(|| format!("{}-{key}.md", local_date()));
        return Ok(render_handoff(&directory, &filename, name_only));
    }
    let Some(session_id) = session_id else {
        return Err("a session id is required (--session-id), or a crown scope (--scope)".into());
    };
    // A shell expanding an unset value hands us Some(""); the retired command
    // rejected it (`if not session_id`) rather than render the shared
    // `<date>-.md` name, and a blank --slug fell back to the handle
    // (`key = slug or canonical_handle(...)`).
    if session_id.trim().is_empty() {
        return Err("--session-id needs a value".into());
    }
    let slug = slug.filter(|s| !s.trim().is_empty());
    let key = slug.unwrap_or_else(|| canonical_handle(session_id.trim()));
    let filename = format!("{}-{key}.md", local_date());
    Ok(render_handoff(&directory, &filename, name_only))
}

/// The printed answer: just the filename under --name-only, else the full path.
fn render_handoff(directory: &Path, filename: &str, name_only: bool) -> String {
    if name_only {
        filename.to_string()
    } else {
        directory.join(filename).display().to_string()
    }
}

fn run_handoff(args: &[String], cwd: &Path, home: Option<&Path>) -> i32 {
    match handoff_out(args, cwd, home) {
        Ok(line) => {
            println!("{line}");
            0
        }
        Err(msg) => {
            eprintln!("fno config paths handoff: {msg}");
            2
        }
    }
}

/// Refuse what Python's SettingsModel validators refuse at load: no shell
/// glob character survives into an emitted path value.
fn glob_check(field: &str, raw: &str) -> Result<(), String> {
    if raw.contains('*') || raw.contains('?') || raw.contains('[') {
        Err(format!(
            "{field} contains glob character(s); glob characters are not allowed in path values"
        ))
    } else {
        Ok(())
    }
}

/// One config value, format-agnostic like the Python loader: `$FNO_CONFIG`
/// may pin a legacy YAML file the Python loader parses by suffix, and the
/// smoke suite pins exactly that shape for this verb, so the emitter reads
/// both formats where the TOML-only getters read one.
fn live_lookup(cwd: &Path, keys: &[&str]) -> Option<Result<toml::Value, ()>> {
    if let Some(explicit) = std::env::var_os("FNO_CONFIG").filter(|v| !v.is_empty()) {
        let path = PathBuf::from(&explicit);
        if matches!(
            path.extension().and_then(|e| e.to_str()),
            Some("yaml" | "yml")
        ) {
            let content = std::fs::read_to_string(&path).ok()?;
            let doc: serde_yaml_ng::Value = serde_yaml_ng::from_str(&content).ok()?;
            // A legacy settings.yaml wraps every key in a `config:` block;
            // try the bare walk first, then the envelope.
            fn walk<'a>(
                doc: &'a serde_yaml_ng::Value,
                keys: &[&str],
            ) -> Option<&'a serde_yaml_ng::Value> {
                let mut cur = doc.get(keys[0])?;
                for k in &keys[1..] {
                    cur = cur.get(k)?;
                }
                Some(cur)
            }
            let hit = walk(&doc, keys).or_else(|| {
                let mut full = Vec::with_capacity(keys.len() + 1);
                full.push("config");
                full.extend_from_slice(keys);
                walk(&doc, &full)
            })?;
            let cur = hit;
            return Some(match cur {
                serde_yaml_ng::Value::String(s) => Ok(toml::Value::String(s.clone())),
                serde_yaml_ng::Value::Bool(b) => Ok(toml::Value::Boolean(*b)),
                _ => Err(()),
            });
        }
    }
    crate::agents_config::config_lookup(cwd, keys).map(Ok)
}

fn cfg_str(cwd: &Path, keys: &[&str]) -> Option<String> {
    live_lookup(cwd, keys)
        .and_then(|r| r.ok())
        .and_then(|v| v.as_str().map(str::to_string))
}

/// Python `paths.state_dir()`'s chain: `FNO_STATE_DIR` first, then the
/// configured value through the template resolver.
fn state_dir_resolved(cwd: &Path) -> Result<PathBuf, String> {
    if let Some(carrier) = std::env::var_os("FNO_STATE_DIR").filter(|v| !v.is_empty()) {
        return Ok(crate::paths::resolve_loose(&expanduser(
            &carrier.to_string_lossy(),
        )));
    }
    let raw = cfg_str(cwd, &["state_dir"]).unwrap_or_else(|| "~/.fno/".to_string());
    resolve_template(raw.trim_end_matches('/'), None)
}

/// One `paths.<key>` override value, the shape Python's emitter shares for
/// every override: a `{template}` resolves at codegen time, a `~` value
/// goes `$HOME`-relative, anything else passes through verbatim.
fn resolve_override(raw: &str) -> Result<String, String> {
    glob_check("paths override", raw)?;
    let stripped = raw.trim_end_matches('/');
    if has_template(stripped) {
        Ok(resolve_template(stripped, None)?
            .to_string_lossy()
            .into_owned())
    } else if stripped.starts_with('~') {
        Ok(home_relative(stripped))
    } else {
        Ok(stripped.to_string())
    }
}

/// One `paths.<key>` override against its `$STATE_DIR/<sub>` default, the
/// shape of Python `_state_subpath`: a `{template}` resolves at codegen
/// time, a `~` value goes `$HOME`-relative, anything else passes through.
fn state_subpath(override_: Option<String>, subdir: &str) -> Result<String, String> {
    match override_ {
        Some(raw) => resolve_override(&raw),
        None => Ok(format!("$STATE_DIR/{subdir}")),
    }
}

/// The live-settings emitter (`use_defaults=False`): every path reflects
/// the config the caller resolves, with `{vault}`/`{project}` templates
/// resolved at codegen time so shell consumers never see raw template
/// tokens. Byte-shape port of the live branch of Python `emit_paths_sh`.
pub fn emit_paths_sh_live(cwd: &Path) -> Result<String, String> {
    // STATE_DIR: home-relative or absolute; a template value resolves
    // through the full state-dir chain.
    let state_raw = cfg_str(cwd, &["state_dir"]).unwrap_or_else(|| "~/.fno/".to_string());
    glob_check("path field", &state_raw)?;
    let state_stripped = state_raw.trim_end_matches('/');
    let state_tmpl = if has_template(state_stripped) {
        state_dir_resolved(cwd)?.to_string_lossy().into_owned()
    } else {
        home_relative(state_stripped)
    };

    let mut lines = header_lines();
    lines.push(String::new());
    lines.push(format!("export STATE_DIR={}", bash_quote(&state_tmpl)));

    for (name, key, sub) in [
        ("LEDGER_JSON_PATH", "ledger_json", "ledger.json"),
        ("BRIEFS_DIR", "briefs_dir", "briefs"),
        ("FLEET_DIR", "fleet_dir", "fleet"),
        ("POSTMORTEMS_DIR", "postmortems_dir", "postmortems"),
        ("WORKTREES_BASE", "worktrees_base", "worktrees"),
        ("MEMORY_DIR", "memory_dir", "memory"),
        ("HOOK_LOGS_DIR", "hook_logs_dir", "hook-logs"),
    ] {
        let override_ = cfg_str(cwd, &["paths", key]);
        if let Some(raw) = &override_ {
            glob_check("paths override", raw)?;
        }
        let v = state_subpath(override_, sub)?;
        lines.push(format!("export {name}={}", bash_quote(&v)));
    }
    // No config override: latches_dir() tracks state_dir by design.
    lines.push(format!(
        "export LATCHES_DIR={}",
        bash_quote("$STATE_DIR/latches")
    ));

    // PLANS_DIR: project-relative by default.
    let plans_raw = cfg_str(cwd, &["plans_dir"]).unwrap_or_else(|| ".fno/plans/".to_string());
    glob_check("path field", &plans_raw)?;
    let plans = plans_raw.trim_end_matches('/');
    let plans_tmpl = if is_project_relative(plans) {
        format!("$REPO_ROOT/{plans}")
    } else if has_template(plans) {
        resolve_template(plans, None)?
            .to_string_lossy()
            .into_owned()
    } else if plans.starts_with('~') {
        home_relative(plans)
    } else {
        plans.to_string()
    };
    lines.push(format!("export PLANS_DIR={}", bash_quote(&plans_tmpl)));

    // INBOX_DIR: project-relative by default.
    let inbox_tmpl = match cfg_str(cwd, &["paths", "inbox_dir"]) {
        Some(raw) => resolve_override(&raw)?,
        None => "$REPO_ROOT/.fno/inbox".to_string(),
    };
    lines.push(format!("export INBOX_DIR={}", bash_quote(&inbox_tmpl)));

    // HANDOFFS_DIR: override, else the vault placement, else the state-dir
    // fallback -- mirrors paths.handoffs_dir() resolution.
    let handoffs = match cfg_str(cwd, &["paths", "handoffs_dir"]) {
        Some(raw) => resolve_override(&raw)?,
        None => {
            let enabled = live_lookup(cwd, &["obsidian", "enabled"])
                .and_then(|r| r.ok())
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let vault = cfg_str(cwd, &["obsidian", "vault"]);
            if enabled {
                match &vault {
                    Some(v) => glob_check("obsidian.vault", v)?,
                    None => return Err("obsidian is enabled with no vault path set".to_string()),
                }
                let root = vault_root(cwd)?;
                let name = project_name(Some(cwd))?;
                Path::new(&root)
                    .join("internal")
                    .join(name)
                    .join("handoffs")
                    .to_string_lossy()
                    .into_owned()
            } else {
                match cfg_str(cwd, &["project", "id"]).filter(|p| !p.is_empty()) {
                    Some(pid) => {
                        // The Python loader refuses any other project.id at
                        // validation time; the raw read must refuse it too,
                        // or the id interpolates into sourced shell code.
                        if !pid
                            .chars()
                            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
                        {
                            return Err(format!(
                                "project.id {pid:?} contains invalid characters; only [A-Za-z0-9._-] are allowed"
                            ));
                        }
                        format!("$STATE_DIR/handoffs/{pid}")
                    }
                    None => return Ok(finish_live_stub(
                        cwd,
                        lines,
                        "export HANDOFFS_DIR=\"$STATE_DIR/handoffs/$(basename \"$REPO_ROOT\")\"",
                    )),
                }
            }
        }
    };
    let handoffs_line = format!("export HANDOFFS_DIR={}", bash_quote(&handoffs));
    Ok(finish_live_stub(cwd, lines, &handoffs_line))
}

/// Shared tail: the handoffs line (already formatted), the live CONFIG_FILE
/// read (the file the caller's config actually loads), and the bash helpers.
fn finish_live_stub(cwd: &Path, mut lines: Vec<String>, handoffs_line: &str) -> String {
    lines.push(handoffs_line.to_string());
    let config_file = crate::agents_config::config_candidates(cwd)
        .into_iter()
        .find(|p| {
            let yaml = matches!(p.extension().and_then(|e| e.to_str()), Some("yaml" | "yml"));
            std::fs::read_to_string(p)
                .map(|c| {
                    if yaml {
                        serde_yaml_ng::from_str::<serde_yaml_ng::Value>(&c).is_ok()
                    } else {
                        c.parse::<toml::Table>().is_ok()
                    }
                })
                .unwrap_or(false)
        })
        .unwrap_or_else(|| {
            crate::agents_config::state_dir(cwd)
                .unwrap_or_else(|| PathBuf::from("~/.fno"))
                .join("config.toml")
        });
    lines.push(format!(
        "export CONFIG_FILE={}",
        bash_quote(&config_file.to_string_lossy())
    ));
    lines.extend(functions_lines());
    lines.push(String::new());
    lines.join("\n")
}

/// `shell-stub`: write the live stub to a fresh temp file and print its
/// path; bash callers `source "$(fno config paths shell-stub)"` and every
/// call regenerates from the current settings.
fn write_shell_stub(cwd: &Path) -> Result<PathBuf, String> {
    let content = emit_paths_sh_live(cwd)?;
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    let path = std::env::temp_dir().join(format!("fno-paths-{}-{nanos}.sh", std::process::id()));
    std::fs::write(&path, &content).map_err(|e| format!("cannot write {}: {e}", path.display()))?;
    Ok(path)
}

fn run_shell_stub() -> i32 {
    let cwd = match std::env::current_dir() {
        Ok(c) => c,
        Err(e) => {
            eprintln!("fno config paths shell-stub: no working directory: {e}");
            return 1;
        }
    };
    match write_shell_stub(&cwd) {
        Ok(p) => {
            println!("{}", p.display());
            0
        }
        Err(e) => {
            eprintln!("fno config paths shell-stub: {e}");
            1
        }
    }
}

/// `verify [PATH]`: compare the schema-derived sha256 with the file's.
/// Same messages the retired Python verify_cmd printed, byte for byte.
fn run_verify(args: &[String]) -> i32 {
    let mut path: Option<PathBuf> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--help" | "-h" => {
                println!("usage: fno config paths verify [PATH]");
                return 0;
            }
            other => {
                if other.starts_with('-') {
                    eprintln!("fno config paths verify: unknown argument {other:?}");
                    return 2;
                }
                if path.is_some() {
                    eprintln!("fno config paths verify: takes at most one PATH");
                    return 2;
                }
                path = Some(PathBuf::from(other));
            }
        }
    }
    let target = match path {
        Some(p) => p,
        None => match repo_root() {
            Some(root) => root.join("scripts/lib/paths.sh"),
            None => {
                eprintln!("fno config paths verify: no repo root; pass PATH");
                return 1;
            }
        },
    };
    if !target.exists() {
        eprintln!(
            "error: {} does not exist. Generate it with: fno config paths emit-shell",
            target.display()
        );
        return 1;
    }
    let bytes = match std::fs::read(&target) {
        Ok(b) => b,
        Err(e) => {
            eprintln!(
                "fno config paths verify: cannot read {}: {e}",
                target.display()
            );
            return 1;
        }
    };
    let derived = hex(&Sha256::digest(emit_paths_sh_defaults().as_bytes()));
    let checked = hex(&Sha256::digest(&bytes));
    if derived == checked {
        println!(
            "paths.sh is in sync with schema (hash: {}...)",
            &derived[..12]
        );
        0
    } else {
        eprintln!(
            "--- expected (from schema)\n+++ checked-in\nschema hash:  {derived}\nfile hash:    {checked}\n\nHashes differ. Regenerate with:\n  fno config paths emit-shell"
        );
        1
    }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Worker lane entry for `--paths-exec <verb> [args...]`.
pub fn run(args: &[String]) -> i32 {
    match args.first().map(String::as_str) {
        Some("emit-shell") => run_emit_shell(&args[1..]),
        Some("shell-stub") => {
            if args.len() > 1 {
                eprintln!("fno config paths shell-stub: takes no arguments");
                return 2;
            }
            run_shell_stub()
        }
        Some("handoff") => {
            let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            let home = std::env::var_os("HOME").map(PathBuf::from);
            run_handoff(&args[1..], &cwd, home.as_deref())
        }
        Some("verify") => run_verify(&args[1..]),
        _ => {
            eprintln!(
                "usage: fno-agents-worker --paths-exec <emit-shell|shell-stub|verify|handoff> [args...]"
            );
            2
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_defaults_matches_checked_in_fixture() {
        assert_eq!(emit_paths_sh_defaults(), String::from_utf8_lossy(FIXTURE));
    }

    #[test]
    fn helpers_quote_and_relative() {
        assert_eq!(bash_quote("$HOME/.fno"), "\"$HOME/.fno\"");
        assert_eq!(bash_quote("plain"), "plain");
        assert_eq!(home_relative("~/.fno/"), "$HOME/.fno");
        assert_eq!(home_relative("/abs"), "/abs");
        assert!(is_project_relative(".fno/plans"));
        assert!(!is_project_relative("plans/{project}"));
        assert!(has_template("a/{vault}/b"));
        assert!(!has_template("a/{{vault}}/b"));
    }

    #[test]
    fn run_emit_shell_writes_output_file() {
        let dir = std::env::temp_dir().join(format!("fno-paths-cli-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let out = dir.join("out.sh");
        let code = run(&[
            "emit-shell".to_string(),
            "--output".to_string(),
            out.to_string_lossy().into_owned(),
        ]);
        assert_eq!(code, 0);
        let written = std::fs::read(&out).unwrap();
        assert_eq!(written, FIXTURE.to_vec());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn run_refuses_unknown_verb() {
        assert_eq!(run(&["bogus".to_string()]), 2);
    }

    // ── handoff ─────────────────────────────────────────────────────────────

    /// A uuid whose first-8 handle is unambiguous and not equal to its last-8.
    const SID: &str = "c35abbca-bd2d-4407-8365-cf468baa7eea";

    /// An isolated cwd/home pair; with no settings in either, the handoffs
    /// dir resolves to `<home>/.fno/handoffs/<cwd-basename>` (the resolution
    /// itself is pinned by finalize.rs's resolve_handoffs_dir tests).
    fn handoff_fixture(tag: &str) -> (PathBuf, PathBuf) {
        let dir = std::env::temp_dir().join(format!("fno-paths-ho-{tag}-{}", std::process::id()));
        let cwd = dir.join("repo");
        let home = dir.join("home");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&cwd).unwrap();
        std::fs::create_dir_all(&home).unwrap();
        (cwd, home)
    }

    fn handoff_dir(cwd: &Path, home: &Path) -> PathBuf {
        resolve_handoffs_dir(None, None, cwd, Some(home))
    }

    fn stamp_mtime(p: &Path, secs: u64) {
        std::fs::File::options()
            .write(true)
            .open(p)
            .unwrap()
            .set_modified(std::time::UNIX_EPOCH + std::time::Duration::from_secs(secs))
            .unwrap();
    }

    /// Serializes against the env-pinning fixtures and neutralizes the
    /// ambient handoff pins for this test's scope: resolve_handoffs_dir reads
    /// FNO_STATE_DIR/FNO_CONFIG/HANDOFFS_DIR, so a concurrent live-fixture
    /// test's process env would reroute the resolution into its tree.
    fn handoff_env_guards() -> (std::sync::MutexGuard<'static, ()>, [EnvVarGuard; 3]) {
        let lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        (
            lock,
            [
                EnvVarGuard::set("FNO_STATE_DIR", ""),
                EnvVarGuard::set("FNO_CONFIG", ""),
                EnvVarGuard::set("HANDOFFS_DIR", ""),
            ],
        )
    }

    use crate::claims::EnvVarGuard;

    #[test]
    fn handoff_key_derivation_first_eight_then_slug() {
        let (_lock, _env) = handoff_env_guards();
        let (cwd, home) = handoff_fixture("first8");
        let out = handoff_out(
            &["--session-id".into(), SID.into(), "--name-only".into()],
            &cwd,
            Some(&home),
        )
        .unwrap();
        // Guards the both-ends truncation hazard: the key must be the head
        // (c35abbca), never the tail (8baa7eea).
        let (date, rest) = out.split_once('-').unwrap();
        assert!(
            date.len() == 8 && date.chars().all(|c| c.is_ascii_digit()),
            "{out}"
        );
        assert_eq!(rest, "c35abbca.md");
        let out = handoff_out(
            &[
                "--session-id".into(),
                SID.into(),
                "--slug".into(),
                "my-feature".into(),
                "--name-only".into(),
            ],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert!(out.ends_with("-my-feature.md"), "{out}");
        assert!(!out.contains("c35abbca"), "{out}");
        // The attached --flag=value spelling: the retired Click command
        // accepted it, so the port must too, or it refuses callers that
        // never were wrong.
        let out = handoff_out(
            &[
                "--session-id=c35abbca-bd2d-4407-8365-cf468baa7eea".into(),
                "--name-only".into(),
            ],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert!(out.ends_with("-c35abbca.md"), "{out}");
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_full_path_joins_the_handoffs_dir() {
        let (_lock, _env) = handoff_env_guards();
        let (cwd, home) = handoff_fixture("fullpath");
        let dir = handoff_dir(&cwd, &home);
        let full = handoff_out(&["--session-id".into(), SID.into()], &cwd, Some(&home)).unwrap();
        let name = handoff_out(
            &["--session-id".into(), SID.into(), "--name-only".into()],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert_eq!(Path::new(&full).parent().unwrap(), dir);
        assert_eq!(
            Path::new(&full).file_name().unwrap().to_str().unwrap(),
            name
        );
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_empty_session_refuses_and_blank_slug_falls_back() {
        let (_lock, _env) = handoff_env_guards();
        let (cwd, home) = handoff_fixture("refuse");
        // The hidden --session alias was removed to pay the flag-surface
        // ratchet (operator ruling 2026-09-12); --session-id is the one
        // spelling.
        assert!(handoff_out(
            &["--session".into(), SID.into(), "--name-only".into()],
            &cwd,
            Some(&home)
        )
        .is_err());
        let scope = ["--scope".to_string(), "x-aaaa1111".into()];
        let mut v = scope.to_vec();
        v.extend(["--session-id".into(), SID.into()]);
        assert!(handoff_out(&v, &cwd, Some(&home)).is_err());
        let mut v = scope.to_vec();
        v.extend(["--slug".into(), "s".into()]);
        assert!(handoff_out(&v, &cwd, Some(&home)).is_err());
        assert!(handoff_out(&[], &cwd, Some(&home)).is_err());
        // A shell expanding an unset value hands us Some(""); the shared
        // `<date>-.md` name must never render.
        assert!(handoff_out(
            &["--session-id".into(), "".into(), "--name-only".into()],
            &cwd,
            Some(&home),
        )
        .is_err());
        // A blank --slug falls back to the canonical handle (Python
        // `key = slug or canonical_handle(...)`).
        let out = handoff_out(
            &[
                "--session-id".into(),
                SID.into(),
                "--slug".into(),
                "".into(),
                "--name-only".into(),
            ],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert!(out.ends_with("-c35abbca.md"), "{out}");
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_mints_a_dated_crown_keyed_name() {
        let (_lock, _env) = handoff_env_guards();
        let (cwd, home) = handoff_fixture("scope-mint");
        let scope = "x-1234abcd";
        let out = handoff_out(
            &["--scope".into(), scope.into(), "--name-only".into()],
            &cwd,
            Some(&home),
        )
        .unwrap();
        let (date, rest) = out.split_once('-').unwrap();
        assert!(
            date.len() == 8 && date.chars().all(|c| c.is_ascii_digit()),
            "{out}"
        );
        assert_eq!(rest, format!("crown-{scope}.md"));
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_returns_the_newest_existing_doc() {
        let (_lock, _env) = handoff_env_guards();
        let (cwd, home) = handoff_fixture("scope-newest");
        let scope = "x-2222bbbb";
        let dir = handoff_dir(&cwd, &home);
        std::fs::create_dir_all(&dir).unwrap();
        let old = dir.join(format!("20260901-crown-{scope}.md"));
        let new = dir.join(format!("20260909-crown-{scope}.md"));
        std::fs::write(&old, "predecessor").unwrap();
        std::fs::write(&new, "successor").unwrap();
        stamp_mtime(&old, 1_000_000);
        stamp_mtime(&new, 2_000_000);
        let full = handoff_out(&["--scope".into(), scope.into()], &cwd, Some(&home)).unwrap();
        assert_eq!(Path::new(&full), new);
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_newest_ignores_other_scopes_and_session_keys() {
        let (_lock, _env) = handoff_env_guards();
        let (cwd, home) = handoff_fixture("scope-filter");
        let scope = "x-3333cccc";
        let dir = handoff_dir(&cwd, &home);
        std::fs::create_dir_all(&dir).unwrap();
        let other = dir.join("20260909-crown-x-9999zzzz.md");
        let session_key = dir.join("20260909-c35abbca.md");
        let mine = dir.join(format!("20260901-crown-{scope}.md"));
        for p in [&other, &session_key, &mine] {
            std::fs::write(p, "x").unwrap();
        }
        stamp_mtime(&other, 9_999_999);
        stamp_mtime(&session_key, 9_999_999);
        stamp_mtime(&mine, 1_000_000);
        let full = handoff_out(&["--scope".into(), scope.into()], &cwd, Some(&home)).unwrap();
        assert_eq!(Path::new(&full), mine);
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_sanitizes_runs_into_one_dash() {
        let (_lock, _env) = handoff_env_guards();
        // A portfolio crown stores its scope comma-joined; commas and spaces
        // are not filename-safe, so each unsafe RUN collapses into one key
        // separator (Python re.sub(r"[^A-Za-z0-9._-]+", "-") parity).
        let (cwd, home) = handoff_fixture("scope-sanitize");
        let out = handoff_out(
            &[
                "--scope".into(),
                "x-aaaa1111, x-bbbb2222".into(),
                "--name-only".into(),
            ],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert!(out.ends_with(".md") && out.contains("-crown-x-"), "{out}");
        assert!(!out.contains(',') && !out.contains(' '), "{out}");
        assert!(!out.contains("--"), "{out}");
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    // -- verify: contracts ported from cli/tests/integration/test_paths_sh_gate.py --

    #[test]
    fn run_verify_contracts() {
        let dir = std::env::temp_dir().join(format!("fno-paths-verify-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("paths.sh");
        std::fs::write(&p, FIXTURE).unwrap();
        let arg = p.to_string_lossy().into_owned();

        // matching content passes
        assert_eq!(run(&["verify".to_string(), arg.clone()]), 0);

        // a mtime-only touch still passes: the contract is content hash, not mtime
        let f = std::fs::OpenOptions::new().append(true).open(&p).unwrap();
        f.set_times(
            std::fs::FileTimes::new().set_modified(
                std::time::SystemTime::UNIX_EPOCH + std::time::Duration::from_secs(1),
            ),
        )
        .unwrap();
        assert_eq!(run(&["verify".to_string(), arg.clone()]), 0);

        // one flipped byte fails
        let mut bytes = FIXTURE.to_vec();
        bytes[0] ^= 0x20;
        std::fs::write(&p, &bytes).unwrap();
        assert_eq!(run(&["verify".to_string(), arg.clone()]), 1);

        // a missing file fails
        let missing = dir.join("nope.sh").to_string_lossy().into_owned();
        assert_eq!(run(&["verify".to_string(), missing]), 1);

        // an unknown flag is a usage error
        assert_eq!(run(&["verify".to_string(), "--bogus".to_string()]), 2);

        let _ = std::fs::remove_dir_all(&dir);
    }

    // -- live emitter (shell-stub): contracts ported from the Python
    //    shell-stub tests (Finding C) and the kept live-mode tests in
    //    cli/tests/unit/test_emit_shell.py --

    use crate::claims::test_env_lock;
    use std::fs;

    /// One temp config: `FNO_CONFIG` pins it as the sole candidate, the
    /// state root pins inside the temp tree, and cwd stays a real dir.
    struct LiveFx {
        base: PathBuf,
        config: PathBuf,
        root: PathBuf,
    }

    impl LiveFx {
        fn new(tag: &str, body: &str) -> Self {
            let base =
                std::env::temp_dir().join(format!("fno-paths-live-{}-{}", tag, std::process::id()));
            let _ = fs::remove_dir_all(&base);
            let root = base.join("proj");
            fs::create_dir_all(&root).unwrap();
            let config = base.join("config.toml");
            fs::write(&config, body).unwrap();
            LiveFx { base, config, root }
        }

        fn body(&self, text: &str) {
            fs::write(&self.config, text).unwrap();
        }

        fn pins(&self) -> Vec<(&'static str, String)> {
            vec![
                ("FNO_CONFIG", self.config.display().to_string()),
                (
                    "FNO_STATE_DIR",
                    self.base.join("state").display().to_string(),
                ),
            ]
        }
    }

    impl Drop for LiveFx {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.base);
        }
    }

    struct EnvGuard {
        saved: Vec<(&'static str, Option<std::ffi::OsString>)>,
    }

    impl EnvGuard {
        fn new(pins: &[(&'static str, String)]) -> Self {
            let saved = pins
                .iter()
                .map(|(k, _)| (*k, std::env::var_os(k)))
                .collect();
            for (k, v) in pins {
                std::env::set_var(k, v);
            }
            EnvGuard { saved }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            for (k, v) in &self.saved {
                match v {
                    Some(old) => std::env::set_var(k, old),
                    None => std::env::remove_var(k),
                }
            }
        }
    }

    fn line_with<'a>(stub: &'a str, needle: &str) -> &'a str {
        stub.lines()
            .find(|l| l.contains(needle))
            .unwrap_or_else(|| panic!("no line containing {needle:?} in:\n{stub}"))
    }

    #[test]
    fn shell_stub_prints_a_sourceable_temp_path() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("sourceable", "");
        let _env = EnvGuard::new(&fx.pins());
        assert_eq!(run(&["shell-stub".to_string()]), 0);
        // The printed path is the only stdout line; find it from the temp dir.
        let entries: Vec<_> = std::env::temp_dir()
            .read_dir()
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| {
                p.file_name()
                    .map(|n| {
                        n.to_string_lossy()
                            .starts_with(&format!("fno-paths-{}-", std::process::id()))
                    })
                    .unwrap_or(false)
            })
            .collect();
        assert!(!entries.is_empty(), "shell-stub printed no temp path");
        for p in entries {
            let content = fs::read_to_string(&p).unwrap();
            let out = Command::new("bash")
                .arg("-c")
                .arg(format!("source {} && echo $STATE_DIR", p.display()))
                .output()
                .unwrap();
            assert!(out.status.success(), "bash source failed: {:?}", out.stderr);
            let state = String::from_utf8_lossy(&out.stdout);
            assert!(
                state.trim().contains('/'),
                "STATE_DIR not absolute: {state:?}"
            );
            let _ = content;
        }
    }

    #[test]
    fn shell_stub_regenerates_from_current_settings() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("regen", "");
        let _env = EnvGuard::new(&fx.pins());
        let p1 = write_shell_stub(&fx.root).unwrap();
        let first = fs::read_to_string(&p1).unwrap();
        let _ = fs::remove_file(&p1);

        fx.body("plans_dir = '.fno/my-custom-plans'\n");
        let p2 = write_shell_stub(&fx.root).unwrap();
        let second = fs::read_to_string(&p2).unwrap();
        let _ = fs::remove_file(&p2);

        assert_ne!(p1, p2, "each call writes a fresh temp file");
        assert_ne!(first, second, "each call regenerates from live settings");
        assert!(second.contains("my-custom-plans"), "stub:\n{second}");
    }

    #[test]
    fn live_stub_reflects_custom_state_dir() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("state", "state_dir = '~/.my-custom-fno'\n");
        let _env = EnvGuard::new(&fx.pins());
        let stub = emit_paths_sh_live(&fx.root).unwrap();
        assert!(stub.contains("$HOME/.my-custom-fno"), "stub:\n{stub}");
    }

    #[test]
    fn live_stub_resolves_vault_templates() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("vault", "");
        fx.body(&format!(
            "state_dir = '{{vault}}/state'\n[project]\nid = 'testproj'\n[obsidian]\nenabled = true\nvault = '{}'\n",
            fx.base.display()
        ));
        let _env = EnvGuard::new(&fx.pins());
        let stub = emit_paths_sh_live(&fx.root).unwrap();
        let expected = format!("{}/state", fx.base.display());
        assert!(stub.contains(&expected), "stub:\n{stub}");
        assert!(!stub.contains("{vault}") && !stub.contains("{project}"));
        let line = line_with(&stub, "export HANDOFFS_DIR=");
        let handoffs = format!("{}/internal/testproj/handoffs", fx.base.display());
        assert!(line.contains(&handoffs), "HANDOFFS_DIR: {line}");
    }

    #[test]
    fn live_stub_rejects_glob_in_state_dir() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("glob", "state_dir = '/home/*/fno'\n");
        let _env = EnvGuard::new(&fx.pins());
        let err = emit_paths_sh_live(&fx.root).unwrap_err();
        assert!(err.contains("glob"), "error: {err}");
    }

    #[test]
    fn live_stub_config_file_is_the_loaded_path() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("conffile", "");
        let _env = EnvGuard::new(&fx.pins());
        let stub = emit_paths_sh_live(&fx.root).unwrap();
        let line = line_with(&stub, "export CONFIG_FILE=");
        assert!(
            line.contains(&fx.config.display().to_string()),
            "CONFIG_FILE must name the loaded config: {line}"
        );
        assert!(!line.contains("$STATE_DIR"), "CONFIG_FILE: {line}");
    }

    #[test]
    fn live_stub_handoffs_dir_override() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let shared = fx_shared_dir("handovr");
        let fx = LiveFx::new(
            "handovr",
            &format!("paths.handoffs_dir = '{}'\n", shared.display()),
        );
        let _env = EnvGuard::new(&fx.pins());
        let stub = emit_paths_sh_live(&fx.root).unwrap();
        assert!(
            stub.contains(&shared.display().to_string()),
            "explicit handoffs_dir override must appear: {stub}"
        );
    }

    #[test]
    fn live_stub_handoffs_project_id_guard() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("handpid", "[project]\nid = 'my-pinned-id'\n");
        let _env = EnvGuard::new(&fx.pins());
        let stub = emit_paths_sh_live(&fx.root).unwrap();
        let line = line_with(&stub, "export HANDOFFS_DIR=");
        assert!(line.contains("my-pinned-id"), "HANDOFFS_DIR: {line}");
        assert!(!line.contains("basename"), "HANDOFFS_DIR: {line}");
        let bad = LiveFx::new("badpid", "[project]\nid = '$(touch /tmp/pwned)'\n");
        let _env2 = EnvGuard::new(&bad.pins());
        let err = emit_paths_sh_live(&bad.root).unwrap_err();
        assert!(err.contains("invalid characters"), "error: {err}");
    }

    #[test]
    fn live_stub_reads_a_pinned_yaml_config() {
        let _lock = test_env_lock().lock().unwrap_or_else(|e| e.into_inner());
        let fx = LiveFx::new("yamlpin", "");
        let yaml = fx.base.join("alt-settings.yaml");
        fs::write(
            &yaml,
            format!(
                "schema_version: 1\nconfig:\n  state_dir: {}/\n",
                fx.base.join("alt-state").display()
            ),
        )
        .unwrap();
        let mut pins = fx.pins();
        pins.push(("FNO_CONFIG", yaml.display().to_string()));
        let _env = EnvGuard::new(&pins);
        let stub = emit_paths_sh_live(&fx.root).unwrap();
        let line = line_with(&stub, "export STATE_DIR=");
        let expected = fx.base.join("alt-state").display().to_string();
        assert!(line.contains(&expected), "STATE_DIR: {line}");
        let conf = line_with(&stub, "export CONFIG_FILE=");
        assert!(
            conf.contains(&yaml.display().to_string()),
            "CONFIG_FILE: {conf}"
        );
    }

    fn fx_shared_dir(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("fno-paths-shared-{tag}"));
        fs::create_dir_all(&dir).unwrap();
        dir
    }
}
