//! `fno config paths emit-shell`: generate scripts/lib/paths.sh natively.
//!
//! One verb per PR (law d-450caaeb): this file serves `emit-shell` and
//! `handoff`; shell-stub and verify still answer in Python
//! (cli/src/fno/paths_cli.py) until their child nodes port. The defaults
//! emitter reproduces the
//! checked-in scripts/lib/paths.sh byte for byte; the include_bytes! parity
//! test fails the build the moment the two drift.

use std::path::{Path, PathBuf};
use std::process::Command;

use crate::finalize::resolve_handoffs_dir;
use crate::identity::canonical_handle;
use crate::lead_checkin::sanitize_scope_key;

/// The parity fixture: the checked-in stub this emitter must reproduce.
/// Test-only: the include path leaves the crate, which packaging forbids.
#[cfg(test)]
const FIXTURE: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../scripts/lib/paths.sh"
));

/// Quote a value for a bash assignment, the shape of Python `_bash_quote`:
/// a value carrying `$` takes double quotes so bash expands it at runtime
/// (literal `"` and `\` escaped first); anything else takes shlex single
/// quotes, unquoted when every char is shell-safe.
fn bash_quote(value: &str) -> String {
    if value.contains('$') {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        return format!("\"{escaped}\"");
    }
    if value.is_empty() {
        return "''".to_string();
    }
    let safe = value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "@%+=:,./-_".contains(c));
    if safe {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', "'\\''"))
}

/// Convert a tilde-prefixed raw value to a `$HOME`-relative template; an
/// absolute path passes through. Trailing slashes strip for consistency.
fn home_relative(raw: &str) -> String {
    let stripped = raw.trim_end_matches('/');
    if let Some(rest) = stripped.strip_prefix("~/") {
        return format!("$HOME/{rest}");
    }
    if stripped == "~" {
        return "$HOME".to_string();
    }
    stripped.to_string()
}

/// True for a bare relative path (no `~`, `/`-root, `$`, or `{` template
/// anywhere -- `plans/{project}` is NOT project-relative).
/// Test-only until the shell-stub port needs it live.
#[cfg(test)]
fn is_project_relative(raw: &str) -> bool {
    let stripped = raw.trim();
    if stripped.is_empty() {
        return false;
    }
    !(stripped.starts_with('/')
        || stripped.starts_with('~')
        || stripped.starts_with('$')
        || stripped.contains('{'))
}

/// True when the raw value carries a `{template}` variable (a `{{` escape
/// never counts, mirroring the Python regex's lookarounds).
/// Test-only until the shell-stub port needs it live.
#[cfg(test)]
fn has_template(raw: &str) -> bool {
    let bytes = raw.as_bytes();
    for i in 0..bytes.len() {
        if bytes[i] != b'{' || (i > 0 && bytes[i - 1] == b'{') {
            continue;
        }
        if let Some(close) = raw[i + 1..].find('}') {
            let close_idx = i + 1 + close;
            let next_dbl = close_idx + 1 < bytes.len() && bytes[close_idx + 1] == b'}';
            let inner = &raw[i + 1..close_idx];
            if !next_dbl && !inner.is_empty() && !inner.contains('{') && !inner.contains('}') {
                return true;
            }
        }
    }
    false
}

fn header_lines() -> Vec<String> {
    let header = r#"#!/usr/bin/env bash
# AUTO-GENERATED by `fno config paths emit-shell`. Do not hand-edit.
# Regenerate after any change to settings.yaml or the schema:
#   fno config paths emit-shell --output scripts/lib/paths.sh
#
# This stub is config-BLIND by design: it is emitted with use_defaults=True so
# regeneration is byte-stable across machines and the checked-in hash verifies.
# It does NOT honor a project's settings.yaml. A bash caller that needs the
# current config's resolved paths (vault-aware handoffs dir, overridden
# state_dir, etc.) must use the config-aware door instead:
#   source "$(fno config paths shell-stub)"
# which regenerates a temp stub from the live settings on every call.

# Self-set REPO_ROOT if unset so this file is safe to source under set -u.
# Callers may still pre-set REPO_ROOT before sourcing to pin the value.
REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
HOME="${HOME:-$(getent passwd "$(id -un)" 2>/dev/null | cut -d: -f6 || echo ~)}"
"#;
    header.lines().map(String::from).collect()
}

/// Emit the config-blind stub from schema defaults only (`use_defaults=True`):
/// `$HOME` and `$REPO_ROOT` stay literal so the bytes are machine-stable and
/// the checked-in hash verifies. Byte-for-byte port of the defaults path of
/// Python `emit_paths_sh`; the include_bytes! parity test pins it.
pub fn emit_paths_sh_defaults() -> String {
    let mut lines = header_lines();
    lines.push(String::new());
    lines.push(format!(
        "export STATE_DIR={}",
        bash_quote(&home_relative("~/.fno/"))
    ));
    for (name, sub) in [
        ("LEDGER_JSON_PATH", "ledger.json"),
        ("BRIEFS_DIR", "briefs"),
        ("FLEET_DIR", "fleet"),
        ("POSTMORTEMS_DIR", "postmortems"),
        ("WORKTREES_BASE", "worktrees"),
        ("MEMORY_DIR", "memory"),
        ("HOOK_LOGS_DIR", "hook-logs"),
        ("LATCHES_DIR", "latches"),
    ] {
        let v = bash_quote(&format!("$STATE_DIR/{sub}"));
        lines.push(format!("export {name}={v}"));
    }
    lines.push(format!(
        "export PLANS_DIR={}",
        bash_quote("$REPO_ROOT/.fno/plans")
    ));
    lines.push(format!(
        "export INBOX_DIR={}",
        bash_quote("$REPO_ROOT/.fno/inbox")
    ));
    // Defaults mode: no handoffs override, obsidian off, project.id unset --
    // the literal fallback line keeps the stub machine-stable; the basename
    // resolves at source-time from the consumer's repo.
    lines
        .push("export HANDOFFS_DIR=\"$STATE_DIR/handoffs/$(basename \"$REPO_ROOT\")\"".to_string());
    lines.push(format!(
        "export CONFIG_FILE={}",
        bash_quote("$STATE_DIR/config.toml")
    ));
    lines.push(String::new());
    lines.push("paths_plan_file() {".to_string());
    lines.push("  local name=\"$1\"".to_string());
    lines.push("  echo \"${PLANS_DIR}/${name}\"".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push("paths_inbox_thread() {".to_string());
    lines.push("  local thread=\"$1\"".to_string());
    lines.push("  echo \"${INBOX_DIR}/${thread}\"".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.push("# Mirrors fno.paths.project_log(): <repo>/.fno/<name>, anchored to".to_string());
    lines
        .push("# $REPO_ROOT (never CWD). Hooks route ad-hoc .fno/ writes through this".to_string());
    lines.push("# instead of hand-building \".fno/\" + name strings.".to_string());
    lines.push("paths_project_log() {".to_string());
    lines.push("  local name=\"$1\"".to_string());
    lines.push("  echo \"${REPO_ROOT}/.fno/${name}\"".to_string());
    lines.push("}".to_string());
    lines.push(String::new());
    lines.join("\n")
}

/// The repo root, Python `resolve_repo_root` semantics: `FNO_REPO_ROOT` env
/// first, then `git rev-parse --show-toplevel`. None when git fails (the
/// caller refuses rather than write to a guessed root).
fn repo_root() -> Option<PathBuf> {
    if let Some(p) = std::env::var_os("FNO_REPO_ROOT") {
        return Some(PathBuf::from(p));
    }
    let out = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if s.is_empty() {
        None
    } else {
        Some(PathBuf::from(s))
    }
}

/// `emit-shell [--output P]`: write the stub atomically (temp sibling +
/// rename, the shape fno.state.io.atomic_write uses) and print
/// `wrote N bytes to P`. Default output is `<repo>/scripts/lib/paths.sh`.
fn run_emit_shell(args: &[String]) -> i32 {
    let mut output: Option<PathBuf> = None;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--output" => match it.next() {
                Some(v) => output = Some(PathBuf::from(v)),
                None => {
                    eprintln!("fno config paths emit-shell: --output needs a path");
                    return 2;
                }
            },
            "--help" | "-h" => {
                println!("usage: fno config paths emit-shell [--output P]");
                return 0;
            }
            other => {
                eprintln!("fno config paths emit-shell: unknown argument {other:?}");
                return 2;
            }
        }
    }
    let out = match output {
        Some(p) => p,
        None => match repo_root() {
            Some(root) => root.join("scripts/lib/paths.sh"),
            None => {
                eprintln!("fno config paths emit-shell: no repo root; pass --output");
                return 1;
            }
        },
    };
    write_stub(&out)
}

/// Atomic write: temp sibling + rename (fno.state.io.atomic_write shape).
fn write_stub(out: &std::path::Path) -> i32 {
    let content = emit_paths_sh_defaults();
    if let Some(parent) = out.parent() {
        if let Err(e) = std::fs::create_dir_all(parent) {
            eprintln!(
                "fno config paths emit-shell: cannot create {}: {e}",
                parent.display()
            );
            return 1;
        }
    }
    let tmp = out.with_extension(format!("sh.tmp.{}", std::process::id()));
    if let Err(e) = std::fs::write(&tmp, &content) {
        eprintln!(
            "fno config paths emit-shell: cannot write {}: {e}",
            tmp.display()
        );
        return 1;
    }
    if let Err(e) = std::fs::rename(&tmp, out) {
        eprintln!("fno config paths emit-shell: cannot rename into place: {e}");
        let _ = std::fs::remove_file(&tmp);
        return 1;
    }
    println!("wrote {} bytes to {}", content.len(), out.display());
    0
}

/// Today's local date as YYYYMMDD, the Python `datetime.now().strftime`
/// filename prefix.
fn local_date() -> String {
    chrono::Local::now().format("%Y%m%d").to_string()
}

/// `handoff [--session-id S | --slug S | --scope S] [--name-only]`: print the
/// save path for a canon handoff doc (Python `paths_cli.handoff` parity). The
/// filename key is the session's canonical handle (first-8) unless --slug
/// overrides. --scope keys the doc on the crown instead -- a crown outlives
/// its sessions -- and returns the newest existing doc for that scope, so a
/// successor session resolves its predecessor's doc; today's dated name when
/// none exists yet. Every argv refusal exits 2, the typer BadParameter code.
fn handoff_out(args: &[String], cwd: &Path, home: Option<&Path>) -> Result<String, String> {
    let mut session_id: Option<String> = None;
    let mut slug: Option<String> = None;
    let mut scope: Option<String> = None;
    let mut name_only = false;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--session-id" => match it.next() {
                Some(v) => session_id = Some(v.clone()),
                None => return Err("--session-id needs a value".into()),
            },
            "--slug" => match it.next() {
                Some(v) => slug = Some(v.clone()),
                None => return Err("--slug needs a value".into()),
            },
            "--scope" => match it.next() {
                Some(v) => scope = Some(v.clone()),
                None => return Err("--scope needs a value".into()),
            },
            "--name-only" => name_only = true,
            "--help" | "-h" => {
                return Ok(
                    "usage: fno config paths handoff [--session-id S | --slug S | --scope S] [--name-only]"
                        .into(),
                )
            }
            other => return Err(format!("unknown argument {other:?}")),
        }
    }
    let directory = resolve_handoffs_dir(None, None, cwd, home);
    if let Some(scope) = scope {
        if session_id.is_some() || slug.is_some() {
            return Err("--scope cannot be combined with --session-id/--slug".into());
        }
        let key = format!("crown-{}", sanitize_scope_key(&scope));
        if key == "crown-" {
            return Err("a crown scope is required (--scope)".into());
        }
        let suffix = format!("-{key}.md");
        let mut best: Option<(std::time::SystemTime, String)> = None;
        if let Ok(rd) = std::fs::read_dir(&directory) {
            for entry in rd.flatten() {
                let name = entry.file_name();
                let Some(name) = name.to_str() else {
                    continue;
                };
                if !name.ends_with(&suffix) || !entry.path().is_file() {
                    continue;
                }
                // A concurrent refresh can unlink between read_dir and stat;
                // a vanished candidate sorts oldest and the writer recreates
                // the file anyway (Python `_mtime` parity).
                let mtime = entry
                    .metadata()
                    .and_then(|m| m.modified())
                    .unwrap_or(std::time::UNIX_EPOCH);
                if best.as_ref().map_or(true, |(t, _)| mtime > *t) {
                    best = Some((mtime, name.to_string()));
                }
            }
        }
        let filename = best
            .map(|(_, n)| n)
            .unwrap_or_else(|| format!("{}-{key}.md", local_date()));
        return Ok(render_handoff(&directory, &filename, name_only));
    }
    let Some(session_id) = session_id else {
        return Err("a session id is required (--session-id), or a crown scope (--scope)".into());
    };
    let key = slug.unwrap_or_else(|| canonical_handle(session_id.trim()));
    let filename = format!("{}-{key}.md", local_date());
    Ok(render_handoff(&directory, &filename, name_only))
}

/// The printed answer: just the filename under --name-only, else the full path.
fn render_handoff(directory: &Path, filename: &str, name_only: bool) -> String {
    if name_only {
        filename.to_string()
    } else {
        directory.join(filename).display().to_string()
    }
}

fn run_handoff(args: &[String], cwd: &Path, home: Option<&Path>) -> i32 {
    match handoff_out(args, cwd, home) {
        Ok(line) => {
            println!("{line}");
            0
        }
        Err(msg) => {
            eprintln!("fno config paths handoff: {msg}");
            2
        }
    }
}

/// Worker lane entry for `--paths-exec <verb> [args...]`.
pub fn run(args: &[String]) -> i32 {
    match args.first().map(String::as_str) {
        Some("emit-shell") => run_emit_shell(&args[1..]),
        Some("handoff") => {
            let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
            let home = std::env::var_os("HOME").map(PathBuf::from);
            run_handoff(&args[1..], &cwd, home.as_deref())
        }
        _ => {
            eprintln!("usage: fno-agents-worker --paths-exec emit-shell|handoff [args...]");
            2
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_defaults_matches_checked_in_fixture() {
        assert_eq!(emit_paths_sh_defaults(), String::from_utf8_lossy(FIXTURE));
    }

    #[test]
    fn helpers_quote_and_relative() {
        assert_eq!(bash_quote("$HOME/.fno"), "\"$HOME/.fno\"");
        assert_eq!(bash_quote("plain"), "plain");
        assert_eq!(home_relative("~/.fno/"), "$HOME/.fno");
        assert_eq!(home_relative("/abs"), "/abs");
        assert!(is_project_relative(".fno/plans"));
        assert!(!is_project_relative("plans/{project}"));
        assert!(has_template("a/{vault}/b"));
        assert!(!has_template("a/{{vault}}/b"));
    }

    #[test]
    fn run_emit_shell_writes_output_file() {
        let dir = std::env::temp_dir().join(format!("fno-paths-cli-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let out = dir.join("out.sh");
        let code = run(&[
            "emit-shell".to_string(),
            "--output".to_string(),
            out.to_string_lossy().into_owned(),
        ]);
        assert_eq!(code, 0);
        let written = std::fs::read(&out).unwrap();
        assert_eq!(written, FIXTURE.to_vec());
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn run_refuses_unknown_verb() {
        assert_eq!(run(&["bogus".to_string()]), 2);
    }

    // ── handoff ─────────────────────────────────────────────────────────────

    /// A uuid whose first-8 handle is unambiguous and not equal to its last-8.
    const SID: &str = "c35abbca-bd2d-4407-8365-cf468baa7eea";

    /// An isolated cwd/home pair; with no settings in either, the handoffs
    /// dir resolves to `<home>/.fno/handoffs/<cwd-basename>` (the resolution
    /// itself is pinned by finalize.rs's resolve_handoffs_dir tests).
    fn handoff_fixture(tag: &str) -> (PathBuf, PathBuf) {
        let dir = std::env::temp_dir().join(format!("fno-paths-ho-{tag}-{}", std::process::id()));
        let cwd = dir.join("repo");
        let home = dir.join("home");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&cwd).unwrap();
        std::fs::create_dir_all(&home).unwrap();
        (cwd, home)
    }

    fn handoff_dir(cwd: &Path, home: &Path) -> PathBuf {
        resolve_handoffs_dir(None, None, cwd, Some(home))
    }

    fn stamp_mtime(p: &Path, secs: u64) {
        std::fs::File::options()
            .write(true)
            .open(p)
            .unwrap()
            .set_modified(std::time::UNIX_EPOCH + std::time::Duration::from_secs(secs))
            .unwrap();
    }

    #[test]
    fn handoff_name_only_uses_canonical_handle_first_eight() {
        let (cwd, home) = handoff_fixture("first8");
        let out = handoff_out(
            &["--session-id".into(), SID.into(), "--name-only".into()],
            &cwd,
            Some(&home),
        )
        .unwrap();
        // Guards the both-ends truncation hazard: the key must be the head
        // (c35abbca), never the tail (8baa7eea).
        let (date, rest) = out.split_once('-').unwrap();
        assert!(
            date.len() == 8 && date.chars().all(|c| c.is_ascii_digit()),
            "{out}"
        );
        assert_eq!(rest, "c35abbca.md");
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_full_path_joins_the_handoffs_dir() {
        let (cwd, home) = handoff_fixture("fullpath");
        let dir = handoff_dir(&cwd, &home);
        let full = handoff_out(&["--session-id".into(), SID.into()], &cwd, Some(&home)).unwrap();
        let name = handoff_out(
            &["--session-id".into(), SID.into(), "--name-only".into()],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert_eq!(Path::new(&full).parent().unwrap(), dir);
        assert_eq!(
            Path::new(&full).file_name().unwrap().to_str().unwrap(),
            name
        );
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_slug_overrides_handle_key() {
        let (cwd, home) = handoff_fixture("slug");
        let out = handoff_out(
            &[
                "--session-id".into(),
                SID.into(),
                "--slug".into(),
                "my-feature".into(),
                "--name-only".into(),
            ],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert!(out.ends_with("-my-feature.md"), "{out}");
        assert!(!out.contains("c35abbca"), "{out}");
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_argv_validation_refusals() {
        let (cwd, home) = handoff_fixture("refuse");
        // The hidden --session alias was removed to pay the flag-surface
        // ratchet (operator ruling 2026-09-12); --session-id is the one
        // spelling.
        assert!(handoff_out(
            &["--session".into(), SID.into(), "--name-only".into()],
            &cwd,
            Some(&home)
        )
        .is_err());
        let scope = ["--scope".to_string(), "x-aaaa1111".into()];
        let mut v = scope.to_vec();
        v.extend(["--session-id".into(), SID.into()]);
        assert!(handoff_out(&v, &cwd, Some(&home)).is_err());
        let mut v = scope.to_vec();
        v.extend(["--slug".into(), "s".into()]);
        assert!(handoff_out(&v, &cwd, Some(&home)).is_err());
        assert!(handoff_out(&[], &cwd, Some(&home)).is_err());
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_mints_a_dated_crown_keyed_name() {
        let (cwd, home) = handoff_fixture("scope-mint");
        let scope = "x-1234abcd";
        let out = handoff_out(
            &["--scope".into(), scope.into(), "--name-only".into()],
            &cwd,
            Some(&home),
        )
        .unwrap();
        let (date, rest) = out.split_once('-').unwrap();
        assert!(
            date.len() == 8 && date.chars().all(|c| c.is_ascii_digit()),
            "{out}"
        );
        assert_eq!(rest, format!("crown-{scope}.md"));
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_returns_the_newest_existing_doc() {
        let (cwd, home) = handoff_fixture("scope-newest");
        let scope = "x-2222bbbb";
        let dir = handoff_dir(&cwd, &home);
        std::fs::create_dir_all(&dir).unwrap();
        let old = dir.join(format!("20260901-crown-{scope}.md"));
        let new = dir.join(format!("20260909-crown-{scope}.md"));
        std::fs::write(&old, "predecessor").unwrap();
        std::fs::write(&new, "successor").unwrap();
        stamp_mtime(&old, 1_000_000);
        stamp_mtime(&new, 2_000_000);
        let full = handoff_out(&["--scope".into(), scope.into()], &cwd, Some(&home)).unwrap();
        assert_eq!(Path::new(&full), new);
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_newest_ignores_other_scopes_and_session_keys() {
        let (cwd, home) = handoff_fixture("scope-filter");
        let scope = "x-3333cccc";
        let dir = handoff_dir(&cwd, &home);
        std::fs::create_dir_all(&dir).unwrap();
        let other = dir.join("20260909-crown-x-9999zzzz.md");
        let session_key = dir.join("20260909-c35abbca.md");
        let mine = dir.join(format!("20260901-crown-{scope}.md"));
        for p in [&other, &session_key, &mine] {
            std::fs::write(p, "x").unwrap();
        }
        stamp_mtime(&other, 9_999_999);
        stamp_mtime(&session_key, 9_999_999);
        stamp_mtime(&mine, 1_000_000);
        let full = handoff_out(&["--scope".into(), scope.into()], &cwd, Some(&home)).unwrap();
        assert_eq!(Path::new(&full), mine);
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }

    #[test]
    fn handoff_scope_sanitizes_runs_into_one_dash() {
        // A portfolio crown stores its scope comma-joined; commas and spaces
        // are not filename-safe, so each unsafe RUN collapses into one key
        // separator (Python re.sub(r"[^A-Za-z0-9._-]+", "-") parity).
        let (cwd, home) = handoff_fixture("scope-sanitize");
        let out = handoff_out(
            &[
                "--scope".into(),
                "x-aaaa1111, x-bbbb2222".into(),
                "--name-only".into(),
            ],
            &cwd,
            Some(&home),
        )
        .unwrap();
        assert!(out.ends_with(".md") && out.contains("-crown-x-"), "{out}");
        assert!(!out.contains(',') && !out.contains(' '), "{out}");
        assert!(!out.contains("--"), "{out}");
        let _ = std::fs::remove_dir_all(cwd.parent().unwrap());
    }
}
