#!/usr/bin/env python3
"""Generate the OTEL table/column reference from the canonical SQL."""
import argparse
import sqlite3
from pathlib import Path


def render(root):
    conn = sqlite3.connect(":memory:")
    conn.executescript((root / "crates/fno-agents/src/otel_schema.sql").read_text())
    lines = ["<!-- Generated by scripts/docs/generate-otel-schema.py. Do not edit. -->", "# Local telemetry schema", "", "The canonical schema is `crates/fno-agents/src/otel_schema.sql`. Regenerate this reference with `python3 scripts/docs/generate-otel-schema.py`. Every log event is retained after content redaction. Unknown event names and future attribute/resource fields remain in the JSON columns. Metrics and traces are not collected.", ""]
    tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").fetchall()
    for (table,) in tables:
        lines += [f"## `{table}`", "", "| Column | SQLite type | Null allowed | Primary key |", "|---|---|---|---|"]
        for _, name, kind, required, _, primary in conn.execute(f'PRAGMA table_info("{table}")'):
            lines.append(f"| `{name}` | `{kind}` | {'no' if required else 'yes'} | {'yes' if primary else 'no'} |")
        lines.append("")
    lines += ["## Data policy", "", "`api_requests` is the typed cost projection. `otel_events` retains event names, timestamps, session/prompt IDs, attribute JSON and resource JSON. Retries are deduplicated. Raw retention and cost projection commit in one transaction.", "", "Prompt and response text, tool input, command text, API bodies, hook definitions and managed settings content are redacted before persistence. Safe attribution names inside tool parameters remain. The receiver never enables prompt or tool-content export. With `OTEL_LOG_TOOL_DETAILS=1`, the exporter can emit tool arguments. The receiver redacts these arguments before persistence.", ""]
    conn.close()
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    output = root / "docs/reference/otel-schema.md"
    text = render(root)
    if args.check:
        if not output.is_file() or output.read_text() != text:
            parser.exit(1, "OTEL schema reference is stale. Run python3 scripts/docs/generate-otel-schema.py.\n")
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(text)


if __name__ == "__main__":
    main()
