# GENERATED by crates/fno-agents/codegen/check_supersession.rs.
# Do not edit. Change the TOML contract and rebuild.

from __future__ import annotations

from typing import Sequence


def _text(row: dict, field: str) -> str:
    value = row.get(field)
    return value if isinstance(value, str) else ""


def _identity(row: dict) -> tuple[str, str, str] | None:
    name = _text(row, "name")
    if name:
        return ("check", name, _text(row, "workflow"))
    context = _text(row, "context")
    if context:
        return ("status", context, "")
    return None


def _timestamp(row: dict) -> str:
    for field in ("startedAt", "createdAt"):
        value = _text(row, field)
        if value:
            return value
    return ""


def _is_failure(row: dict) -> bool:
    status = _text(row, "status").upper()
    if status and status != "COMPLETED":
        return False
    if _text(row, "bucket").lower() in ("fail", "cancel"):
        return True
    conclusion = _text(row, "conclusion") or _text(row, "state")
    return conclusion.upper() in ("FAILURE", "TIMED_OUT", "CANCELLED", "ACTION_REQUIRED", "STARTUP_FAILURE", "STALE", "ERROR")


def latest_per_name(rollup: Sequence[dict]) -> list[dict]:
    latest: dict[tuple[str, str, str], int] = {}
    slots: list[tuple[tuple[str, str, str] | None, dict]] = []
    for row in rollup:
        key = _identity(row)
        if key is None:
            slots.append((None, row))
            continue
        position = latest.get(key)
        if position is None:
            latest[key] = len(slots)
            slots.append((key, row))
            continue
        existing = slots[position][1]
        incoming_time = _timestamp(row)
        existing_time = _timestamp(existing)
        replaces = incoming_time > existing_time or (
            incoming_time == existing_time
            and _is_failure(row)
            and not _is_failure(existing)
        )
        if replaces:
            slots[position] = (key, row)
    return [row for _, row in slots]
