#!/usr/bin/env bash
# tests/ci/test_check_events_limits_fresh.sh
#
# Test harness for scripts/ci/check-events-limits-fresh.sh.
#
# Scenarios:
#   T01 - generated file matches the schema projection -> PASS, rc=0
#   T02 - generated file hand-edited away from schema  -> FAIL, rc=1, names both paths
#   T03 - missing generated file                       -> misuse, rc=2
#   T04 - missing schema                               -> misuse, rc=2
#   T05 - --write regenerates a hand-edited file       -> PASS, rc=0
#
# Exit codes: 0 pass, 1 fail

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT_REAL="$(cd "${SCRIPT_DIR}/../.." && pwd)"
GATE="${REPO_ROOT_REAL}/scripts/ci/check-events-limits-fresh.sh"

fail() { printf '[events-limits-fresh-test] FAIL: %s\n' "$*" >&2; exit 1; }
pass() { printf '[events-limits-fresh-test] PASS: %s\n' "$*"; }

[[ -f "${GATE}" ]] || fail "gate script not found at ${GATE}"
bash -n "${GATE}" || fail "gate script failed bash -n"

python3 -c "import yaml" 2>/dev/null || fail "PyYAML unavailable; the gate cannot project schema.yaml"

TMP=$(mktemp -d -t events-limits-test-XXXXXX)
trap 'rm -rf "$TMP"' EXIT

REPO="$TMP/repo"
SCHEMA_DIR="$REPO/cli/src/fno/events"
GENERATED_DIR="$REPO/crates/fno-agents/src"
SCHEMA="$SCHEMA_DIR/schema.yaml"
GENERATED="$GENERATED_DIR/events_limits.toml"

mkdir -p "$SCHEMA_DIR" "$GENERATED_DIR"
(
  cd "$REPO"
  git init -q
  git config user.email "test@example.invalid"
  git config user.name "gate selftest"
)

write_schema() {
  cat > "$SCHEMA" <<YAMLEOF
limits:
  max_data_bytes: $1
  data_size_encoding: compact-json-ascii-v1
YAMLEOF
}

write_generated() {
  cat > "$GENERATED" <<TOMLEOF
# GENERATED by crates/fno-agents/build.rs from cli/src/fno/events/schema.yaml.
# Do not edit. Change the limits block in schema.yaml and rebuild.
max_data_bytes = $1
data_size_encoding = "compact-json-ascii-v1"
TOMLEOF
}

commit_all() {
  (cd "$REPO" && git add -A && git commit -q -m "$1")
}

# T01: the generated file matches the projection.
write_schema 65536
write_generated 65536
commit_all "fresh"

out="$(cd "$REPO" && bash "${GATE}" 2>&1)" && rc=0 || rc=$?
[[ "$rc" -eq 0 ]] || fail "T01: expected rc=0, got $rc: $out"
echo "$out" | grep -q "events limits table fresh" || fail "T01: missing fresh message: $out"
echo "$out" | grep -q "committed" || fail "T01: expected a committed-bytes comparison: $out"
pass "T01 matching generated file exits 0"

# T02: a hand edit of the generated file fires the tripwire.
write_generated 99999
commit_all "hand edit"
out="$(cd "$REPO" && bash "${GATE}" 2>&1)" && rc=0 || rc=$?
[[ "$rc" -eq 1 ]] || fail "T02: expected rc=1, got $rc: $out"
echo "$out" | grep -q "cli/src/fno/events/schema.yaml" || fail "T02: schema path not named: $out"
echo "$out" | grep -q "crates/fno-agents/src/events_limits.toml" || fail "T02: generated path not named: $out"
pass "T02 hand-edited generated file fails (rc=1), naming both paths"

# T05 (run here, while the file is still divergent): --write regenerates it.
out="$(cd "$REPO" && bash "${GATE}" --write 2>&1)" && rc=0 || rc=$?
[[ "$rc" -eq 0 ]] || fail "T05: expected rc=0 from --write, got $rc: $out"
grep -q "max_data_bytes = 65536" "$GENERATED" || fail "T05: --write did not regenerate: $(cat "$GENERATED")"
out="$(cd "$REPO" && bash "${GATE}" --worktree 2>&1)" && rc=0 || rc=$?
[[ "$rc" -eq 0 ]] || fail "T05b: expected --worktree rc=0 after --write, got $rc: $out"
pass "T05 --write regenerates the file from schema.yaml"

# T03: missing generated file is misuse.
commit_all "regenerated"
rm -f "$GENERATED"
out="$(cd "$REPO" && bash "${GATE}" 2>&1)" && rc=0 || rc=$?
[[ "$rc" -eq 2 ]] || fail "T03: expected rc=2, got $rc: $out"
echo "$out" | grep -q "missing" || fail "T03: missing error message expected: $out"
pass "T03 missing generated file exits 2"

# T04: missing schema is misuse.
write_generated 65536
rm -f "$SCHEMA"
out="$(cd "$REPO" && bash "${GATE}" 2>&1)" && rc=0 || rc=$?
[[ "$rc" -eq 2 ]] || fail "T04: expected rc=2, got $rc: $out"
echo "$out" | grep -q "missing" || fail "T04: missing error message expected: $out"
pass "T04 missing schema exits 2"

pass "all scenarios passed"
