#!/usr/bin/env bash
# rename-to-fno.sh -- pre-launch rename: abilities -> footnote (brand) / abi -> fno (handle).
#
# Design: internal/abilities/design/2026-06-11-rename-abilities-to-footnote-fno.md
#
# This is the boundary-safe, anchored, IDEMPOTENT sweep that flips the whole
# technical surface from the `abi`/`abilities` handle to `fno`. It NEVER does a
# global `s/abi/fno/g` (that corrupts `capabilities`, prose `abilities`, and
# substring-bearing paths). Each pass is an enumerated, anchored pattern run
# over only the tracked text files that contain it.
#
# Because the cutover must run LAST (after #476 and any other open branch
# lands), this is a re-runnable script, not a hand-applied diff: run it again on
# the post-merge tree and it converges to the same result (every pass's output
# no longer matches its input pattern).
#
# It does NOT touch the live ~/.abilities state dir. The one-time directory
# migration (mv ~/.abilities -> ~/.fno) is a SEPARATE operator step; see
# scripts/rename/migrate-state-dir.sh.
#
# Usage:
#   scripts/rename/rename-to-fno.sh            # apply in-place
#   scripts/rename/rename-to-fno.sh --dry-run  # report what each pass would change
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"

DRY_RUN=0
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

# Exclude pathspecs: lock files (regenerated by the toolchain), this rename
# tree (it contains every pattern by definition), and git internals.
EXCLUDES=(
  ':!*.lock'
  ':!**/*.lock'
  ':!scripts/rename/**'
  # The compat shims + their tests intentionally reference the OLD names (they
  # read legacy env vars for the one-release fallback); never sweep them.
  ':!cli/src/fno/_compat_env.py'
  ':!cli/tests/unit/test_compat_env.py'
  ':!crates/fno-agents/src/compat_env.rs'
  # .gitignore needs BOTH .fno/ (new) and .abilities/ (legacy, migration window).
  # The general .abilities->.fno sweep would clobber the legacy block, so it is
  # excluded here and normalized by a dedicated idempotent step in Phase 9.
  ':!.gitignore'
  # The loc-ratchet trajectory is an APPEND-ONLY historical ledger; its past
  # entries' reasons record the old `abi-agents`/`abilities.` names verbatim and
  # must stay byte-identical (the gate enforces append-only). Never sweep it.
  ':!scripts/ci/loc-ratchet-trajectory.yaml'
)

# sweep PATTERN REPL [extra-pathspec ...]
# Replaces PATTERN (PCRE) with the literal string REPL across every tracked text
# file that matches. git grep -P gives PCRE (lookbehind/lookahead, \b); -I skips
# binaries; -l lists files; -z null-delimits for safe xargs. Idempotent: REPL
# never re-matches its own PATTERN. Portable to bash 3.2 (no mapfile/arrays).
# REPL is a literal string, NOT a perl replacement expression -- passes that need
# to keep surrounding context use lookbehind/lookahead in PATTERN instead of
# capture groups, so there are no backreferences to interpolate.
sweep() {
  local pattern="$1" repl="$2"; shift 2
  local listfile; listfile="$(mktemp)"
  git grep -lIzP -e "$pattern" -- "${EXCLUDES[@]}" "$@" > "$listfile" 2>/dev/null || true
  local count; count=$(tr -cd '\0' < "$listfile" | wc -c | tr -d ' ')
  if [ "$count" -eq 0 ]; then
    printf '  (no matches) %s\n' "$pattern"
    rm -f "$listfile"
    return 0
  fi
  printf '  %-4d files: %s\n' "$count" "$pattern"
  if [ "$DRY_RUN" -eq 1 ]; then
    rm -f "$listfile"
    return 0
  fi
  # perl -CSD: treat I/O as UTF-8 so multibyte content is preserved. PATTERN and
  # REPL come via env so shell quoting never reaches perl source. $r is a plain
  # literal (no $, @, or backslash in any replacement) interpolated as a variable
  # -- so its runtime `/` never threatens the parse-time s/// delimiter, and no
  # quotemeta is needed (quotemeta on the REPLACEMENT half wrongly inserts
  # backslashes before non-word chars).
  PAT="$pattern" REPL="$repl" xargs -0 perl -CSD -i -pe '
    BEGIN { $p = $ENV{PAT}; $r = $ENV{REPL}; }
    s/$p/$r/g;
  ' < "$listfile"
  rm -f "$listfile"
}

# move SRC DST -- git mv a tracked directory if it still exists at SRC.
move() {
  local src="$1" dst="$2"
  if [[ -e "$src" && ! -e "$dst" ]]; then
    printf '  git mv %s -> %s\n' "$src" "$dst"
    [[ $DRY_RUN -eq 1 ]] && return 0
    mkdir -p "$(dirname "$dst")"
    git mv "$src" "$dst"
  else
    printf '  (skip move, already done or absent) %s\n' "$src"
  fi
}

echo "== Phase 1: directory moves =="
move cli/src/abilities cli/src/fno
move crates/abi-agents crates/fno-agents

echo "== Phase 1b: file renames (content already points to the new names) =="
# Doc files whose names embed `abi-agents` -- the content sweep (Phase 2)
# rewrote every cross-link to fno-agents-*.md, so the files must follow.
while IFS= read -r f; do
  [[ -n "$f" ]] && move "$f" "${f/abi-agents-/fno-agents-}"
done < <(git ls-files 'docs/architecture/abi-agents-*.md' 'docs/guides/abi-agents-*.md')
# launchd template/plist files: code refs were swept com.abilities.* -> com.fno.*
move scripts/templates/com.abilities.watch.plist scripts/templates/com.fno.watch.plist
move scripts/post-merge/com.abilities.postmerge.plist.template scripts/post-merge/com.fno.postmerge.plist.template
# the one tracked state-dir example -- .gitignore now negates .fno/settings.yaml.example
move .abilities/settings.yaml.example .fno/settings.yaml.example
# v2 bundle shim literally named `abi` (its test refs were swept to scripts/fno).
move v2/skills/target/scripts/abi v2/skills/target/scripts/fno
# Obsolete: test_abi_rename.sh verifies a deprecated `abilities` compat-alias
# that EMITS a deprecation warning - the exact two-command+alias model this
# rename eliminates (single command `fno`, no alias). Remove it.
if [[ -e cli/tests/smoke/test_abi_rename.sh ]]; then
  printf '  git rm cli/tests/smoke/test_abi_rename.sh (obsolete alias test)\n'
  [[ $DRY_RUN -eq 0 ]] && git rm -qf cli/tests/smoke/test_abi_rename.sh
fi

echo "== Phase 2: Rust crate / lib / binary names =="
# abi-agents (crate, binaries abi-agents-daemon/-worker, path refs, cache keys)
sweep 'abi-agents' 'fno-agents'
# abi_agents (the underscored lib name + `abi_agents::` paths in Rust + tests)
sweep 'abi_agents' 'fno_agents'

echo "== Phase 3: Python package path + imports =="
# Package source path (covers cli/src/abilities AND bare src/abilities in pyproject/hatch)
sweep 'src/abilities' 'src/fno'
# In-wheel package path used by the build hook + schema force-include
sweep 'abilities/events' 'fno/events'
# Imports are unambiguous wherever they appear (Python files AND doc code
# blocks), so they are not scoped. Module qualifiers stay Python-scoped because
# `abilities.` could be sentence-prose in docs.
sweep '\bfrom abilities\b' 'from fno'
sweep '\bimport abilities\b' 'import fno'
sweep '\babilities\.' 'fno.' '*.py'
# patch()/import_module() string refs to the package, scoped to Python.
# Lookaround (not capture groups) so the replacement stays a literal string.
sweep '(?<=["\x27])abilities(?=["\x27])' 'fno' '*.py'
# Phase 3b: bare `abilities` Python identifiers + command strings + heredoc test
# data -> fno. Phase 3 renamed module qualifiers (`abilities.x`) but left LOCAL
# VARIABLES named `abilities` half-renamed (defined `abilities`, used as `fno.`)
# -> NameError; and renamed quoted `"abilities"` call args while leaving matching
# unquoted heredoc `name: abilities` test data behind -> lookup misses. This
# renames the bare token too. The lookbehind/ahead EXCLUDE path context
# (`/abilities`, `.abilities`, `abilities/`) and attribute access (`x.abilities`)
# so vault doc-path refs (internal/abilities/...) stay intact. Benchmarks excluded.
sweep '(?<![/\w.])abilities(?![/\w])' 'fno' '*.py' ':!cli/benchmarks/**'
# Phase 3c: module qualifiers + relative code-path refs OUTSIDE *.py. Phase 3's
# qualifier pass was *.py-scoped, but `python -m abilities.events` (hooks, CI
# yaml, shell scripts), pyproject module lists, Rust mirror comments, and
# `("abilities/cli.py", ...)` test data live elsewhere and break at runtime.
# `abilities.` + lowercase and `abilities/` + lowercase are strong module/path
# signals; the vault (internal/abilities/, slash-preceded) is preserved by the
# dot requirement and by the `(?<![\w./])` lookbehind on the slash form.
# `.(?!ext)` excludes file-extension contexts (abilities.sh / abilities.md /
# abilities.json filenames) - those are not module qualifiers and must not move
# unless the file itself is renamed (e.g. the `session-start-using-abilities.sh`
# hook + `using-abilities` skill stay). The slash form excludes vault subdir
# leaves (backlog/plans/design/...) so `{vault}/abilities/backlog` stays while a
# real package path like `abilities/cli.py` still moves.
sweep '\babilities\.(?!(?:sh|py|md|json|ya?ml|txt|toml|rs|lock|jsonl|cfg|ini|template|example|bak)\b)(?=[a-z_])' 'fno.'
sweep '(?<![\w./])abilities/(?!(?:backlog|plans|design|specs|handoffs|reason|inbox)\b)(?=[a-z_])' 'fno/'

echo "== Phase 4: skill namespace =="
sweep '/abilities:' '/fno:'

echo "== Phase 5: environment variables =="
# ABILITIES_* -> FNO_*  and  ABI_* -> FNO_* (incl. ABI_AGENTS_* daemon vars).
# Old names get a one-release read-fallback via the startup shim (paths.py /
# Rust main), so an operator's exported ABI_*/ABILITIES_* still takes effect.
# `\bABI_` cannot match inside `ABILITIES_` (ABI is followed by L, not _).
sweep '\bABILITIES_' 'FNO_'
sweep '\bABI_' 'FNO_'

echo "== Phase 6: state directory =="
# Literal `.abilities` (state dir) -> `.fno`. Requires the leading dot, so
# `capabilities` (no dot) and `cli/src/...` (handled above) are untouched.
sweep '\.abilities\b' '.fno'

echo "== Phase 6b: Obsidian vault area -> fno =="
# The vault area is renamed to the handle `fno` (operator decision 2026-06-11:
# the actual vault folder internal/abilities/ becomes internal/fno/). This is the
# SINGLE-STRING vault forms the `/`-lookbehind in Phase 3/3b/3c left intact;
# split-component forms (`"internal" / "abilities"`) were already turned to `fno`
# by Phase 3's quoted-string pass (Phase 10 no longer reverts them). The
# repo-checkout dirs (`~/conductor/workspaces/abilities/`, `code/me/abilities`)
# are NOT the vault and stay -- only the `internal/` symlink and `{vault}` template
# roots, plus bare vault-subdir leaves, are renamed.
# NOTE: a fresh sweep mangles crates/fno-agents/src/finalize.rs's handoffs tests,
# which use a SYNTHETIC project literally named "abilities" substituted into
# `internal/{project}/handoffs` (collides with the vault-area `internal/abilities`
# pattern below). Those tests are hand-maintained to use a neutral project name
# ("demo"); re-apply that at cutover if re-running on a fresh tree (verify step).
sweep 'internal/abilities\b' 'internal/fno'
sweep '\{vault\}/abilities\b' '{vault}/fno'
sweep '(?<![\w./])abilities/(?=(?:backlog|plans|design|specs|handoffs|reason|inbox)\b)' 'fno/'

echo "== Phase 7: repo URL -> brand (footnote) =="
# Forward-looking identity surface: the launch repo is bllshttng/footnote.
sweep 'bllshttng/abilities' 'bllshttng/footnote'

echo "== Phase 8: bare command  abi -> fno =="
# Most dangerous pass. Replace `abi` ONLY when it is a standalone token:
# not preceded/followed by a word char or hyphen. This preserves:
#   - `abi-agents` (already renamed in Phase 2 anyway; guarded by trailing -)
#   - immutable node slugs ending in `-abi` (preceded by -)
#   - `abilities`/`capabilities` (followed by a letter)
# Excludes cli/benchmarks/**: there `abi` is a load-bearing METRIC name with an
# `abi=...` output-format contract a downstream parser reads, plus recorded
# result JSON. Benchmarks are internal dev tooling (not shipped, not in CI);
# their cosmetic abi->fno is a Tier-2 follow-up.
sweep '(?<![\w-])abi(?![\w-])' 'fno' ':!cli/benchmarks/**'

echo "== Phase 9: brand surfaces (footnote) + packaging identity =="
# Brand vs handle split. The plugin manifest `name` DRIVES the Claude Code skill
# namespace, so it must be the handle `fno` for `/fno:` (Phase 4) to resolve.
# The brand `footnote` lives on the marketplace name, README face, and repo URL
# (Phase 7). These are surgical, file-scoped, idempotent edits.
brand_edit() {  # file  perl-program
  local f="$1" prog="$2"
  [[ -f "$f" ]] || { printf '  (absent) %s\n' "$f"; return 0; }
  printf '  brand %s\n' "$f"
  [[ $DRY_RUN -eq 1 ]] && return 0
  perl -CSD -0777 -i -pe "$prog" "$f"
}

# plugin.json: name -> fno (handle; drives /fno: namespace)
brand_edit .claude-plugin/plugin.json 's/"name":\s*"abilities"/"name": "fno"/'
# marketplace.json: top-level name -> footnote (brand); plugin entry name -> fno
brand_edit .claude-plugin/marketplace.json '
  s/^(  )"name": "abilities"/${1}"name": "footnote"/m;
  s/^(      )"name": "abilities"/${1}"name": "fno"/m;
'
# pyproject: distribution name -> fno; single console entry point fno -> fno.cli
brand_edit cli/pyproject.toml '
  s/^name = "abilities"$/name = "fno"/m;
  s/\[project\.scripts\]\n.*?\n\n/[project.scripts]\nfno = "fno.cli:app"\n\n/s;
'
# README brand face
brand_edit README.md 's/^# abilities$/# footnote/m'
# User-facing product strings in code use the BRAND (footnote), not the command
# handle (fno): the CLI top-level help blurb and the rendered Kanban board's HTML
# <title> + <h1>. (gemini review #504: brand vs handle on user-facing surfaces.)
brand_edit cli/src/fno/cli.py 's/help="CLI for the fno autonomous delivery pipeline"/help="CLI for the footnote autonomous delivery pipeline"/'
brand_edit cli/src/fno/graph/render_html.py '
  s{<title>fno backlog</title>}{<title>footnote backlog</title>};
  s{<h1>fno backlog</h1>}{<h1>footnote backlog</h1>};
'
# Post-rename there is exactly ONE command (`fno`): the old `abi` + `abilities`
# entry points collapsed into it, so the deprecated-alias warning is dead. Left
# alone, the sweep turns its `invoked_as == "abilities"` guard into `== "fno"`,
# which fires on EVERY invocation and leaks "fno: deprecated; use 'fno'" to
# stderr (breaks `fno --version` cleanliness + `--json` output). Neutralize it.
brand_edit cli/src/fno/cli.py '
  s{def _warn_deprecated_alias_if_needed\(\) -> None:\n.*?\n\n\ndef }{def _warn_deprecated_alias_if_needed() -> None:\n    # Exactly one command post-rename (`fno`); no deprecated alias to warn about.\n    return\n\n\ndef }s;
'
# .gitignore state-dir block: canonical form (new .fno/ + legacy .abilities/),
# idempotent regardless of input (fresh `.abilities/` or already-normalized).
# .gitignore is excluded from the general sweep, so this is the only writer.
brand_edit .gitignore '
  s{\# Runtime state \(planning/execution\)\n.*?\n!\*\*/\.(?:abilities|fno)/settings\.yaml\.example\n}{\# Runtime state (planning/execution)\n.fno/\n**/.fno/\n\# Legacy state dir (abilities -> fno rename): ignored through the migration window.\n.abilities/\n**/.abilities/\n\# But track the example config file - it is documentation, not runtime state\n!.fno/settings.yaml.example\n!**/.fno/settings.yaml.example\n}s;
  s{^\.abilities/feels/}{.fno/feels/}mg;
'

echo "== Phase 10: corrective reverts (sentinel + skill-name consistency) =="
# 1. test-temp sentinel: the marker is `fno-test-home-` (renamed); make the
#    `/`-preceded test strings (which Phase 3b's path-exclusion skipped) match.
sweep 'abilities-test-home' 'fno-test-home'
# 2. worktree name derived from the now-`fno` project_id: `abi-my-feature` was
#    `{project_id}-{name}` with project_id `abi` -> `fno`; the compound-preserve
#    pass kept the literal, so align it.
sweep 'abi-my-feature' 'fno-my-feature'
# 3. The `using-abilities` skill + its SessionStart hook file are NOT renamed
#    (skill dirs are out of scope), so any `using-fno` produced by a bare-token
#    pass must be restored. (Idempotent no-op on a fresh run.)
sweep 'using-fno' 'using-abilities'

echo "== Phase 11: brand prose (footnote) + skill-namespace residual (fno:) =="
# Skill namespace WITHOUT a leading slash (handle): `abilities:tdd`, `$abilities:do`,
# mermaid nodes, agent frontmatter `- abilities:think`. Phase 4 only caught the
# `/abilities:` form. Run BEFORE the brand pass so `abilities:tdd` -> `fno:tdd`,
# not `footnote:tdd`.
sweep '(?<![\w/-])abilities:(?=[a-z])' 'fno:'
# Functional `abilities` command / uv-workspace-selector refs the .md-scoped brand
# pass leaves in shell: `uv run abilities` (the removed second entry-point alias ->
# the `fno` console script), `--package abilities` (uv workspace package, now `fno`),
# `--project abilities` (backlog project filter). These are the HANDLE (fno), and
# they BREAK at runtime if missed - `uv ... --package abilities` errors "Package
# 'abilities' not found in workspace" (codex review #504). NOT brand.
sweep '\buv run abilities\b' 'uv run fno'
sweep '\-\-package abilities\b' '--package fno'
sweep '\-\-project abilities\b' '--project fno'
# postinstall checks `uv tool list | grep '^abilities '` but the installed tool
# is now `fno` (so the "already installed" skip never fires -> reinstalls every
# run). In this file every `abilities` is the package/tool handle -> fno.
sweep '\babilities\b' 'fno' '.claude-plugin/postinstall.sh'
# rust-ci step name (cosmetic; the step runs `uv sync`).
brand_edit .github/workflows/rust-ci.yml 's/Install abilities Python package/Install fno Python package/'
# Bare project/plugin name in PROSE -> brand `footnote`. SCOPED to documentation
# (*.md + NOTICE): renaming bare `abilities` in functional files (.py/.sh/.rs/
# yaml) would rewrite synthetic test-project fixtures and code strings, breaking
# internal consistency (a test project named `abilities` whose `$ROOT/abilities/`
# path the `/`-exclusion would skip -> half-renamed). Excludes: vault paths/URLs
# (`/abilities`), `capabilities` (`\w` before), `_abilities`, and the
# `using-abilities` skill. Still renames `non-abilities`, `abilities-ecosystem`.
sweep '(?<!using-)(?<![\w/])abilities(?![\w])' 'footnote' '*.md' 'NOTICE'

echo
echo "Mechanical sweep + brand surfaces complete."
echo "Tier-2 brand prose ('abilities' the English word in docs/README body) is"
echo "reviewed by hand; the residual-grep guard (scripts/rename/residual-check.sh)"
echo "enforces the structural patterns."
