"""Public immutable contracts for role discovery and bounded resolution."""

from fno.roles.models import (
    ApprovalFloor,
    AuthorityCeiling,
    CapabilityFact,
    ContextBundle,
    ContextBundleBounds,
    ContextKind,
    ContextReference,
    ContextSelector,
    DefinitionStatus,
    DeliveryPolicy,
    ManifestRoutingResolution,
    ResolvedRole,
    ResolvedSource,
    ReviewPolicy,
    RoleDefinitionSource,
    RoleLayer,
    RoleManifest,
    RoleResolution,
    RoleResolutionBlocked,
    RoleResolutionReason,
    RoutingHint,
    Sensitivity,
)
from fno.roles.registry import (
    DiscoveredRoleDefinition,
    DiscoveryInputError,
    RegistryError,
    RoleRegistry,
    discover_role_definitions,
    ordered_definitions,
)
from fno.roles.resolver import resolve_manifest_routing, resolve_role

__all__ = [
    "ApprovalFloor",
    "AuthorityCeiling",
    "CapabilityFact",
    "ContextBundle",
    "ContextBundleBounds",
    "ContextKind",
    "ContextReference",
    "ContextSelector",
    "DefinitionStatus",
    "DeliveryPolicy",
    "DiscoveredRoleDefinition",
    "DiscoveryInputError",
    "RegistryError",
    "ManifestRoutingResolution",
    "ResolvedRole",
    "ResolvedSource",
    "ReviewPolicy",
    "RoleDefinitionSource",
    "RoleLayer",
    "RoleManifest",
    "RoleRegistry",
    "RoleResolution",
    "RoleResolutionBlocked",
    "RoleResolutionReason",
    "RoutingHint",
    "Sensitivity",
    "discover_role_definitions",
    "ordered_definitions",
    "resolve_role",
    "resolve_manifest_routing",
]
