use serde::Deserialize;
use std::path::Path;

#[derive(Debug, Deserialize)]
pub struct Contract {
    pub identity: Identity,
    pub recency: Recency,
    pub failure: Failure,
    pub tie: Tie,
    pub output: Output,
}

#[derive(Debug, Deserialize)]
pub struct Identity {
    pub check_namespace: String,
    pub check_name_field: String,
    pub check_workflow_field: String,
    pub status_namespace: String,
    pub status_context_field: String,
}

#[derive(Debug, Deserialize)]
pub struct Recency {
    pub fields: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct Failure {
    pub bucket_values: Vec<String>,
    pub conclusion_state_values: Vec<String>,
}

#[derive(Debug, Deserialize)]
pub struct Tie {
    pub failure_replaces_non_failure: bool,
    pub otherwise: String,
}

#[derive(Debug, Deserialize)]
pub struct Output {
    pub order: String,
}

pub fn load_contract(path: &Path) -> Result<Contract, Box<dyn std::error::Error>> {
    let text = std::fs::read_to_string(path)?;
    Ok(toml::from_str(&text)?)
}

/// One escaper for BOTH target languages: `\xHH` is a valid escape in Rust
/// and Python alike, so a contract value carrying a control character cannot
/// render a generated file that fails to parse. A trailing comma keeps a
/// single-element list a list in Python (a 1-tuple, not a parenthesized
/// string) and is legal in a Rust array too.
fn quote_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || (c as u32) == 0x7f => {
                out.push_str(&format!("\\x{:02x}", c as u32))
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn quote_list(values: &[String]) -> String {
    let mut out = values
        .iter()
        .map(|value| quote_string(value))
        .collect::<Vec<_>>()
        .join(", ");
    if !values.is_empty() {
        out.push(',');
    }
    out
}

/// The generated selectors are correct only under these contract invariants;
/// one validator shared by both renderers, so the two can never disagree
/// about what a valid contract is.
fn validate(contract: &Contract) {
    assert_eq!(contract.tie.otherwise, "first_seen");
    assert_eq!(contract.output.order, "first_seen_slots");
    assert!(contract.tie.failure_replaces_non_failure);
}

const INVARIANT_PROSE: &str = concat!(
    "Supersession invariants, carried from the deleted hand-written selectors:\n",
    "a slot is replaced ONLY by a strictly newer row; equal timestamps replace\n",
    "only fail over non-fail and otherwise keep first-seen (fail-closed against\n",
    "a green that cannot prove its recency). Check and status namespaces key\n",
    "separately, so a StatusContext never supersedes a CheckRun, and the\n",
    "workflow dimension keeps same-named jobs from different workflows from\n",
    "superseding each other.",
);

fn comment_block(prefix: &str, body: &str) -> String {
    body.lines()
        .map(|line| format!("{prefix}{line}\n"))
        .collect()
}

pub fn render_rust(contract: &Contract) -> String {
    validate(contract);
    let recency_fields = quote_list(&contract.recency.fields);
    let bucket_values = quote_list(&contract.failure.bucket_values);
    let failure_values = quote_list(&contract.failure.conclusion_state_values);
    let identity = &contract.identity;
    format!(
        "// GENERATED by crates/fno-agents/codegen/check_supersession.rs.\n\
         // Do not edit. Change codegen/check_supersession.toml and rebuild.\n\
         {invariant_prose}\n\
         use serde_json::Value;\n\n\
         fn text_field<'a>(row: &'a Value, field: &str) -> &'a str {{\n\
             row.get(field).and_then(Value::as_str).unwrap_or(\"\")\n\
         }}\n\n\
         fn identity(row: &Value) -> Option<(String, String, String)> {{\n\
             let name = text_field(row, {check_name});\n\
             if !name.is_empty() {{\n\
                 return Some(({check_ns}.to_string(), name.to_string(), text_field(row, {workflow}).to_string()));\n\
             }}\n\
             let context = text_field(row, {status_context});\n\
             if !context.is_empty() {{\n\
                 return Some(({status_ns}.to_string(), context.to_string(), String::new()));\n\
             }}\n\
             None\n\
         }}\n\n\
         fn timestamp(row: &Value) -> &str {{\n\
             for field in [{recency_fields}] {{\n\
                 let value = text_field(row, field);\n\
                 if !value.is_empty() {{\n\
                     return value;\n\
                 }}\n\
             }}\n\
             \"\"\n\
         }}\n\n\
         fn is_failure(row: &Value) -> bool {{\n\
             let status = text_field(row, \"status\").to_ascii_uppercase();\n\
             if !status.is_empty() && status != \"COMPLETED\" {{\n\
                 return false;\n\
             }}\n\
             let bucket = text_field(row, \"bucket\").to_ascii_lowercase();\n\
             if [{bucket_values}].iter().any(|value| bucket == *value) {{\n\
                 return true;\n\
             }}\n\
             let conclusion = text_field(row, \"conclusion\");\n\
             let conclusion = if conclusion.is_empty() {{\n\
                 text_field(row, \"state\")\n\
             }} else {{\n\
                 conclusion\n\
             }};\n\
             [{failure_values}].iter().any(|value| conclusion.eq_ignore_ascii_case(value))\n\
         }}\n\n\
         pub fn latest_per_name(checks: &Value) -> Value {{\n\
             let Some(rows) = checks.as_array() else {{\n\
                 return checks.clone();\n\
             }};\n\
             let mut slots: Vec<(Option<(String, String, String)>, Value)> = Vec::new();\n\
             let mut positions: std::collections::HashMap<(String, String, String), usize> =\n\
                 std::collections::HashMap::new();\n\
             for row in rows {{\n\
                 let Some(key) = identity(row) else {{\n\
                     slots.push((None, row.clone()));\n\
                     continue;\n\
                 }};\n\
                 let Some(&position) = positions.get(&key) else {{\n\
                     positions.insert(key.clone(), slots.len());\n\
                     slots.push((Some(key), row.clone()));\n\
                     continue;\n\
                 }};\n\
                 let existing = &slots[position].1;\n\
                 let incoming_time = timestamp(row);\n\
                 let existing_time = timestamp(existing);\n\
                 let replaces = incoming_time > existing_time\n\
                     || (incoming_time == existing_time\n\
                         && is_failure(row)\n\
                         && !is_failure(existing));\n\
                 if replaces {{\n\
                     slots[position].1 = row.clone();\n\
                 }}\n\
             }}\n\
             Value::Array(slots.into_iter().map(|(_, row)| row).collect())\n\
         }}\n",
        check_ns = quote_string(&identity.check_namespace),
        check_name = quote_string(&identity.check_name_field),
        workflow = quote_string(&identity.check_workflow_field),
        status_ns = quote_string(&identity.status_namespace),
        status_context = quote_string(&identity.status_context_field),
        recency_fields = recency_fields,
        bucket_values = bucket_values,
        failure_values = failure_values,
        invariant_prose = comment_block("// ", INVARIANT_PROSE),
    )
}

pub fn render_python(contract: &Contract) -> String {
    validate(contract);
    let recency_fields = quote_list(&contract.recency.fields);
    let bucket_values = quote_list(&contract.failure.bucket_values);
    let failure_values = quote_list(&contract.failure.conclusion_state_values);
    let identity = &contract.identity;
    let template = r#"# GENERATED by crates/fno-agents/codegen/check_supersession.rs.
# Do not edit. Change the TOML contract and rebuild.
__INVARIANT_PROSE__
from __future__ import annotations

from typing import Sequence


def _text(row: dict, field: str) -> str:
    value = row.get(field)
    return value if isinstance(value, str) else ""


def _identity(row: dict) -> tuple[str, str, str] | None:
    name = _text(row, __CHECK_NAME__)
    if name:
        return (__CHECK_NAMESPACE__, name, _text(row, __WORKFLOW_FIELD__))
    context = _text(row, __STATUS_CONTEXT_FIELD__)
    if context:
        return (__STATUS_NAMESPACE__, context, "")
    return None


def _timestamp(row: dict) -> str:
    for field in (__RECENCY_FIELDS__):
        value = _text(row, field)
        if value:
            return value
    return ""


def _is_failure(row: dict) -> bool:
    status = _text(row, "status").upper()
    if status and status != "COMPLETED":
        return False
    if _text(row, "bucket").lower() in (__BUCKET_VALUES__):
        return True
    conclusion = _text(row, "conclusion") or _text(row, "state")
    return conclusion.upper() in (__FAILURE_VALUES__)


def latest_per_name(rollup: Sequence[dict]) -> list[dict]:
    latest: dict[tuple[str, str, str], int] = {}
    slots: list[tuple[tuple[str, str, str] | None, dict]] = []
    for row in rollup:
        key = _identity(row)
        if key is None:
            slots.append((None, row))
            continue
        position = latest.get(key)
        if position is None:
            latest[key] = len(slots)
            slots.append((key, row))
            continue
        existing = slots[position][1]
        incoming_time = _timestamp(row)
        existing_time = _timestamp(existing)
        replaces = incoming_time > existing_time or (
            incoming_time == existing_time
            and _is_failure(row)
            and not _is_failure(existing)
        )
        if replaces:
            slots[position] = (key, row)
    return [row for _, row in slots]
"#;
    template
        .replace(
            "__INVARIANT_PROSE__",
            comment_block("# ", INVARIANT_PROSE).trim_end_matches('\n'),
        )
        .replace(
            "__CHECK_NAMESPACE__",
            &quote_string(&identity.check_namespace),
        )
        .replace("__CHECK_NAME__", &quote_string(&identity.check_name_field))
        .replace(
            "__WORKFLOW_FIELD__",
            &quote_string(&identity.check_workflow_field),
        )
        .replace(
            "__STATUS_NAMESPACE__",
            &quote_string(&identity.status_namespace),
        )
        .replace(
            "__STATUS_CONTEXT_FIELD__",
            &quote_string(&identity.status_context_field),
        )
        .replace("__RECENCY_FIELDS__", &recency_fields)
        .replace("__BUCKET_VALUES__", &bucket_values)
        .replace("__FAILURE_VALUES__", &failure_values)
}
