#!/usr/bin/env bash
# scripts/ci/check-harness-capabilities-fresh.sh
#
# Tripwire, not a sync step. `crates/fno-agents/build.rs` PRODUCES
# cli/src/fno/agents/harness_capabilities.toml from the canonical
# crates/fno-agents/src/harness_capabilities.toml on every build, so the only
# way the two diverge now is a hand edit of the copy. This gate catches that.
#
# Modes:
#   (default)    compare the COMMITTED bytes of both files
#   --worktree   compare the working-tree bytes
#   --write      copy canonical over copy and exit 0
#
# Comparing HEAD by default closes an ordering hazard the producer creates: a
# CI job that builds Rust before running this gate would resync the WORKTREE
# copy and launder a hand edit that is still committed. HEAD is order-independent.
#
# Exit codes: 0 fresh, 1 diverged, 2 misuse (a file is missing).
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/gate-fresh-common.sh"
gate_parse_mode "$@"
gate_resolve_repo_root
MODE="$GATE_MODE"

CANONICAL_REL="crates/fno-agents/src/harness_capabilities.toml"
COPY_REL="cli/src/fno/agents/harness_capabilities.toml"

CANONICAL="$REPO_ROOT/$CANONICAL_REL"
COPY="$REPO_ROOT/$COPY_REL"

if [[ ! -f "$CANONICAL" ]]; then
  echo "ERROR: canonical harness_capabilities.toml missing at $CANONICAL_REL" >&2
  exit 2
fi

if [[ ! -f "$COPY" ]]; then
  echo "ERROR: copy harness_capabilities.toml missing at $COPY_REL" >&2
  exit 2
fi

if [[ "$MODE" == "write" ]]; then
  cp "$CANONICAL" "$COPY"
  echo "harness capabilities copy written from $CANONICAL_REL"
  exit 0
fi

TMPDIR_GATE="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_GATE"' EXIT

LEFT="$CANONICAL"
RIGHT="$COPY"
SCOPE="worktree"
if [[ "$MODE" == "committed" ]]; then
  # Degrade to the worktree when either blob is absent at HEAD (an unborn
  # branch, or a file not yet tracked). A repo with nothing committed has no
  # committed drift to find, and silently passing would be worse than saying so.
  if gate_committed_blob "$CANONICAL_REL" "$TMPDIR_GATE/canonical" \
    && gate_committed_blob "$COPY_REL" "$TMPDIR_GATE/copy"; then
    LEFT="$TMPDIR_GATE/canonical"
    RIGHT="$TMPDIR_GATE/copy"
    SCOPE="committed"
  else
    echo "NOTE: no committed blobs for both paths; comparing the worktree instead" >&2
  fi
fi

if ! cmp -s "$LEFT" "$RIGHT"; then
  echo "ERROR: harness_capabilities.toml copies have diverged:" >&2
  echo "  canonical: $CANONICAL_REL" >&2
  echo "  copy:      $COPY_REL" >&2
  echo "  compared:  $SCOPE bytes" >&2
  echo "" >&2
  echo "The copy is GENERATED by crates/fno-agents/build.rs. To resync, run:" >&2
  echo "  cargo build -p fno-agents" >&2
  echo "or, with no cargo toolchain:" >&2
  echo "  bash scripts/ci/check-harness-capabilities-fresh.sh --write" >&2
  echo "  cp $CANONICAL_REL $COPY_REL" >&2
  exit 1
fi

echo "harness capabilities table fresh ($SCOPE)"
