#!/usr/bin/env bash
# scripts/ci/check-harness-capabilities-fresh.sh
#
# Tripwire, not a sync step. `crates/fno-agents/build.rs` PRODUCES
# cli/src/fno/agents/harness_capabilities.toml from the canonical
# crates/fno-agents/src/harness_capabilities.toml on every build, so the only
# way the two diverge now is a hand edit of the copy. This gate catches that.
#
# Modes:
#   (default)    compare the COMMITTED bytes of both files
#   --worktree   compare the working-tree bytes
#   --write      copy canonical over copy and exit 0
#
# Comparing HEAD by default closes an ordering hazard the producer creates: a
# CI job that builds Rust before running this gate would resync the WORKTREE
# copy and launder a hand edit that is still committed. HEAD is order-independent.
#
# Exit codes: 0 fresh, 1 diverged, 2 misuse (a file is missing).
set -euo pipefail

MODE="committed"
for arg in "$@"; do
  case "$arg" in
    --write) MODE="write" ;;
    --worktree) MODE="worktree" ;;
    -h|--help)
      sed -n '2,18p' "${BASH_SOURCE[0]}"
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $arg" >&2
      echo "usage: $(basename "${BASH_SOURCE[0]}") [--write|--worktree]" >&2
      exit 2
      ;;
  esac
done

# Resolve REPO_ROOT defensively. The naive $(git rev-parse ...) inside
# command substitution can propagate git's rc=128 silently when bash is
# running with inherit_errexit (seen on GitHub Actions ubuntu-latest with
# bash 5.x). The explicit `if ! ...; then` form contains the failure
# regardless of inherit_errexit semantics.
REPO_ROOT=""
if git_root=$(git rev-parse --show-toplevel 2>/dev/null); then
  REPO_ROOT="$git_root"
fi
if [[ -z "$REPO_ROOT" ]]; then
  # Fallback: walk up from script location looking for .git
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  candidate="$SCRIPT_DIR"
  while [[ "$candidate" != "/" && "$candidate" != "." ]]; do
    if [[ -e "$candidate/.git" ]]; then
      REPO_ROOT="$candidate"
      break
    fi
    candidate="$(dirname "$candidate")"
  done
fi
if [[ -z "$REPO_ROOT" ]]; then
  echo "ERROR: not in a git repo (git rev-parse failed and no .git found via script-dir walk-up)" >&2
  exit 2
fi

CANONICAL_REL="crates/fno-agents/src/harness_capabilities.toml"
COPY_REL="cli/src/fno/agents/harness_capabilities.toml"

CANONICAL="$REPO_ROOT/$CANONICAL_REL"
COPY="$REPO_ROOT/$COPY_REL"

if [[ ! -f "$CANONICAL" ]]; then
  echo "ERROR: canonical harness_capabilities.toml missing at $CANONICAL_REL" >&2
  exit 2
fi

if [[ ! -f "$COPY" ]]; then
  echo "ERROR: copy harness_capabilities.toml missing at $COPY_REL" >&2
  exit 2
fi

if [[ "$MODE" == "write" ]]; then
  cp "$CANONICAL" "$COPY"
  echo "harness capabilities copy written from $CANONICAL_REL"
  exit 0
fi

TMPDIR_GATE="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_GATE"' EXIT

LEFT="$CANONICAL"
RIGHT="$COPY"
SCOPE="worktree"
if [[ "$MODE" == "committed" ]]; then
  # Degrade to the worktree when either blob is absent at HEAD (an unborn
  # branch, or a file not yet tracked). A repo with nothing committed has no
  # committed drift to find, and silently passing would be worse than saying so.
  if git -C "$REPO_ROOT" show "HEAD:$CANONICAL_REL" > "$TMPDIR_GATE/canonical" 2>/dev/null \
    && git -C "$REPO_ROOT" show "HEAD:$COPY_REL" > "$TMPDIR_GATE/copy" 2>/dev/null; then
    LEFT="$TMPDIR_GATE/canonical"
    RIGHT="$TMPDIR_GATE/copy"
    SCOPE="committed"
  else
    echo "NOTE: no committed blobs for both paths; comparing the worktree instead" >&2
  fi
fi

if ! cmp -s "$LEFT" "$RIGHT"; then
  echo "ERROR: harness_capabilities.toml copies have diverged:" >&2
  echo "  canonical: $CANONICAL_REL" >&2
  echo "  copy:      $COPY_REL" >&2
  echo "  compared:  $SCOPE bytes" >&2
  echo "" >&2
  echo "The copy is GENERATED by crates/fno-agents/build.rs. To resync, run:" >&2
  echo "  cargo build -p fno-agents" >&2
  echo "or, with no cargo toolchain:" >&2
  echo "  bash scripts/ci/check-harness-capabilities-fresh.sh --write" >&2
  echo "  cp $CANONICAL_REL $COPY_REL" >&2
  exit 1
fi

echo "harness capabilities table fresh ($SCOPE)"
