#!/usr/bin/env bash
# check-generated-manifest.sh - keep generated-artifacts.tsv complete and live.
#
# Fails when:
#   (a) a manifest glob matches no tracked file (a renamed or deleted copy), or
#   (b) a tracked file carries a generated marker (`DO NOT EDIT`, `@generated`,
#       `Generated by`) in its first 5 lines, and no manifest glob or
#       skill-bundles.yaml destination covers it.
#
# hooks/generated-write-guard.sh refuses edits only to paths these two lists
# name, so an unlisted generated file is an unguarded one.
#
# Usage: bash scripts/ci/check-generated-manifest.sh [repo-root]
set -uo pipefail

ROOT="${1:-$(git rev-parse --show-toplevel)}"
cd "$ROOT" || exit 2
MANIFEST="generated-artifacts.tsv"
[[ -f "$MANIFEST" ]] || { echo "check-generated-manifest: $MANIFEST not found" >&2; exit 2; }

GLOBS=()
while IFS=$'\t' read -r glob _source _regen; do
    [[ -z "$glob" || "$glob" == \#* ]] && continue
    GLOBS+=("$glob")
done < "$MANIFEST"

TRACKED=()
while IFS= read -r -d '' f; do
    TRACKED+=("$f")
done < <(git ls-files -z)

BUNDLE_DESTS=()
if [[ -f skill-bundles.yaml ]]; then
    rows="$(python3 scripts/lib/parse-bundle-manifest.py skill-bundles.yaml 2>/dev/null)" \
        || rows="$(uv run --no-project --with pyyaml python3 scripts/lib/parse-bundle-manifest.py skill-bundles.yaml)" \
        || { echo "check-generated-manifest: could not parse skill-bundles.yaml" >&2; exit 2; }
    while IFS=$'\t' read -r type skill _source dest _meta; do
        [[ -n "$type" ]] || continue
        case "$type" in
            pack-*) BUNDLE_DESTS+=("$dest") ;;
            *)      BUNDLE_DESTS+=("skills/$skill/$dest") ;;
        esac
    done <<< "$rows"
fi

fail=0

for glob in ${GLOBS[@]+"${GLOBS[@]}"}; do
    hit=0
    for f in "${TRACKED[@]}"; do
        # shellcheck disable=SC2053
        if [[ "$f" == $glob ]]; then hit=1; break; fi
    done
    if [[ $hit -eq 0 ]]; then
        echo "check-generated-manifest: row '$glob' matches no tracked file; fix or delete the row in $MANIFEST" >&2
        fail=1
    fi
done

_covered() {
    local f="$1" g d
    for g in ${GLOBS[@]+"${GLOBS[@]}"}; do
        # shellcheck disable=SC2053
        [[ "$f" == $g ]] && return 0
    done
    for d in ${BUNDLE_DESTS[@]+"${BUNDLE_DESTS[@]}"}; do
        [[ "$f" == "$d" || "$f" == "$d/"* ]] && return 0
    done
    return 1
}

MARKER='DO NOT EDIT|@generated|Generated by'
# One grep finds every file that mentions a marker anywhere; only those pay
# the per-file first-5-lines read.
while IFS= read -r f; do
    [[ -f "$f" ]] || continue
    head -5 "$f" 2>/dev/null | LC_ALL=C grep -q -I -E "$MARKER" || continue
    if ! _covered "$f"; then
        echo "check-generated-manifest: $f carries a generated marker but no row in $MANIFEST or skill-bundles.yaml covers it; add a row naming its source and regen command" >&2
        fail=1
    fi
done < <(git ls-files -z | xargs -0 env LC_ALL=C grep -l -I -E "$MARKER" -- 2>/dev/null)

if [[ $fail -eq 0 ]]; then
    echo "check-generated-manifest: ok (${#GLOBS[@]} rows, ${#BUNDLE_DESTS[@]} bundle destinations)"
fi
exit "$fail"
