#!/usr/bin/env bash
# scripts/ci/check-events-limits-fresh.sh
#
# Tripwire for a hand-edited crates/fno-agents/src/events_limits.toml.
#
# cli/src/fno/events/schema.yaml is canonical. `crates/fno-agents/build.rs`
# PROJECTS its `limits` block into events_limits.toml, which the crate
# `include_str!`s, so the committed file is what a crates.io build compiles
# against. This gate re-renders the same projection and compares. It exists
# only because that generated file is tracked and therefore hand-editable.
#
# Modes:
#   (default)    compare the COMMITTED bytes of the generated file
#   --worktree   compare the working-tree bytes
#   --write      regenerate the file from schema.yaml and exit 0
#
# Exit codes: 0 fresh, 1 diverged, 2 misuse (a file is missing / unparseable).
set -euo pipefail

MODE="committed"
for arg in "$@"; do
  case "$arg" in
    --write) MODE="write" ;;
    --worktree) MODE="worktree" ;;
    -h|--help)
      sed -n '2,17p' "${BASH_SOURCE[0]}"
      exit 0
      ;;
    *)
      echo "ERROR: unknown argument: $arg" >&2
      echo "usage: $(basename "${BASH_SOURCE[0]}") [--write|--worktree]" >&2
      exit 2
      ;;
  esac
done

# Same defensive root resolution as check-harness-capabilities-fresh.sh: a bare
# $(git rev-parse ...) can propagate rc=128 under inherit_errexit.
REPO_ROOT=""
if git_root=$(git rev-parse --show-toplevel 2>/dev/null); then
  REPO_ROOT="$git_root"
fi
if [[ -z "$REPO_ROOT" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  candidate="$SCRIPT_DIR"
  while [[ "$candidate" != "/" && "$candidate" != "." ]]; do
    if [[ -e "$candidate/.git" ]]; then
      REPO_ROOT="$candidate"
      break
    fi
    candidate="$(dirname "$candidate")"
  done
fi
if [[ -z "$REPO_ROOT" ]]; then
  echo "ERROR: not in a git repo (git rev-parse failed and no .git found via script-dir walk-up)" >&2
  exit 2
fi

SCHEMA_REL="cli/src/fno/events/schema.yaml"
GENERATED_REL="crates/fno-agents/src/events_limits.toml"

SCHEMA="$REPO_ROOT/$SCHEMA_REL"
GENERATED="$REPO_ROOT/$GENERATED_REL"

if [[ ! -f "$SCHEMA" ]]; then
  echo "ERROR: canonical event schema missing at $SCHEMA_REL" >&2
  exit 2
fi
if [[ ! -f "$GENERATED" ]]; then
  echo "ERROR: generated events_limits.toml missing at $GENERATED_REL" >&2
  exit 2
fi

PYTHON3="${PYTHON3:-python3}"

TMPDIR_GATE="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_GATE"' EXIT

# Render the expectation with the SAME projection build.rs uses: read
# limits.max_data_bytes and limits.data_size_encoding, emit the two keys under
# the generated-file banner.
#
# Stdlib only, deliberately. The guards job installs a bare interpreter, so a
# PyYAML import here is a red check on every PR (measured: "PyYAML unavailable"
# exit 2 in the guards job). The block this reads is two scalars under one
# top-level key, and the reader REFUSES with exit 2 on any shape it does not
# recognize, so it can never pass by mis-reading. build.rs does the real YAML
# parse; this is its twin, and disagreement fails loud.
if ! "$PYTHON3" - "$SCHEMA" > "$TMPDIR_GATE/expected" <<'PYEOF'
import re
import sys

with open(sys.argv[1], encoding="utf-8") as handle:
    lines = handle.read().splitlines()

# The top-level `limits:` key, at column 0, exactly once.
starts = [i for i, line in enumerate(lines) if line.rstrip() == "limits:"]
if len(starts) != 1:
    print(
        f"ERROR: expected exactly one top-level 'limits:' block, found {len(starts)}",
        file=sys.stderr,
    )
    raise SystemExit(2)

# Its body: the indented, non-blank, non-comment lines that follow.
body = []
for line in lines[starts[0] + 1:]:
    if not line.strip() or line.lstrip().startswith("#"):
        continue
    if not line[:1].isspace():
        break
    body.append(line.strip())

entry = re.compile(r'^([A-Za-z_][A-Za-z0-9_]*):\s*(.*?)\s*$')
found = {}
for item in body:
    match = entry.match(item)
    if match is None:
        print(f"ERROR: unreadable line in the limits block: {item!r}", file=sys.stderr)
        raise SystemExit(2)
    found[match.group(1)] = match.group(2)

raw_bytes = found.get("max_data_bytes", "")
encoding = found.get("data_size_encoding", "").strip("'\"")
if not raw_bytes.isdigit() or not encoding:
    print(
        "ERROR: schema.yaml limits block is missing max_data_bytes or "
        "data_size_encoding",
        file=sys.stderr,
    )
    raise SystemExit(2)

sys.stdout.write(
    "# GENERATED by crates/fno-agents/build.rs from cli/src/fno/events/schema.yaml.\n"
    "# Do not edit. Change the limits block in schema.yaml and rebuild.\n"
    f"max_data_bytes = {int(raw_bytes)}\n"
    f'data_size_encoding = "{encoding}"\n'
)
PYEOF
then
  exit 2
fi

if [[ "$MODE" == "write" ]]; then
  cp "$TMPDIR_GATE/expected" "$GENERATED"
  echo "events limits regenerated into $GENERATED_REL"
  exit 0
fi

ACTUAL="$GENERATED"
SCOPE="worktree"
if [[ "$MODE" == "committed" ]]; then
  if git -C "$REPO_ROOT" show "HEAD:$GENERATED_REL" > "$TMPDIR_GATE/actual" 2>/dev/null; then
    ACTUAL="$TMPDIR_GATE/actual"
    SCOPE="committed"
  else
    echo "NOTE: no committed blob for $GENERATED_REL; comparing the worktree instead" >&2
  fi
fi

if ! cmp -s "$TMPDIR_GATE/expected" "$ACTUAL"; then
  echo "ERROR: events limits copy has diverged from its source:" >&2
  echo "  canonical: $SCHEMA_REL" >&2
  echo "  generated: $GENERATED_REL" >&2
  echo "  compared:  $SCOPE bytes" >&2
  echo "" >&2
  echo "$GENERATED_REL is GENERATED. Change the limits block in $SCHEMA_REL, then:" >&2
  echo "  cargo build -p fno-agents" >&2
  echo "or, with no cargo toolchain:" >&2
  echo "  bash scripts/ci/check-events-limits-fresh.sh --write" >&2
  exit 1
fi

echo "events limits table fresh ($SCOPE)"
