#!/usr/bin/env bash
# scripts/ci/check-harness-capability-matrix-fresh.sh
#
# Tripwire, not a sync step. The features capability matrix doc
# (`docs/harnesses/capability-matrix.md`) is GENERATED by
# `fno doctor harness-matrix --write` from the canonical capability table
# (`crates/fno-agents/src/harness_capabilities.toml`, x-a3e8). A hand edit
# of the doc, or a table edit that skipped the regeneration, is the drift
# this gate catches.
#
# The render is run against the COMMITTED table bytes in the default mode,
# so the comparison answers "does the committed doc match the committed
# table", not "does it match whatever is in the worktree today".
#
# Modes:
#   (default)    compare the COMMITTED matrix against a render of the
#                COMMITTED table
#   --worktree   compare the working-tree bytes
#   --write      regenerate the doc from the worktree table and exit 0
#
# Generated docs are never hand-edited; the remedy for a stale matrix is
# the verb, not an edit.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/ci/lib/gate-fresh-common.sh
source "$SCRIPT_DIR/lib/gate-fresh-common.sh"

CANONICAL_REL="crates/fno-agents/src/harness_capabilities.toml"
MATRIX_REL="docs/harnesses/capability-matrix.md"

gate_resolve_repo_root
gate_parse_mode "$@"
MODE="$GATE_MODE"

TABLE="$REPO_ROOT/$CANONICAL_REL"
MATRIX="$REPO_ROOT/$MATRIX_REL"

if [[ ! -f "$TABLE" ]]; then
  echo "ERROR: canonical capability table missing at $CANONICAL_REL" >&2
  exit 2
fi

render() {
  # Render from the table at $1 to stdout. Runs the repo's own renderer,
  # not the installed fno: a stale install must not mask drift.
  python3 "$REPO_ROOT/scripts/diagnostics/render-harness-matrix.py" --table "$1"
}

if [[ "$MODE" == "write" ]]; then
  render "$TABLE" > "$MATRIX"
  echo "harness capability matrix written to $MATRIX_REL"
  exit 0
fi

TMPDIR_GATE="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_GATE"' EXIT

TABLE_BYTES="$TABLE"
MATRIX_BYTES="$MATRIX"
SCOPE="worktree"
if [[ "$MODE" == "committed" ]]; then
  if gate_committed_blob "$CANONICAL_REL" "$TMPDIR_GATE/table" \
    && gate_committed_blob "$MATRIX_REL" "$TMPDIR_GATE/matrix"; then
    TABLE_BYTES="$TMPDIR_GATE/table"
    MATRIX_BYTES="$TMPDIR_GATE/matrix"
    SCOPE="committed"
  else
    echo "NOTE: no committed blobs yet; comparing the worktree instead" >&2
  fi
fi

if [[ ! -f "$MATRIX_BYTES" ]]; then
  echo "harness capability matrix STALE: $MATRIX_REL is missing; run:" >&2
  echo "  fno doctor harness-matrix --write" >&2
  exit 1
fi

if render "$TABLE_BYTES" | diff -u "$MATRIX_BYTES" - > "$TMPDIR_GATE/diff"; then
  echo "harness capability matrix fresh ($SCOPE)"
  exit 0
fi

echo "harness capability matrix STALE ($SCOPE): $MATRIX_REL does not match a render of $CANONICAL_REL; run:" >&2
echo "  fno doctor harness-matrix --write" >&2
echo >&2
sed -n '1,40p' "$TMPDIR_GATE/diff" >&2
exit 1
