#!/usr/bin/env bash
# check-generated-manifest-selftest.sh - watch scripts/ci/check-generated-manifest.sh
# pass on a covered repo and fail on a dead row and on an unlisted marker.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CHECK="$REPO_ROOT/scripts/ci/check-generated-manifest.sh"

PASS=0; FAIL=0
pass() { PASS=$((PASS+1)); printf '[cgm] PASS: %s\n' "$*"; }
fail() { FAIL=$((FAIL+1)); printf '[cgm] FAIL: %s\n' "$*" >&2; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# fixture DIR -> a repo whose one generated file is listed
fixture() {
    mkdir -p "$1/docs"
    git -C "$1" init -q
    printf '# Generated by make gen; DO NOT EDIT\n' > "$1/docs/gen.md"
    printf 'docs/gen.md\tdocs/gen.src\tmake gen\n' > "$1/generated-artifacts.tsv"
    git -C "$1" add docs/gen.md generated-artifacts.tsv
}

# run_check NAME WANT_EXIT DIR [NEEDLE]
run_check() {
    local name="$1" want="$2" dir="$3" needle="${4:-}" out rc
    out="$(bash "$CHECK" "$dir" 2>&1)"; rc=$?
    if [[ $rc -ne $want ]]; then fail "$name: want exit $want got $rc ($out)"; return; fi
    if [[ -n "$needle" && "$out" != *"$needle"* ]]; then fail "$name: output lacks '$needle' ($out)"; return; fi
    pass "$name"
}

fixture "$TMP/ok"
run_check "covered repo passes" 0 "$TMP/ok"

fixture "$TMP/dead"
printf 'docs/renamed.md\tdocs/gen.src\tmake gen\n' >> "$TMP/dead/generated-artifacts.tsv"
run_check "AC2: dead row fails and names the row" 1 "$TMP/dead" "docs/renamed.md"

fixture "$TMP/unlisted"
printf '# Generated by foo; do not edit\n' > "$TMP/unlisted/docs/other.txt"
git -C "$TMP/unlisted" add docs/other.txt
run_check "AC10: unlisted marker fails and names the file" 1 "$TMP/unlisted" "docs/other.txt"

run_check "AC9: this repo passes" 0 "$REPO_ROOT"

printf '[cgm] RESULTS: %d passed, %d failed\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]]
