"""Render the features capability matrix from the capability table (x-a3e8).

GENERATE the copy; never hand-edit it. The rendered file is docs/harnesses/capability-matrix.md, gated by scripts/ci/check-harness-capability-matrix-fresh.sh - the gate is the tripwire for a hand edit, not the sync step. One row per supported harness, the FULL roster, so a roster entry with no capability row (hermes, openclaw today) renders as visible all-unmeasured gaps instead of vanishing. One column per feature key, sourced from the table's own feature probe declarations, so a key added there appears here with no code edit.

This is a docs/CI tool, not runtime: it lives under scripts/ beside the other
diagnostics, keeps the Python compatibility shell out of its line budget, and
is invoked by the freshness gate and by `fno doctor harness-matrix`.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "cli" / "src"))

from fno.harness_names import KNOWN_HARNESSES  # noqa: E402

_MATRIX_REL = Path("docs/harnesses/capability-matrix.md")
_PACKAGED_TABLE = REPO_ROOT / "crates" / "fno-agents" / "src" / "harness_capabilities.toml"

_HEADER = """\
<!-- GENERATED by `fno doctor harness-matrix --write`. DO NOT EDIT.
     A hand edit trips scripts/ci/check-harness-capability-matrix-fresh.sh;
     regenerate from crates/fno-agents/src/harness_capabilities.toml. -->
# Harness capability matrix (features)

What each harness can DO, rendered from the capability table (`map_version {version}`). One row per supported harness - including roster entries with no capability row, which read unmeasured everywhere - and one column per feature key.

| State | Meaning |
|---|---|
| `native` | fno drives it today through a wired lane: the harness's own surface where it exposes one, else a lane fno hosts (the daemon-kept portal) |
| `capable` | real on the harness, and fno has no wired arm |
| `absent` | measured not to exist on this harness |
| `unmeasured` | nobody has looked |

Every non-native cell settles the same way: `fno agents harness probe <harness>` runs the instrument the table declares for that key. The pane-driving mechanics are a different dimension and live in the capability table itself, never here.
"""


def _feature_keys(table: dict) -> list[str]:
    return sorted(
        field[len("features."):]
        for field in table.get("probe", {})
        if field.startswith("features.")
    )


def _cell(row: dict, key: str) -> str:
    claim = row.get("features") or {}
    if not isinstance(claim, dict):
        return "unmeasured"
    return str(claim.get(key, {}).get("state", "unmeasured"))


def render_matrix(table_path: Path) -> str:
    """Render the matrix from one capability table. The gate passes the
    COMMITTED blob so a stale doc is caught against the bytes that would
    ship."""
    with table_path.open("rb") as handle:
        table = tomllib.load(handle)
    harness_rows = table.get("harness", {})
    keys = _feature_keys(table)
    lines = [
        _HEADER.format(version=table.get("map_version", "?")),
        "",
        "| harness | " + " | ".join(keys) + " |",
        "|---" * (len(keys) + 1) + "|",
    ]
    for name in KNOWN_HARNESSES:
        row = harness_rows.get(name) or {}
        cells = " | ".join(f"`{_cell(row, key)}`" for key in keys)
        lines.append(f"| {name} | {cells} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    table_arg = Path(argv[argv.index("--table") + 1]) if "--table" in argv else _PACKAGED_TABLE
    rendered = render_matrix(table_arg)
    if "--write" in argv:
        target = REPO_ROOT / _MATRIX_REL
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
        print(f"harness capability matrix written to {_MATRIX_REL}")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
