"""Render the two harness matrices from the capability table (x-a3e8, x-b7a1).

GENERATE the copies; never hand-edit them. The rendered files are docs/harnesses/capability-matrix.md (harness x feature) and docs/harnesses/verb-matrix.md (fno verb x harness); the rust-ci dirty-tree step is the tripwire for a hand edit, not the sync step. The features matrix has one row per supported harness, the FULL roster, so a roster entry with no capability row (hermes, openclaw today) renders as visible all-unmeasured gaps instead of vanishing, and one column per feature key sourced from the table's own probe declarations, so a key added there appears here with no code edit. The verb matrix has one row per skills/*/SKILL.md and is a PROJECTION, not a measurement: each skill declares what it needs in `requires.harness` and the cell is the worst state the table reports for those needs.

This is a docs/CI tool, not runtime: it lives under scripts/ beside the other
diagnostics, keeps the Python compatibility shell out of its line budget, and
is invoked by the freshness gate and by `fno doctor harness-matrix`.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "cli" / "src"))

from fno.harness_names import KNOWN_HARNESSES  # noqa: E402

_MATRIX_REL = Path("docs/harnesses/capability-matrix.md")
_VERB_MATRIX_REL = Path("docs/harnesses/verb-matrix.md")
_PACKAGED_TABLE = REPO_ROOT / "crates" / "fno-agents" / "src" / "harness_capabilities.toml"
_SKILLS_DIR = REPO_ROOT / "skills"

# The four state definitions in _HEADER are the doc-facing copy of the
# vocabulary whose home is the FEATURE_STATES doc in
# crates/fno-agents/src/harness_capabilities.rs; keep the two in step.

_HEADER = """\
<!-- GENERATED by `fno doctor harness-matrix --write`. DO NOT EDIT.
     A hand edit trips the rust-ci generated-copies dirty-tree step;
     regenerate from crates/fno-agents/src/harness_capabilities.toml. -->
# Harness capability matrix (features)

What each harness can DO, rendered from the capability table (`map_version {version}`). One row per supported harness - including roster entries with no capability row, which read unmeasured everywhere - and one column per feature key.

| State | Meaning |
|---|---|
| `native` | fno drives it today through a wired lane: the harness's own surface where it exposes one, else a lane fno hosts (the daemon-kept portal) |
| `capable` | real on the harness, and fno has no wired arm |
| `absent` | measured not to exist on this harness |
| `unmeasured` | nobody has looked |

Every non-native cell settles the same way: `fno agents harness probe <harness>` runs the instrument the table declares for that key. Until the reader port lands the probe reports feature keys as undeclared rows: the dimension is inert by the split ruling, and this doc measures the table, not the readers. The pane-driving mechanics are a different dimension and live in the capability table itself, never here.
"""

# The verb matrix is a projection of the features matrix above. A skill
# declares its needs once, in frontmatter; nothing here is filled by pattern,
# so a harness nobody has measured reads unmeasured on every verb.
_VERB_HEADER = """\
<!-- GENERATED by `fno doctor harness-matrix --write`. DO NOT EDIT.
     A hand edit trips the rust-ci generated-copies dirty-tree step;
     regenerate from crates/fno-agents/src/harness_capabilities.toml
     and skills/*/SKILL.md frontmatter. -->
# Verb x harness matrix

Which fno verb runs on which harness, rendered from the capability table (`map_version {version}`) and each skill's `requires.harness` frontmatter. One row per `skills/*/SKILL.md`, one column per supported harness. The states are the features vocabulary in [capability-matrix.md](capability-matrix.md).

A cell is a projection, never a fresh measurement. The rule, in order:

1. No capability row for the harness: `unmeasured`.
2. `command_surface = "refused"`: `absent`. Dispatch refuses to render any verb there.
3. Otherwise start at `native` and take the worst over the skill's declared needs, ordered absent < unmeasured < capable < native.

The needs vocabulary is closed. `loop` reads `loop_participation`: `native` is native; `extension` with a shipped `loop_extension` is native, with an empty one capable; `none` is absent. `spawn` and `subagent_dispatch` read `features.<key>.state`; an unwritten key is unmeasured. A skill with no needs runs inline through ordinary tool calls and reads native wherever dispatch renders it. A row covers the skill's DEFAULT lane; a sub-mode that needs more (execute waves, review peer, think subagent) is not a row. A need the table has no key for (a claude prompt cache, say) cannot be declared, so that row reads the dispatch surface; add the key and its probe to the table first.
"""

_NEED_VOCABULARY = ("loop", "spawn", "subagent_dispatch")
_STATE_ORDER = {"absent": 0, "unmeasured": 1, "capable": 2, "native": 3}


def _feature_keys(table: dict) -> list[str]:
    return sorted(
        field[len("features."):]
        for field in table.get("probe", {})
        if field.startswith("features.")
    )


def _cell(row: dict, key: str) -> str:
    claim = row.get("features") or {}
    if not isinstance(claim, dict):
        return "unmeasured"
    entry = claim.get(key)
    if not isinstance(entry, dict):
        return "unmeasured"
    return str(entry.get("state", "unmeasured"))


def _loop_state(row: dict) -> str:
    participation = row.get("loop_participation")
    if participation == "native":
        return "native"
    if participation == "extension":
        return "native" if row.get("loop_extension") else "capable"
    if participation == "none":
        return "absent"
    return "unmeasured"


def verb_cell(row: dict | None, needs: list[str]) -> str:
    """The state one verb reads on one harness. `row` is the harness's
    capability table row, or None for a roster entry with no row."""
    if not row:
        return "unmeasured"
    if row.get("command_surface") == "refused":
        return "absent"
    state = "native"
    for need in needs:
        need_state = _loop_state(row) if need == "loop" else _cell(row, need)
        if _STATE_ORDER[need_state] < _STATE_ORDER[state]:
            state = need_state
    return state


def skill_needs(skills_dir: Path) -> dict[str, list[str]]:
    """Every skill's declared `requires.harness`, keyed by skill name. A
    value outside the vocabulary refuses by naming the skill and the value:
    a typo that silently read as "no needs" would render native by default."""
    needs: dict[str, list[str]] = {}
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        text = skill_md.read_text(encoding="utf-8")
        frontmatter: dict = {}
        if text.startswith("---\n"):
            end = text.find("\n---", 4)
            if end != -1:
                frontmatter = yaml.safe_load(text[4:end]) or {}
        name = str(frontmatter.get("name") or skill_md.parent.name)
        declared = (frontmatter.get("requires") or {}).get("harness") or []
        for value in declared:
            if value not in _NEED_VOCABULARY:
                raise SystemExit(
                    f"{skill_md}: requires.harness value {value!r} is outside "
                    f"the vocabulary {list(_NEED_VOCABULARY)}"
                )
        needs[name] = [str(value) for value in declared]
    return needs


def _load_table(table_path: Path) -> dict:
    with table_path.open("rb") as handle:
        return tomllib.load(handle)


def render_matrix(table_path: Path) -> str:
    """Render the features matrix from one capability table. The gate passes
    the COMMITTED blob so a stale doc is caught against the bytes that would
    ship."""
    table = _load_table(table_path)
    harness_rows = table.get("harness", {})
    keys = _feature_keys(table)
    lines = [
        _HEADER.format(version=table.get("map_version", "?")),
        "",
        "| harness | " + " | ".join(keys) + " |",
        "|---" * (len(keys) + 1) + "|",
    ]
    for name in KNOWN_HARNESSES:
        row = harness_rows.get(name) or {}
        cells = " | ".join(f"`{_cell(row, key)}`" for key in keys)
        lines.append(f"| {name} | {cells} |")
    lines.append("")
    return "\n".join(lines)


def render_verb_matrix(table_path: Path, skills_dir: Path = _SKILLS_DIR) -> str:
    """Render the verb matrix: skill rows against the harness roster."""
    table = _load_table(table_path)
    harness_rows = table.get("harness", {})
    lines = [
        _VERB_HEADER.format(version=table.get("map_version", "?")),
        "",
        "| verb | needs | " + " | ".join(KNOWN_HARNESSES) + " |",
        "|---" * (len(KNOWN_HARNESSES) + 2) + "|",
    ]
    for name, needs in skill_needs(skills_dir).items():
        cells = " | ".join(
            f"`{verb_cell(harness_rows.get(harness), needs)}`" for harness in KNOWN_HARNESSES
        )
        lines.append(f"| {name} | {', '.join(needs) or '-'} | {cells} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    table_arg = Path(argv[argv.index("--table") + 1]) if "--table" in argv else _PACKAGED_TABLE
    rendered = {
        _MATRIX_REL: render_matrix(table_arg),
        _VERB_MATRIX_REL: render_verb_matrix(table_arg),
    }
    if "--write" in argv:
        for rel, text in rendered.items():
            target = REPO_ROOT / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
            print(f"harness matrix written to {rel}")
    else:
        sys.stdout.write("\n".join(rendered.values()))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
