// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/effect_map.rs. Do not edit.
//! The effect table's pure layer: the class dispositions, the canonical
//! digest, and the tool-call map. `effect_gate` owns the approvals store and
//! re-exports this table; the footnote harness reads the map through the
//! fno crate's generated copy, so one table classifies every harness.

use serde_json::{json, Value};
use sha2::{Digest, Sha256};

/// The class table's dispositions, mirroring `EffectDisposition` in models.py.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Disposition {
    Allow,
    RequireApproval,
    Deny,
}

impl Disposition {
    pub fn as_str(self) -> &'static str {
        match self {
            Disposition::Allow => "allow",
            Disposition::RequireApproval => "require_approval",
            Disposition::Deny => "deny",
        }
    }
}

/// Refused until a later explicit policy and adapter contract exist
/// (models.py DENIED_EFFECT_CLASSES).
const DENIED_EFFECT_CLASSES: [&str; 5] = [
    "financial.payment",
    "financial.commitment",
    "signature.contract",
    "employment.action",
    "infrastructure.destructive",
];

/// No external consequence, so no effect approval (models.py INERT_EFFECT_CLASSES).
const INERT_EFFECT_CLASSES: [&str; 2] = ["internal.draft", "internal.research"];

/// Classify an effect class. Function-agnostic: only the class is read.
pub fn classify(effect_class: &str) -> Disposition {
    if DENIED_EFFECT_CLASSES.contains(&effect_class) {
        return Disposition::Deny;
    }
    if INERT_EFFECT_CLASSES.contains(&effect_class) {
        return Disposition::Allow;
    }
    Disposition::RequireApproval
}

/// Digest a mapping so any change to any bound field changes the digest.
/// Byte-identical to models.py `canonical_digest`: sorted keys, `(",", ":")`
/// separators, raw UTF-8 (ensure_ascii=False).
pub fn canonical_digest(value: &Value) -> String {
    fn write(v: &Value, out: &mut String) {
        match v {
            Value::Null => out.push_str("null"),
            Value::Bool(b) => out.push_str(if *b { "true" } else { "false" }),
            Value::Number(n) => out.push_str(&n.to_string()),
            Value::String(s) => out.push_str(&serde_json::to_string(s).unwrap_or_default()),
            Value::Array(items) => {
                out.push('[');
                for (i, item) in items.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    write(item, out);
                }
                out.push(']');
            }
            Value::Object(map) => {
                let mut keys: Vec<&String> = map.keys().collect();
                keys.sort();
                out.push('{');
                for (i, k) in keys.iter().enumerate() {
                    if i > 0 {
                        out.push(',');
                    }
                    out.push_str(&serde_json::to_string(*k).unwrap_or_default());
                    out.push(':');
                    write(&map[*k], out);
                }
                out.push('}');
            }
        }
    }
    let mut canonical = String::new();
    write(value, &mut canonical);
    format!("{:x}", Sha256::digest(canonical.as_bytes()))
}

/// Python `datetime.isoformat()` on an aware UTC datetime: no fraction when
/// the microsecond is zero, `+00:00` suffix either way.
pub(crate) fn isoformat(t: chrono::DateTime<chrono::Utc>) -> String {
    if t.timestamp_subsec_micros() == 0 {
        t.to_rfc3339_opts(chrono::SecondsFormat::Secs, false)
    } else {
        t.to_rfc3339_opts(chrono::SecondsFormat::Micros, false)
    }
}

// -- Tool call to effect class ----------------------------------------------

/// One tool call mapped to the effect class it would exercise.
pub struct MappedEffect {
    pub effect_class: &'static str,
    pub destination: String,
    pub action_digest: String,
}

/// First present input field among the candidates, else `unspecified`.
fn destination_from(input: &Value, keys: &[&str]) -> String {
    for key in keys {
        if let Some(v) = input.get(*key).and_then(Value::as_str) {
            if !v.is_empty() {
                return v.to_string();
            }
        }
    }
    "unspecified".to_string()
}

fn mapped(class: &'static str, destination: String, tool: &str, input: &Value) -> MappedEffect {
    MappedEffect {
        effect_class: class,
        destination,
        action_digest: canonical_digest(&json!({"tool": tool, "input": input})),
    }
}

/// Map one tool call to its effect class, or None when the call carries none.
/// `gh pr merge` and `git push` map to None on purpose: the merge gate and
/// git-protection own them, and this guard never decides them twice.
pub fn map_tool_call(tool_name: &str, tool_input: &Value) -> Option<MappedEffect> {
    if tool_name == "Bash" {
        return map_bash_command(
            tool_input
                .get("command")
                .and_then(Value::as_str)
                .unwrap_or(""),
        );
    }
    let lower = tool_name.to_lowercase();
    if !tool_name.starts_with("mcp__") {
        return None;
    }
    if lower.contains("send") || lower.contains("post_message") {
        return Some(mapped(
            "external.communication",
            destination_from(
                tool_input,
                &[
                    "to",
                    "recipient",
                    "email",
                    "channel",
                    "channel_id",
                    "room",
                    "user",
                    "username",
                    "phone",
                    "webhook",
                ],
            ),
            tool_name,
            tool_input,
        ));
    }
    if lower.contains("publish") || lower.contains("create_post") || lower.contains("deploy") {
        return Some(mapped(
            "external.publication",
            destination_from(
                tool_input,
                &["site", "project", "target", "url", "domain", "page", "name"],
            ),
            tool_name,
            tool_input,
        ));
    }
    None
}

/// The Bash rows of the effect table. Tokens are matched on the command's
/// leading words; anything else is no effect and is never blocked here.
pub fn map_bash_command(command: &str) -> Option<MappedEffect> {
    let tokens: Vec<&str> = command.split_whitespace().collect();
    let input = json!({ "command": command });
    // Merge effects belong to the merge gate and git-protection. A PR or
    // issue comment is part of the review loop, like `gh pr create` and the
    // `gh api` review comments: no person outside the repo receives it.
    if matches!(tokens.as_slice(), ["gh", "pr", "merge", ..])
        || matches!(tokens.as_slice(), ["git", "push", ..])
    {
        return None;
    }
    match tokens.as_slice() {
        ["gws", "gmail", "send", ..] => {
            let destination = tokens
                .iter()
                .position(|t| *t == "--to")
                .and_then(|i| tokens.get(i + 1))
                .map(|s| s.to_string())
                .unwrap_or_else(|| "unspecified".to_string());
            Some(mapped(
                "external.communication",
                destination,
                "Bash",
                &input,
            ))
        }
        ["gh", "repo", "delete", ..]
        | ["gh", "release", "delete", ..]
        | ["aws", "s3", "rm", ..] => Some(mapped(
            "infrastructure.destructive",
            "remote".to_string(),
            "Bash",
            &input,
        )),
        ["gcloud", ..] if tokens.iter().any(|t| *t == "delete") => Some(mapped(
            "infrastructure.destructive",
            "gcp".to_string(),
            "Bash",
            &input,
        )),
        ["stripe", verb, ..] if matches!(*verb, "charge" | "payout" | "transfer") => Some(mapped(
            "financial.payment",
            "stripe".to_string(),
            "Bash",
            &input,
        )),
        _ => None,
    }
}
