// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/live_store_fence.rs. Do not edit.
//! A build from a linked feature worktree refuses to open an operator store.
//!
//! Every writable SQLite open routes through [`refuse_worktree_build_on_operator_store`]
//! before `Connection::open`: a binary whose nearest `.git` ancestor is a FILE
//! (the linked-worktree marker) may not open a store under the passwd home's
//! `.fno`, because its own open-time schema and import steps would run on the
//! operator's store. The canonical checkout (`.git` a directory) and any
//! deployed binary (no `.git` ancestor) are exempt, as is every store outside
//! the home `.fno` or inside the worktree itself. Read-only opens stay
//! unfenced: they cannot migrate a store. There is no bypass flag; the remedy
//! is a different binary or a different store.

use std::path::{Path, PathBuf};

pub fn refuse_worktree_build_on_operator_store(store: &Path) -> Result<(), String> {
    let home = passwd_home();
    // A unit test, or any process cargo launched (its env carries
    // CARGO_MANIFEST_DIR), never touches the operator store, checkout or not:
    // one such run once turned the live registry.json into a directory.
    if cfg!(test) || std::env::var_os("CARGO_MANIFEST_DIR").is_some() {
        if let Some(home) = &home {
            let store = canonical_or_self(store);
            if store.starts_with(canonical_or_self(&home.join(".fno"))) {
                return Err(format!(
                    "refusing to open the live store {} from a cargo-launched build: \
                     set FNO_AGENTS_HOME and FNO_STATE_DIR to a temp directory",
                    store.display()
                ));
            }
        }
    }
    let exe = std::env::current_exe()
        .ok()
        .and_then(|path| std::fs::canonicalize(path).ok());
    refusal(exe.as_deref(), home.as_deref(), store)
}

pub fn operator_state_root() -> Option<PathBuf> {
    passwd_home().map(|home| home.join(".fno"))
}

/// The pure rule. `Ok` whenever the fence cannot place the process: no exe,
/// no passwd home, no `.git` ancestor (deployed), a `.git` DIRECTORY
/// (canonical checkout), a store outside the home `.fno`, or a store under
/// the worktree itself (the checkout's own state, not the operator's).
fn refusal(exe: Option<&Path>, home: Option<&Path>, store: &Path) -> Result<(), String> {
    let Some(exe) = exe else {
        return Ok(());
    };
    let Some(home) = home else {
        return Ok(());
    };
    let Some((worktree, git_is_dir)) = nearest_git_ancestor(exe) else {
        return Ok(());
    };
    if git_is_dir {
        return Ok(());
    }
    let worktree = canonical_or_self(&worktree);
    let home_fno = canonical_or_self(&home.join(".fno"));
    let store = canonical_or_self(store);
    if !store.starts_with(&home_fno) || store.starts_with(&worktree) {
        return Ok(());
    }
    Err(format!(
        "refusing to open the live store {} from a feature-worktree build ({}, worktree {}): \
         this build's store code would run its open-time schema and import steps on the \
         operator's store. Run the deployed binary (fno doctor update), or point this checkout \
         at its own store.",
        store.display(),
        exe.display(),
        worktree.display()
    ))
}

/// The nearest ancestor of `exe` holding `.git`, with whether that `.git` is
/// a directory (canonical checkout) or a file (linked worktree).
fn nearest_git_ancestor(exe: &Path) -> Option<(PathBuf, bool)> {
    let mut candidate = exe.parent()?;
    loop {
        let git = candidate.join(".git");
        if git.exists() {
            return Some((candidate.to_path_buf(), git.is_dir()));
        }
        candidate = candidate.parent()?;
    }
}

/// Canonical form with a fallback for paths that do not fully exist yet:
/// canonicalize the deepest existing ancestor and re-append the missing tail,
/// so a store the guarded open is ABOUT to create still compares equal to its
/// canonical neighbors even when several leading directories are new.
fn canonical_or_self(path: &Path) -> PathBuf {
    if let Ok(canonical) = std::fs::canonicalize(path) {
        return canonical;
    }
    let mut missing: Vec<std::ffi::OsString> = Vec::new();
    let mut probe = path.to_path_buf();
    loop {
        if let Ok(canonical) = std::fs::canonicalize(&probe) {
            return missing
                .iter()
                .rev()
                .fold(canonical, |acc, part| acc.join(part));
        }
        match probe.parent() {
            Some(parent) if parent != probe => {
                missing.push(probe.file_name().unwrap_or_default().to_os_string());
                probe = parent.to_path_buf();
            }
            _ => return path.to_path_buf(),
        }
    }
}

/// The home directory of the real user behind this process, from the passwd
/// database. Never `$HOME`: a test that points `$HOME` at a tempdir must stay
/// outside the fence, while the store it guards does not.
#[cfg(unix)]
pub(crate) fn passwd_home() -> Option<PathBuf> {
    let mut buf = vec![0u8; 4096];
    let mut pwd: libc::passwd = unsafe { std::mem::zeroed() };
    let mut result: *mut libc::passwd = std::ptr::null_mut();
    let status = unsafe {
        libc::getpwuid_r(
            libc::getuid(),
            &mut pwd,
            buf.as_mut_ptr().cast(),
            buf.len(),
            &mut result,
        )
    };
    if status != 0 || result.is_null() || pwd.pw_dir.is_null() {
        return None;
    }
    let dir = unsafe { std::ffi::CStr::from_ptr(pwd.pw_dir) }
        .to_string_lossy()
        .to_string();
    if dir.is_empty() {
        None
    } else {
        Some(PathBuf::from(dir))
    }
}

#[cfg(not(unix))]
pub(crate) fn passwd_home() -> Option<PathBuf> {
    None
}
