// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/otel_read.rs. Do not edit.
//! Shared read-only telemetry queries used by doctor and the lead check-in.

use std::collections::BTreeSet;
use std::path::Path;
use std::time::Duration;

use chrono::{DateTime, Utc};
use rusqlite::{Connection, OpenFlags};
use serde_json::{json, Value};

pub fn schema_sql() -> &'static str {
    "CREATE TABLE IF NOT EXISTS api_requests (\n    dedupe_key TEXT PRIMARY KEY,\n    session_id TEXT NOT NULL,\n    ts TEXT,\n    model TEXT,\n    cost_usd_micros INTEGER,\n    input_tokens INTEGER,\n    output_tokens INTEGER,\n    cache_read_tokens INTEGER,\n    cache_creation_tokens INTEGER,\n    skill_name TEXT,\n    plugin_name TEXT,\n    agent_name TEXT\n);\n\nCREATE TABLE IF NOT EXISTS otel_events (\n    dedupe_key TEXT PRIMARY KEY NOT NULL,\n    event_name TEXT NOT NULL,\n    ts TEXT,\n    session_id TEXT,\n    prompt_id TEXT,\n    attributes TEXT NOT NULL CHECK (json_valid(attributes)),\n    resource TEXT NOT NULL CHECK (json_valid(resource))\n);\n\nCREATE INDEX IF NOT EXISTS api_requests_session_time ON api_requests(session_id, ts);\nCREATE INDEX IF NOT EXISTS otel_events_session_time ON otel_events(session_id, ts);\n"
}

fn open(db: &Path) -> Result<Option<Connection>, String> {
    match std::fs::metadata(db) {
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(format!("telemetry database unavailable: {error}")),
        Ok(_) => {}
    }
    let conn = Connection::open_with_flags(db, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .map_err(|error| format!("telemetry database unreadable: {error}"))?;
    conn.busy_timeout(Duration::from_secs(1))
        .map_err(|error| error.to_string())?;
    Ok(Some(conn))
}

pub fn session_cost_usd(db: &Path, session: &str) -> Option<f64> {
    let conn = open(db).ok()??;
    conn.query_row(
        "SELECT SUM(cost_usd_micros) FROM api_requests WHERE session_id=?1 AND cost_usd_micros IS NOT NULL",
        [session], |row| row.get::<_, Option<i64>>(0),
    ).ok()?.map(|micros| micros as f64 / 1_000_000.0)
}

fn workers(registry: &Path, now: &DateTime<Utc>) -> Result<(BTreeSet<String>, usize), String> {
    let bytes = match crate::registry_read::registry_text(registry) {
        Ok(bytes) => bytes,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok((BTreeSet::new(), 0))
        }
        Err(error) => return Err(format!("worker registry unreadable: {error}")),
    };
    let value: Value = serde_json::from_str(&bytes)
        .map_err(|error| format!("worker registry invalid: {error}"))?;
    let entries = value
        .get("agents")
        .or_else(|| value.get("entries"))
        .and_then(Value::as_array)
        .ok_or_else(|| "worker registry has no entries array".to_string())?;
    let mut live = BTreeSet::new();
    let mut unknown = 0;
    for entry in entries {
        if entry.get("harness").and_then(Value::as_str) != Some("claude") {
            continue;
        }
        let status = entry.get("status").and_then(Value::as_str).unwrap_or("");
        if matches!(
            status,
            "exited" | "failed" | "permanent_dead" | "permanent-dead" | "orphaned"
        ) {
            continue;
        }
        let stamp = entry
            .get("liveness_measured_at")
            .and_then(Value::as_str)
            .and_then(|stamp| DateTime::parse_from_rfc3339(stamp).ok())
            .and_then(|stamp| u64::try_from(stamp.timestamp()).ok());
        let word = crate::served_liveness::served_liveness_word(
            entry.get("liveness").and_then(Value::as_str),
            stamp,
            u64::try_from(now.timestamp()).unwrap_or(0),
        );
        match word {
            Some("alive") => match entry
                .get("harness_session_id")
                .and_then(Value::as_str)
                .filter(|s| !s.is_empty())
            {
                Some(session) => {
                    live.insert(session.to_string());
                }
                None => unknown += 1,
            },
            Some("dead") => {}
            _ => unknown += 1,
        }
    }
    Ok((live, unknown))
}

pub fn health(home: &Path, enabled: bool) -> Result<Value, String> {
    health_at(home, enabled, Utc::now())
}

fn health_at(home: &Path, enabled: bool, now: DateTime<Utc>) -> Result<Value, String> {
    let observed = now.to_rfc3339();
    if !enabled {
        return Ok(json!({"status":"off", "observed_at":observed, "window_seconds":3600}));
    }
    let (live, unknown) = workers(&home.join("registry.json"), &now)?;
    let dir = home.join("otel");
    let port = std::fs::read_to_string(dir.join("port"))
        .ok()
        .and_then(|text| text.trim().parse::<u16>().ok())
        .filter(|port| *port != 0);
    let listening = port.is_some_and(|port| {
        std::net::TcpStream::connect_timeout(
            &std::net::SocketAddr::from(([127, 0, 0, 1], port)),
            Duration::from_millis(100),
        )
        .is_ok()
    });
    let db = open(&dir.join("otel.db"))?;
    let mut rows = 0i64;
    let mut total = 0i64;
    let mut latest: Option<String> = None;
    let mut events: Option<i64> = None;
    let mut covered = BTreeSet::new();
    let since = (now - chrono::Duration::hours(1)).to_rfc3339();
    if let Some(conn) = &db {
        (total, rows, latest) = conn.query_row(
            "SELECT COUNT(*), COALESCE(SUM(julianday(ts)>=julianday(?1) AND julianday(ts)<=julianday(?2)),0), MAX(ts) FROM api_requests",
            [&since, &observed], |r| Ok((r.get(0)?,r.get(1)?,r.get(2)?)),
        ).map_err(|error| format!("request cost schema unreadable: {error}"))?;
        let mut stmt = conn.prepare("SELECT DISTINCT session_id FROM api_requests WHERE julianday(ts)>=julianday(?1) AND julianday(ts)<=julianday(?2)")
            .map_err(|error| error.to_string())?;
        let sessions = stmt
            .query_map([&since, &observed], |r| r.get::<_, String>(0))
            .map_err(|error| error.to_string())?;
        for session in sessions {
            covered.insert(session.map_err(|error| error.to_string())?);
        }
        let raw_exists: bool = conn.query_row("SELECT EXISTS(SELECT 1 FROM sqlite_master WHERE type='table' AND name='otel_events')", [], |r| r.get(0))
            .map_err(|error| error.to_string())?;
        if raw_exists {
            events = Some(conn.query_row("SELECT COUNT(*) FROM otel_events WHERE julianday(ts)>=julianday(?1) AND julianday(ts)<=julianday(?2)", [&since, &observed], |r| r.get(0))
                .map_err(|error| error.to_string())?);
        }
    }
    let uncovered: Vec<_> = live.difference(&covered).cloned().collect();
    let status = if db.is_none() {
        "missing"
    } else if !listening {
        "offline"
    } else if unknown > 0 {
        "unknown_workers"
    } else if rows == 0 && !live.is_empty() {
        "zero_rows"
    } else if !uncovered.is_empty() {
        "uncovered_workers"
    } else if live.is_empty() {
        "idle"
    } else {
        "healthy"
    };
    Ok(
        json!({"status":status, "observed_at":observed, "window_seconds":3600,
        "database":if db.is_some(){"present"}else{"missing"}, "rows_last_hour":rows,
        "api_requests_total":total, "events_last_hour":events, "latest_request_at":latest,
        "live_claude_workers":live.len(), "unknown_claude_workers":unknown,
        "uncovered_sessions":uncovered, "receiver_port":port, "receiver_listening":listening}),
    )
}

pub fn health_line(value: &Value) -> String {
    if value.get("status").and_then(Value::as_str) == Some("off") {
        return "telemetry: off".to_string();
    }
    let rows = value
        .get("rows_last_hour")
        .and_then(Value::as_i64)
        .unwrap_or(0);
    let live = value
        .get("live_claude_workers")
        .and_then(Value::as_u64)
        .unwrap_or(0);
    let unknown = value
        .get("unknown_claude_workers")
        .and_then(Value::as_u64)
        .unwrap_or(0);
    let uncovered = value
        .get("uncovered_sessions")
        .and_then(Value::as_array)
        .map_or(0, Vec::len);
    let status = value
        .get("status")
        .and_then(Value::as_str)
        .unwrap_or("unknown");
    let recovery = if matches!(status, "missing" | "zero_rows" | "uncovered_workers") {
        "; check the receiver and restart an uninstrumented supervisor after its hosted sessions finish"
    } else {
        ""
    };
    format!("telemetry: {rows} API rows in the last hour, {live} live Claude workers, {uncovered} uncovered, {unknown} unknown ({status}){recovery}")
}

fn csv_cell(value: &str) -> String {
    if value.chars().any(|c| matches!(c, ',' | '"' | '\r' | '\n')) {
        format!("\"{}\"", value.replace('"', "\"\""))
    } else {
        value.to_string()
    }
}

fn micros_text(micros: i64) -> String {
    let absolute = micros.unsigned_abs();
    format!(
        "{}{}.{:06}",
        if micros < 0 { "-" } else { "" },
        absolute / 1_000_000,
        absolute % 1_000_000
    )
}

pub fn export_csv(db: &Path) -> Result<(String, usize), String> {
    let mut output = "day,session_id,model,skill_name,requests,unpriced_requests,cost_usd,input_tokens,output_tokens,cache_read_tokens,cache_creation_tokens\n".to_string();
    let Some(conn) = open(db)? else {
        return Ok((output, 0));
    };
    let mut stmt = conn.prepare("SELECT COALESCE(date(ts),''),session_id,COALESCE(model,''),COALESCE(skill_name,''),COUNT(*),COUNT(*)-COUNT(cost_usd_micros),SUM(cost_usd_micros),SUM(input_tokens),SUM(output_tokens),SUM(cache_read_tokens),SUM(cache_creation_tokens) FROM api_requests GROUP BY 1,2,3,4 ORDER BY 1,2,3,4")
        .map_err(|error| format!("cannot export request costs: {error}"))?;
    let rows = stmt
        .query_map([], |r| {
            let mut fields: Vec<String> = (0..4)
                .map(|i| r.get::<_, String>(i))
                .collect::<rusqlite::Result<_>>()?;
            fields.push(r.get::<_, i64>(4)?.to_string());
            fields.push(r.get::<_, i64>(5)?.to_string());
            fields.push(
                r.get::<_, Option<i64>>(6)?
                    .map(micros_text)
                    .unwrap_or_default(),
            );
            for i in 7..11 {
                fields.push(
                    r.get::<_, Option<i64>>(i)?
                        .map(|v| v.to_string())
                        .unwrap_or_default(),
                );
            }
            Ok(fields)
        })
        .map_err(|error| error.to_string())?;
    let mut count = 0;
    for row in rows {
        let row = row.map_err(|error| error.to_string())?;
        output.push_str(
            &row.iter()
                .map(|s| csv_cell(s))
                .collect::<Vec<_>>()
                .join(","),
        );
        output.push('\n');
        count += 1;
    }
    Ok((output, count))
}
