// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/provider_key.rs. Do not edit.
//! Provider API-key resolution: the env var named by `api_key_env`, else the
//! same name read from the `api_key_file` dotenv file.
//!
//! The one key rule both crates need (the codex route resolver and the mux
//! composer's launch check). `crates/fno/src/provider_key.rs` is a generated
//! copy of this file, so the two crates cannot drift; `crates/fno` does not
//! depend on `fno-agents` (independent crates.io publishes).

use std::path::{Path, PathBuf};

/// Key precedence (twin of `_resolve_key`, `model_routing.py`): the env var
/// named by `api_key_env` wins over the same name read from the
/// `api_key_file` dotenv file. Never returns the empty string.
pub fn resolve_key(key_env: &str, api_key_file: Option<&str>) -> Option<String> {
    if key_env.is_empty() {
        return None;
    }
    if let Ok(from_env) = std::env::var(key_env) {
        if !from_env.is_empty() {
            return Some(from_env);
        }
    }
    api_key_file.and_then(|file| read_var_from_env_file(file, key_env))
}

/// Whether a key resolves, without exposing it: the composer's launch check
/// and any other presence-only caller read through here.
pub fn key_present(key_env: &str, api_key_file: Option<&str>) -> bool {
    resolve_key(key_env, api_key_file).is_some()
}

/// Port of Python's `read_var_from_env_file` (`cli/src/fno/env_file.py`):
/// skip `#` lines, allow an `export ` prefix, trim, strip the quotes Python's
/// `str.strip` would strip. A missing file or key is None, never fatal.
fn read_var_from_env_file(path_str: &str, key_name: &str) -> Option<String> {
    let path = expand_tilde(path_str)?;
    let text = std::fs::read_to_string(path).ok()?;
    for line in text.lines() {
        let line = line.trim();
        if line.starts_with('#') {
            continue;
        }
        let line = line.strip_prefix("export ").unwrap_or(line).trim();
        let Some((name, value)) = line.split_once('=') else {
            continue;
        };
        if name.trim() == key_name {
            let v = py_strip(value.trim(), '"');
            let v = py_strip(v, '\'');
            return if v.is_empty() {
                None
            } else {
                Some(v.to_string())
            };
        }
    }
    None
}

/// `str.strip(char)`: repeatedly drop the quote from both ends.
fn py_strip(s: &str, quote: char) -> &str {
    let mut s = s;
    while let Some(rest) = s.strip_prefix(quote) {
        s = rest;
    }
    while let Some(rest) = s.strip_suffix(quote) {
        s = rest;
    }
    s
}

fn expand_tilde(path_str: &str) -> Option<PathBuf> {
    if path_str == "~" {
        return std::env::var_os("HOME").map(PathBuf::from);
    }
    match path_str.strip_prefix("~/") {
        Some(rest) => std::env::var_os("HOME").map(|home| Path::new(&home).join(rest)),
        None => Some(PathBuf::from(path_str)),
    }
}
