// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/registry_read.rs. Do not edit.
//! The one read-only door to the agents registry for code that cannot link
//! the registry store. Before the table import `registry.json` is the file;
//! after it, the path is a fence directory and the rows live in graph.db.

use serde_json::Value;
use std::path::{Path, PathBuf};

/// The graph.db that holds the registry table for the registry at `path`.
pub fn database_path(path: &Path) -> Option<PathBuf> {
    let home = path.parent()?;
    let root = if home.file_name().is_some_and(|name| name == "agents") {
        home.parent()?
    } else {
        home
    };
    Some(crate::state_layout::place(root, "graph.json").with_extension("db"))
}

/// The registry document at `path` as JSON text. A missing path is
/// `NotFound`, exactly as the legacy file read was.
pub fn registry_text(path: &Path) -> std::io::Result<String> {
    if !path.is_dir() {
        return std::fs::read_to_string(path);
    }
    let invalid = |e: String| std::io::Error::new(std::io::ErrorKind::InvalidData, e);
    let database = database_path(path).ok_or_else(|| invalid("registry has no parent".into()))?;
    let connection = crate::store_conn::open_read(&database).map_err(invalid)?;
    let raw: String = connection
        .query_row(
            "SELECT value FROM registry_meta WHERE key='document'",
            [],
            |r| r.get(0),
        )
        .map_err(|e| invalid(e.to_string()))?;
    let mut document: Value = serde_json::from_str(&raw).map_err(|e| invalid(e.to_string()))?;
    let mut statement = connection
        .prepare("SELECT payload FROM registry ORDER BY ordinal")
        .map_err(|e| invalid(e.to_string()))?;
    let rows = statement
        .query_map([], |r| r.get::<_, String>(0))
        .map_err(|e| invalid(e.to_string()))?;
    let mut agents = Vec::new();
    for row in rows {
        let row = row.map_err(|e| invalid(e.to_string()))?;
        agents.push(serde_json::from_str::<Value>(&row).map_err(|e| invalid(e.to_string()))?);
    }
    document
        .as_object_mut()
        .ok_or_else(|| invalid("registry metadata is not an object".into()))?
        .insert("agents".into(), Value::Array(agents));
    Ok(document.to_string())
}
