// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/registry_read.rs. Do not edit.
//! The one read-only door to the agents registry for code that cannot link
//! the registry store. Before the table import `registry.json` is the file;
//! after it, the path is a fence directory and the rows live in graph.db.

use serde_json::Value;
use std::path::{Path, PathBuf};

/// The graph.db that holds the registry table for the registry at `path`.
pub fn database_path(path: &Path) -> Option<PathBuf> {
    let home = path.parent()?;
    let root = if home.file_name().is_some_and(|name| name == "agents") {
        home.parent()?
    } else {
        home
    };
    Some(crate::state_layout::place(root, "graph.json").with_extension("db"))
}

/// Whether the registry table owns `path`: the fence directory stands there,
/// or graph.db records the import. A plain `registry.json` beside an imported
/// table is a stale pre-import file, never the registry: rm edits the table,
/// so reading that file brings removed rows back. A store that exists but
/// cannot be read counts as owned, so the read fails instead of falling back
/// to the file.
pub fn table_owns(path: &Path) -> bool {
    if path.is_dir() {
        return true;
    }
    if path.file_name().is_none_or(|name| name != "registry.json") {
        return false;
    }
    let Some(database) = database_path(path) else {
        return false;
    };
    if !database.exists() {
        return false;
    }
    let Ok(connection) = crate::store_conn::open_read(&database) else {
        return true;
    };
    let has_meta = connection.query_row(
        "SELECT EXISTS(SELECT 1 FROM sqlite_master WHERE type='table' AND name='registry_meta')",
        [],
        |r| r.get::<_, bool>(0),
    );
    match has_meta {
        Ok(false) => false,
        Ok(true) => connection
            .query_row(
                "SELECT EXISTS(SELECT 1 FROM registry_meta WHERE key='imported')",
                [],
                |r| r.get::<_, bool>(0),
            )
            .unwrap_or(true),
        Err(_) => true,
    }
}

/// The registry document at `path` as JSON text. Before the import a missing
/// path is `NotFound`, exactly as the legacy file read was.
pub fn registry_text(path: &Path) -> std::io::Result<String> {
    if !table_owns(path) {
        return std::fs::read_to_string(path);
    }
    let invalid = |e: String| std::io::Error::new(std::io::ErrorKind::InvalidData, e);
    let database = database_path(path).ok_or_else(|| invalid("registry has no parent".into()))?;
    let connection = crate::store_conn::open_read(&database).map_err(invalid)?;
    let raw: String = connection
        .query_row(
            "SELECT value FROM registry_meta WHERE key='document'",
            [],
            |r| r.get(0),
        )
        .map_err(|e| invalid(e.to_string()))?;
    let mut document: Value = serde_json::from_str(&raw).map_err(|e| invalid(e.to_string()))?;
    let mut statement = connection
        .prepare("SELECT payload FROM registry ORDER BY ordinal")
        .map_err(|e| invalid(e.to_string()))?;
    let rows = statement
        .query_map([], |r| r.get::<_, String>(0))
        .map_err(|e| invalid(e.to_string()))?;
    let mut agents = Vec::new();
    for row in rows {
        let row = row.map_err(|e| invalid(e.to_string()))?;
        agents.push(serde_json::from_str::<Value>(&row).map_err(|e| invalid(e.to_string()))?);
    }
    crate::role_migration::upgrade_registry_rows(&mut agents);
    document
        .as_object_mut()
        .ok_or_else(|| invalid("registry metadata is not an object".into()))?
        .insert("agents".into(), Value::Array(agents));
    Ok(document.to_string())
}
