// @generated by crates/fno-agents/build.rs from crates/fno-agents/src/role_migration.rs. Do not edit.
//! Upgrade stored role vocabulary before any runtime reader opens it.
//! This is the sole compatibility boundary; normal readers use only current keys.

use serde_json::Value;
use std::collections::{BTreeMap, BTreeSet};
use std::fs::OpenOptions;
use std::io::Write;
use std::path::{Path, PathBuf};

const WORDS: &[(&str, &str)] = &[
    ("king", "lead"),
    ("kings", "leads"),
    ("crown", "role"),
    ("crowns", "roles"),
    ("crowned", "promoted"),
    ("crowning", "promoting"),
    ("uncrowned", "unpromoted"),
    ("crownless", "unassigned"),
    ("heir", "successor"),
    ("heirs", "successors"),
    ("court", "team"),
    ("courts", "teams"),
    ("reign", "term"),
    ("reigns", "terms"),
    ("reigning", "serving"),
    ("regnal", "generation"),
    ("coronation", "promotion"),
    ("coronations", "promotions"),
    ("coronate", "promote"),
    ("coronated", "promoted"),
    ("coronating", "promoting"),
    ("abdicate", "step_down"),
    ("abdicates", "steps_down"),
    ("abdicated", "stepped_down"),
    ("abdicating", "stepping_down"),
    ("abdication", "departure"),
    ("bestow", "grant"),
    ("bestowed", "granted"),
    ("bestows", "grants"),
    ("bestowing", "granting"),
    ("abdicat", "step_down"),
];

fn vocabulary(text: &str) -> String {
    static PATTERN: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
    let re = PATTERN.get_or_init(|| regex::Regex::new(r"[A-Za-z]+").expect("constant pattern"));
    let replaced = re
        .replace_all(text, |cap: &regex::Captures<'_>| {
            let word = &cap[0];
            let Some((_, new)) = WORDS
                .iter()
                .find(|(old, _)| *old == word.to_ascii_lowercase())
            else {
                return word.to_string();
            };
            if word.bytes().all(|b| b.is_ascii_uppercase()) {
                new.to_ascii_uppercase()
            } else if word.as_bytes()[0].is_ascii_uppercase() {
                let mut shown = new.to_string();
                shown[..1].make_ascii_uppercase();
                shown
            } else {
                new.to_string()
            }
        })
        .into_owned();
    replaced
        .replace("term_armed", "lead_armed")
        .replace("term_checkin", "lead_checkin")
        .replace("term_dispatch_exception", "lead_dispatch_exception")
        .replace("role_succession_reverted", "team_succession_reverted")
        .replace("role_ledger", "team_ledger")
        .replace("term_eval", "lead_eval")
        .replace("fno agents lead", "fno agents org")
}

#[doc(hidden)]
pub fn migrate_node_provenance(value: &mut Value) -> Result<bool, String> {
    let Some(map) = value.as_object_mut() else {
        return Ok(false);
    };
    let Some(legacy) = map.remove("source_crown") else {
        return Ok(false);
    };
    if let Some(current) = map.get("source_team") {
        if current != &legacy {
            return Err("conflicting source_team provenance; migration refused".into());
        }
    } else {
        map.insert("source_team".into(), legacy);
    }
    Ok(true)
}

fn migrate_value(value: &mut Value, field: &str) -> Result<(), String> {
    match value {
        Value::Object(map) => {
            let old = std::mem::take(map);
            for (key, mut value) in old {
                let new = vocabulary(&key);
                migrate_value(&mut value, &new)?;
                if let Some(existing) = map.get(&new) {
                    if existing != &value {
                        return Err(format!(
                            "conflicting stored fields for {new}; migration refused"
                        ));
                    }
                } else {
                    map.insert(new, value);
                }
            }
            let sorted = std::mem::take(map).into_iter().collect::<BTreeMap<_, _>>();
            map.extend(sorted);
        }
        Value::Array(items) => {
            for item in items {
                migrate_value(item, field)?;
            }
        }
        Value::String(text)
            if matches!(
                field,
                "type"
                    | "event"
                    | "arm"
                    | "lane"
                    | "driver"
                    | "kind"
                    | "phase"
                    | "reason"
                    | "checkin_text"
                    | "manifest_path"
                    | "state_path"
                    | "cancel_path"
            ) =>
        {
            *text = vocabulary(text)
        }
        _ => (),
    }
    Ok(())
}

fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let temporary = path.with_extension(format!("role-upgrade-{}.tmp", std::process::id()));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        if let Ok(meta) = std::fs::metadata(path) {
            file.set_permissions(meta.permissions())?;
        }
        file.write_all(bytes)?;
        file.sync_all()?;
        std::fs::rename(&temporary, path)
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(&temporary);
    }
    result.map_err(|e: std::io::Error| format!("{}: {e}", path.display()))
}

fn migrate_file(path: &Path) -> Result<(), String> {
    let mut lock_path = path.as_os_str().to_os_string();
    lock_path.push(".lock");
    let sidecar = if path.file_name().and_then(|s| s.to_str()) == Some("registry.json") {
        let dir = path
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join("locks");
        std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
        dir.join("_registry.lock")
    } else {
        PathBuf::from(lock_path)
    };
    let lock = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(sidecar)
        .map_err(|e| e.to_string())?;
    lock.lock().map_err(|e| e.to_string())?;
    let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let extension = if path
        .file_name()
        .and_then(|s| s.to_str())
        .is_some_and(|s| s.starts_with("events.jsonl"))
    {
        "jsonl"
    } else {
        path.extension().and_then(|s| s.to_str()).unwrap_or("")
    };
    let output = match extension {
        "json" => {
            let mut value: Value =
                serde_json::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
            if value.get("agents").is_some()
                && value
                    .get("schema_version")
                    .and_then(Value::as_u64)
                    .is_some_and(|v| v > 40)
            {
                return Ok(());
            }
            let original = value.clone();
            migrate_value(&mut value, "")?;
            if path.file_name().and_then(|n| n.to_str()) == Some("registry.json") {
                if let Some(map) = value.as_object_mut() {
                    if map.contains_key("agents") && map.contains_key("schema_version") {
                        let floor = map
                            .get("min_writer_version")
                            .and_then(Value::as_u64)
                            .unwrap_or(0);
                        map.insert("schema_version".into(), Value::from(40));
                        map.insert("min_writer_version".into(), Value::from(floor.max(40)));
                    }
                }
            }
            if value == original {
                return Ok(());
            }
            serde_json::to_string_pretty(&value).map_err(|e| e.to_string())? + "\n"
        }
        "jsonl" => {
            let mut out = String::new();
            for line in text.split_inclusive('\n') {
                let Ok(mut value) = serde_json::from_str::<Value>(line) else {
                    out.push_str(line);
                    continue;
                };
                let original = value.clone();
                migrate_value(&mut value, "")?;
                if value == original {
                    out.push_str(line);
                } else {
                    out.push_str(&serde_json::to_string(&value).map_err(|e| e.to_string())?);
                    if line.ends_with('\n') {
                        out.push('\n');
                    }
                }
            }
            out
        }
        "toml" => {
            let document: toml::Value =
                toml::from_str(&text).map_err(|e| format!("{}: {e}", path.display()))?;
            let mut value = serde_json::to_value(document).map_err(|e| e.to_string())?;
            let original = value.clone();
            migrate_value(&mut value, "")?;
            if value == original {
                return Ok(());
            }
            let document: toml::Value = serde_json::from_value(value).map_err(|e| e.to_string())?;
            toml::to_string_pretty(&document).map_err(|e| e.to_string())?
        }
        "md" => {
            text.lines()
                .map(|line| {
                    if let Some((key, rest)) = line.split_once(':') {
                        if !key.is_empty()
                            && key.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
                        {
                            return format!("{}:{rest}", vocabulary(key));
                        }
                    }
                    line.to_string()
                })
                .collect::<Vec<_>>()
                .join("\n")
                + "\n"
        }
        _ => return Ok(()),
    };
    if output != text {
        atomic_write(path, output.as_bytes())?;
    }
    Ok(())
}

fn selected(path: &Path) -> bool {
    let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
    matches!(
        name,
        "events.db"
            | "registry.json"
            | "team_names.json"
            | "crown_names.json"
            | "events.jsonl"
            | "config.toml"
    ) || ((name.starts_with("lead-") || name.starts_with("king-") || name.starts_with("reign-"))
        && matches!(
            path.extension().and_then(|s| s.to_str()),
            Some("json" | "jsonl" | "md")
        ))
}

fn walk(root: &Path, depth: usize) -> Result<(), String> {
    if depth > 8 {
        return Ok(());
    }
    for entry in std::fs::read_dir(root).map_err(|e| format!("{}: {e}", root.display()))? {
        let entry = entry.map_err(|e| e.to_string())?;
        let path = entry.path();
        let kind = entry.file_type().map_err(|e| e.to_string())?;
        if kind.is_symlink() {
            continue;
        }
        if kind.is_dir() {
            let name = entry.file_name().to_string_lossy().to_string();
            let parent_is_container = root.file_name().and_then(|s| s.to_str()).is_some_and(|s| {
                matches!(
                    s,
                    "spaces" | "worktrees" | "king" | "lead" | "kings" | "leads"
                )
            });
            if parent_is_container
                || matches!(
                    name.as_str(),
                    "agents"
                        | "spaces"
                        | "worktrees"
                        | "king"
                        | "lead"
                        | "kings"
                        | "leads"
                        | "events"
                        | "state"
                )
            {
                walk(&path, depth + 1)?;
                let current = vocabulary(&name);
                if current != name {
                    let target = path.with_file_name(current);
                    if target.exists() {
                        return Err(format!(
                            "both role directories exist at {}; migration refused",
                            path.display()
                        ));
                    }
                    std::fs::rename(&path, target).map_err(|e| e.to_string())?;
                }
            }
        } else if kind.is_file() && selected(&path) {
            if path.file_name().and_then(|s| s.to_str()) == Some("events.db") {
                crate::event_store::upgrade_role_store(&path)?;
            } else {
                migrate_file(&path)?;
            }
            let name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            let current = if name == "crown_names.json" {
                "team_names.json".to_string()
            } else {
                vocabulary(name)
            };
            if current != name {
                let target = path.with_file_name(current);
                if target.exists() {
                    return Err(format!(
                        "both role files exist at {}; migration refused",
                        path.display()
                    ));
                }
                std::fs::rename(&path, target).map_err(|e| e.to_string())?;
            }
        }
    }
    Ok(())
}

pub fn run_at(root: &Path) -> Result<(), String> {
    if !root.is_dir() {
        return Ok(());
    }
    let marker = root.join("migrations/role-vocabulary-v1.done");
    if marker.exists() {
        return Ok(());
    }
    crate::live_store_fence::refuse_worktree_build_on_operator_store(root)?;
    std::fs::create_dir_all(marker.parent().expect("marker has parent"))
        .map_err(|e| e.to_string())?;
    let lock = OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(false)
        .open(marker.with_extension("lock"))
        .map_err(|e| e.to_string())?;
    lock.lock().map_err(|e| e.to_string())?;
    if marker.exists() {
        return Ok(());
    }
    walk(root, 0)?;
    atomic_write(&marker, b"1\n")
}

pub fn run() -> Result<(), String> {
    let mut roots = BTreeSet::new();
    for key in ["FNO_STATE_DIR", "FNO_AGENTS_HOME", "FNO_SPACES_DIR"] {
        if let Some(path) = std::env::var_os(key).filter(|s| !s.is_empty()) {
            roots.insert(PathBuf::from(path));
        }
    }
    let explicit_roots = !roots.is_empty();
    if !explicit_roots {
        if let Some(root) = crate::live_store_fence::operator_state_root() {
            roots.insert(root);
        }
    }
    if let Some(config) = std::env::var_os("FNO_CONFIG").filter(|s| !s.is_empty()) {
        let config = PathBuf::from(config);
        if config.is_file() {
            crate::live_store_fence::refuse_worktree_build_on_operator_store(&config)?;
            migrate_file(&config)?;
        }
    }
    if !explicit_roots {
        if let Ok(cwd) = std::env::current_dir() {
            roots.insert(cwd.join(".fno"));
        }
    }
    for root in roots {
        run_at(&root)?;
    }
    Ok(())
}

pub fn upgrade_event_store(conn: &mut rusqlite::Connection) -> Result<(), String> {
    use sha2::Digest;
    let ready: bool = conn
        .query_row(
            "SELECT EXISTS(SELECT 1 FROM events_meta WHERE key = 'role_vocabulary_v1')",
            [],
            |row| row.get(0),
        )
        .map_err(|e| e.to_string())?;
    if ready {
        return Ok(());
    }
    let tx = conn
        .transaction_with_behavior(rusqlite::TransactionBehavior::Immediate)
        .map_err(|e| e.to_string())?;
    let done: bool = tx
        .query_row(
            "SELECT EXISTS(SELECT 1 FROM events_meta WHERE key = 'role_vocabulary_v1')",
            [],
            |row| row.get(0),
        )
        .map_err(|e| e.to_string())?;
    if done {
        return Ok(());
    }
    let rows = {
        let mut query = tx
            .prepare("SELECT seq, type, line FROM events")
            .map_err(|e| e.to_string())?;
        let rows = query
            .query_map([], |row| {
                Ok((
                    row.get::<_, i64>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, String>(2)?,
                ))
            })
            .map_err(|e| e.to_string())?;
        rows.collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())?
    };
    for (seq, event_type, line) in rows {
        let current_type = vocabulary(&event_type);
        let current_line = match serde_json::from_str::<Value>(&line) {
            Ok(mut value) => {
                let original = value.clone();
                migrate_value(&mut value, "")?;
                if value != original {
                    serde_json::to_string(&value).map_err(|e| e.to_string())?
                } else {
                    line.clone()
                }
            }
            Err(_) => line.clone(),
        };
        if current_type != event_type || current_line != line {
            let hash = sha2::Sha256::digest(current_line.as_bytes()).to_vec();
            tx.execute(
                "UPDATE events SET type = ?1, line = ?2, row_hash = CASE WHEN EXISTS(SELECT 1 FROM events other WHERE other.row_hash = ?3 AND other.seq <> ?4) THEN row_hash ELSE ?3 END WHERE seq = ?4",
                rusqlite::params![current_type, current_line, hash, seq],
            )
            .map_err(|e| e.to_string())?;
        }
    }
    tx.execute(
        "INSERT INTO events_meta(key, value) VALUES ('role_vocabulary_v1', '1')",
        [],
    )
    .map_err(|e| e.to_string())?;
    tx.commit().map_err(|e| e.to_string())
}

pub fn contains_legacy_vocabulary(text: &str) -> bool {
    text.split(|c: char| !c.is_ascii_alphabetic())
        .any(|word| WORDS.iter().any(|(old, _)| word.eq_ignore_ascii_case(old)))
}

pub fn retired_verb(verb: &str) -> Option<&'static str> {
    match verb {
        "king" => Some("fno agents org <action>"),
        "king-checkin" => Some("fno agents org checkin"),
        "king-history" => Some("fno agents org history"),
        "crown" => Some("fno agents org promote <session> --scope <scope>"),
        "court" => Some("fno agents org"),
        "court-fold" => Some("fno agents org fold"),
        "court-orphans" => Some("fno agents org vacancies"),
        "reign-ledger" => Some("fno agents org rundown"),
        _ => None,
    }
}
