#!/usr/bin/env bash
# handoff-generator.sh - auto-generate a minimal HANDOFF.md from
# target-state.md + STATE.md when the LLM didn't write one.
#
# Lifted from hooks/target-stop-hook.sh (Phase 1 of stop-hook refactor).
# Behavior is identical to the inline definition.
#
# Requires (set by caller):
#   REPO_ROOT - project repo root (current working tree)
#   log()     - logging function from the hook

# _generate_handoff STATE_FILE OUTPUT_FILE
#   Extracts status, cost, PR URL, incomplete tasks, and Learnings section into
#   a single human-readable markdown file.
_generate_handoff() {
    local state_file="$1"
    local output_file="$2"

    local title status cost pr_number pr_url
    # Strip both single and double quotes from each field. YAML accepts
    # either style; the previous code only handled bare values or
    # double-quoted strings for title/pr_url and left status, cost,
    # pr_number raw. cost is read from total_cost_usd first (the current
    # stop-hook writer's field name) and falls back to total_cost for
    # state files written before the rename. Same fallback pattern as
    # the hook's own budget-cap reader.
    title=$(sed -n 's/^input:[[:space:]]*//p' "$state_file" | head -1 | tr -d '"' | tr -d "'")
    status=$(sed -n 's/^status:[[:space:]]*//p' "$state_file" | head -1 | tr -d '"' | tr -d "'")
    cost=$(sed -n 's/^total_cost_usd:[[:space:]]*//p' "$state_file" | head -1 | tr -d '"' | tr -d "'")
    [[ -z "$cost" ]] && cost=$(sed -n 's/^total_cost:[[:space:]]*//p' "$state_file" | head -1 | tr -d '"' | tr -d "'")
    pr_number=$(sed -n 's/^[[:space:]]*pr_number:[[:space:]]*//p' "$state_file" | head -1 | tr -d '"' | tr -d "'")
    pr_url=$(sed -n 's/^[[:space:]]*pr_url:[[:space:]]*//p' "$state_file" | head -1 | tr -d '"' | tr -d "'")

    {
        echo "# Handoff: ${title:-Untitled}"
        echo ""
        echo "**Status:** ${status:-UNKNOWN}"
        [ -n "$cost" ] && echo "**Cost:** \$${cost}"
        [ -n "$pr_url" ] && echo "**PR:** [#${pr_number}](${pr_url})"
        echo "**Generated:** $(date -u +%Y-%m-%dT%H:%M:%SZ) (auto-generated by stop hook)"
        echo ""

        # (Post-wedge ab-d0337fbc/ab-88f0854d: the "Skipped phases" block was
        # removed - the immutable manifest no longer writes *_passed/docs_generated
        # gate fields, so those greps could never match.)

        # Incomplete tasks from STATE.md
        if [ -f "$REPO_ROOT/.fno/STATE.md" ]; then
            local incomplete
            incomplete=$(grep '^\- \[ \]' "$REPO_ROOT/.fno/STATE.md" 2>/dev/null)
            if [ -n "$incomplete" ]; then
                echo "## Incomplete Tasks"
                echo ""
                echo "$incomplete"
                echo ""
            fi
        fi

        # Learnings section from target-state (if present)
        if grep -q "^## Learnings" "$state_file" 2>/dev/null; then
            sed -n '/^## Learnings/,/^## /p' "$state_file" | sed '$ d'
            echo ""
        fi

    } > "$output_file" 2>/dev/null

    log "Generated HANDOFF.md from state files"
}
