#!/usr/bin/env bash
# AUTO-GENERATED by `fno paths emit-shell`. Do not hand-edit.
# Regenerate after any change to settings.yaml or the schema:
#   cd cli && uv run fno-py paths emit-shell --output ../scripts/lib/paths.sh

# Self-set REPO_ROOT if unset so this file is safe to source under set -u.
# Callers may still pre-set REPO_ROOT before sourcing to pin the value.
REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
HOME="${HOME:-$(getent passwd "$(id -un)" 2>/dev/null | cut -d: -f6 || echo ~)}"

export STATE_DIR="$HOME/.fno"
export GRAPH_JSON_PATH="$STATE_DIR/graph.json"
export LEDGER_JSON_PATH="$STATE_DIR/ledger.json"
export BRIEFS_DIR="$STATE_DIR/briefs"
export FLEET_DIR="$STATE_DIR/fleet"
export POSTMORTEMS_DIR="$STATE_DIR/postmortems"
export WORKTREES_BASE="$STATE_DIR/worktrees"
export MEMORY_DIR="$STATE_DIR/memory"
export HOOK_LOGS_DIR="$STATE_DIR/hook-logs"
export PLANS_DIR="$REPO_ROOT/.fno/plans"
export INBOX_DIR="$REPO_ROOT/.fno/inbox"
export HANDOFFS_DIR="$STATE_DIR/handoffs/$(basename "$REPO_ROOT")"
export CONFIG_FILE="$STATE_DIR/settings.yaml"

paths_plan_file() {
  local name="$1"
  echo "${PLANS_DIR}/${name}"
}

paths_inbox_thread() {
  local thread="$1"
  echo "${INBOX_DIR}/${thread}"
}
