"""Render the features capability matrix from the capability table (x-a3e8).

GENERATE the copy; never hand-edit it. The rendered file is
``docs/harnesses/capability-matrix.md``, gated by
``scripts/ci/check-harness-capability-matrix-fresh.sh`` - the gate is the
tripwire for a hand edit, not the sync step (the x-47b3 ruling on generated
docs). One row per supported harness, the FULL roster, so a roster entry
with no capability row (hermes, openclaw today) renders as visible
all-unmeasured gaps instead of vanishing. One column per feature key,
sourced from the table's own feature probe declarations, so a key added
there appears here with no code edit.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

from fno.harness_names import KNOWN_HARNESSES

_MATRIX_REL = Path("docs/harnesses/capability-matrix.md")
_PACKAGED_TABLE = Path(__file__).parent / "agents" / "harness_capabilities.toml"

_HEADER = """\
<!-- GENERATED by `fno doctor harness-matrix --write`. DO NOT EDIT.
     A hand edit trips scripts/ci/check-harness-capability-matrix-fresh.sh;
     regenerate from crates/fno-agents/src/harness_capabilities.toml. -->
# Harness capability matrix (features)

What each harness can DO, rendered from the capability table
(`map_version {version}`). One row per supported harness - including roster
entries with no capability row, which read unmeasured everywhere - and one
column per feature key.

| State | Meaning |
|---|---|
| `native` | the harness exposes it and fno drives it; a wired lane exists |
| `capable` | the harness exposes it and fno has no wired arm |
| `absent` | measured not to exist on this harness |
| `unmeasured` | nobody has looked |

Every non-native cell settles the same way: `fno agents harness probe
<harness>` runs the instrument the table declares for that key. The
pane-driving mechanics are a different dimension and live in the capability
table itself, never here.
"""


def _feature_keys(table: dict) -> list[str]:
    """The column set: the table's own feature probe declarations. Closed
    on the table side; a declared key with no rendered column would be a
    dimension the doc hides."""
    return sorted(
        field[len("features."):]
        for field in table.get("probe", {})
        if field.startswith("features.")
    )


def _cell(row: dict, key: str) -> str:
    claim = row.get("features") or {}
    if not isinstance(claim, dict):
        return "unmeasured"
    return str(claim.get(key, {}).get("state", "unmeasured"))


def render_matrix(table_path: Path | None = None) -> str:
    """Render the matrix from one capability table. ``table_path`` is the
    canonical TOML (the gate passes the COMMITTED blob so a stale matrix is
    caught against the bytes that would ship); the packaged copy is the
    default for the verb's stdout mode."""
    path = table_path or _PACKAGED_TABLE
    with path.open("rb") as handle:
        table = tomllib.load(handle)
    harness_rows = table.get("harness", {})
    keys = _feature_keys(table)
    lines = [
        _HEADER.format(version=table.get("map_version", "?")),
        "",
        "| harness | " + " | ".join(keys) + " |",
        "|---" * (len(keys) + 1) + "|",
    ]
    for name in KNOWN_HARNESSES:
        row = harness_rows.get(name) or {}
        cells = " | ".join(f"`{_cell(row, key)}`" for key in keys)
        lines.append(f"| {name} | {cells} |")
    lines.append("")
    return "\n".join(lines)


def _repo_root() -> Path:
    import subprocess

    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True
    )
    if result.returncode != 0:
        raise SystemExit(
            "harness-matrix: not in a git checkout; --write has nowhere to "
            "write. Run from a repo root."
        )
    return Path(result.stdout.strip())


def main(argv: list[str] | None = None) -> int:
    write = "--write" in (argv if argv is not None else sys.argv[1:])
    table_arg: Path | None = None
    args = sys.argv[1:] if argv is None else argv
    if "--table" in args:
        table_arg = Path(args[args.index("--table") + 1])
    rendered = render_matrix(table_arg)
    if write:
        target = _repo_root() / _MATRIX_REL
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
        print(f"harness capability matrix written to {_MATRIX_REL}")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
