"""Detective attribution check for replay-run isolation.

Resurrected verbatim from ``cli/src/fno/evals/isolation.py`` (cut in
``675b24e``); the observer harness (x-57a5, Locked Decision 5) reuses its
proven preventive+detective isolation mechanics, not the golden-fixture eval
concept it was part of. "eval run" below reads as "replay run".

Scans real operator state files for replay session ids that should never
appear there.  If any replay session id is found in a real-state surface,
the run has violated isolation.

Public API
----------
``collect_eval_session_ids(workdir, *, claude_projects_dir)``
    Gather every session id attributable to an eval run from three sources:
    - the workdir ``target-state.md`` manifest (``session_id:`` frontmatter)
    - the workdir ``.fno/events.jsonl`` (any ``session_id`` field)
    - transcript ``.jsonl`` files under
      ``<claude_projects_dir>/<encoded-workdir>/``
    Returns ``(ids: set[str], transcript_path: str | None)`` where
    ``transcript_path`` is the first transcript file found (fills the
    history row's ``transcript_path`` field).

``check_isolation(eval_session_ids, real_state_paths)``
    Scan real-state paths for any occurrence of the eval session ids.
    Returns an ``IsolationResult`` with a ``verdict`` and ``violations``.

Known-escapee context
---------------------
The PREVENTIVE layer (``_write_workdir_settings``) covers Python
``fno.paths``-aware writers that read the workdir-local
``settings.yaml`` when ``CWD = workdir``.  It CANNOT cover:

- ``scripts/metrics/register-task.py:23``: LEDGER_JSON_PATH hardcodes
  the home-state ledger path (``~/.fno/ledger.json``) - no config
  read, no FNO_HOME.
- ``scripts/lib/paths.sh:11-13`` (auto-generated by ``fno paths
  emit-shell``): ``STATE_DIR="$HOME/.fno"`` hardcoded; all
  bash-layer writers inherit this.

The DETECTIVE layer (this module) is therefore the load-bearing backstop.
A follow-up carveout (filed via ``fno carveout add``) tracks the decision
of whether to add config-path awareness to these writers.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass
class Violation:
    """One occurrence of an eval session id in a real operator state file.

    Attributes:
        path:         Absolute path to the file containing the leak.
        session_id:   The eval session id that was found.
        line_number:  1-based line number of the first match in the file.
                      For whole-file (non-JSONL) scans, ``1`` if anywhere
                      in the file.
        detail:       One-line explanation of the suspected escape path,
                      naming the known-escapee writer where applicable.
    """

    path: Path
    session_id: str
    line_number: int
    detail: str


@dataclass
class IsolationResult:
    """Result of a single isolation check.

    Attributes:
        verdict:     ``"clean"`` if no eval ids were found in any real-state
                     surface; ``"violated"`` if at least one was.
        violations:  List of :class:`Violation` objects, one per (file, id)
                     pair detected.  Empty when ``verdict == "clean"``.
    """

    verdict: str  # "clean" | "violated"
    violations: list[Violation] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Enforce coherence: verdict must be 'violated' iff violations non-empty."""
        has_violations = len(self.violations) > 0
        if self.verdict == "violated" and not has_violations:
            raise ValueError(
                "IsolationResult coherence error: verdict='violated' requires non-empty violations"
            )
        if self.verdict == "clean" and has_violations:
            raise ValueError(
                "IsolationResult coherence error: verdict='clean' requires empty violations"
            )


# ---------------------------------------------------------------------------
# Known-escapee metadata
# ---------------------------------------------------------------------------

# Maps a "surface key" (matches keys in ``real_state_paths``) to a one-line
# escape explanation used in violation details.
_ESCAPE_EXPLANATIONS: dict[str, str] = {
    "ledger_json": (
        "writer bypasses project-local path overrides - known escapee: "
        "register-task.py ledger registration (scripts/metrics/register-task.py:23)"
    ),
    "graph_json": (
        "writer bypasses project-local path overrides - known escapee: "
        "paths.sh STATE_DIR (scripts/lib/paths.sh:11-13)"
    ),
    "repo_events_jsonl": (
        "writer bypasses project-local path overrides - known escapee: "
        "paths.sh STATE_DIR bash-layer writers"
    ),
    "global_events_jsonl": (
        "writer bypasses project-local path overrides - known escapee: "
        "paths.sh STATE_DIR bash-layer writers"
    ),
    "memory_dir": (
        "memory-pass or autocorrect writer may have used real session context"
    ),
    "corrections_log": (
        "autocorrect corrections.log writer may bypass project-local isolation"
    ),
}

_DEFAULT_ESCAPE_EXPLANATION = (
    "writer bypasses project-local path overrides - check known escapees: "
    "register-task.py (scripts/metrics/register-task.py:23) and "
    "paths.sh STATE_DIR (scripts/lib/paths.sh:11-13)"
)


# ---------------------------------------------------------------------------
# Internal scan helpers
# ---------------------------------------------------------------------------


def _scan_jsonl_file(
    path: Path,
    eval_session_ids: set[str],
    surface_key: str,
) -> list[Violation]:
    """Scan a JSONL file line by line for eval session ids.

    Reports the 1-based line number of the first match per (id, file).
    Missing files are silently skipped (clean result).
    """
    if not path.exists():
        return []

    violations: list[Violation] = []
    seen_ids: set[str] = set()
    explanation = _ESCAPE_EXPLANATIONS.get(surface_key, _DEFAULT_ESCAPE_EXPLANATION)

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []

    for lineno, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped:
            continue
        for sid in eval_session_ids:
            if sid in seen_ids:
                continue
            if sid in stripped:
                violations.append(
                    Violation(
                        path=path,
                        session_id=sid,
                        line_number=lineno,
                        detail=explanation,
                    )
                )
                seen_ids.add(sid)

    return violations


def _scan_whole_file(
    path: Path,
    eval_session_ids: set[str],
    surface_key: str,
) -> list[Violation]:
    """Scan a non-JSONL file (whole content) for eval session ids.

    Reports line number of the first matching line (1-based).
    Missing files are silently skipped.
    """
    if not path.exists():
        return []

    violations: list[Violation] = []
    seen_ids: set[str] = set()
    explanation = _ESCAPE_EXPLANATIONS.get(surface_key, _DEFAULT_ESCAPE_EXPLANATION)

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []

    lines = text.splitlines()
    for sid in eval_session_ids:
        if sid not in text:
            continue
        # Find first line containing the id
        for lineno, line in enumerate(lines, start=1):
            if sid in line:
                violations.append(
                    Violation(
                        path=path,
                        session_id=sid,
                        line_number=lineno,
                        detail=explanation,
                    )
                )
                seen_ids.add(sid)
                break

    return violations


def _scan_memory_dir(
    memory_dir: Path,
    eval_session_ids: set[str],
) -> list[Violation]:
    """Scan all files inside the memory directory for eval session ids.

    Missing directory is silently skipped.
    """
    if not memory_dir.exists() or not memory_dir.is_dir():
        return []

    violations: list[Violation] = []
    try:
        for mem_file in sorted(memory_dir.iterdir()):
            if mem_file.is_file():
                violations.extend(
                    _scan_whole_file(mem_file, eval_session_ids, "memory_dir")
                )
    except OSError:
        pass
    return violations


# ---------------------------------------------------------------------------
# Public: check_isolation
# ---------------------------------------------------------------------------


def check_isolation(
    eval_session_ids: set[str],
    real_state_paths: dict[str, Path],
) -> IsolationResult:
    """Scan real operator state surfaces for any eval session id leaks.

    Args:
        eval_session_ids:   Set of session id strings attributable to the
                            eval run.  Collected via
                            :func:`collect_eval_session_ids`.
        real_state_paths:   Dict mapping surface keys to absolute ``Path``
                            objects.  All known keys:

                            - ``ledger_json``       real ~/.fno/ledger.json
                            - ``graph_json``        real ~/.fno/graph.json
                            - ``repo_events_jsonl`` fno repo .fno/events.jsonl
                            - ``global_events_jsonl`` ~/.fno/events.jsonl
                            - ``memory_dir``        ~/.fno/memory/ directory
                            - ``corrections_log``   ~/.claude/corrections.log

                            Unknown keys are ignored.  Missing files are
                            silently skipped (clean).

    Returns:
        :class:`IsolationResult` with ``verdict="clean"`` or
        ``verdict="violated"`` and a list of :class:`Violation` objects.
    """
    if not eval_session_ids:
        return IsolationResult(verdict="clean", violations=[])

    all_violations: list[Violation] = []

    # --- JSONL surfaces ---
    for key in ("ledger_json", "graph_json", "repo_events_jsonl", "global_events_jsonl"):
        path = real_state_paths.get(key)
        if path is not None:
            all_violations.extend(_scan_jsonl_file(path, eval_session_ids, key))

    # --- memory directory (whole-file scan per file) ---
    memory_dir = real_state_paths.get("memory_dir")
    if memory_dir is not None:
        all_violations.extend(_scan_memory_dir(memory_dir, eval_session_ids))

    # --- corrections.log (whole-file scan) ---
    corrections_log = real_state_paths.get("corrections_log")
    if corrections_log is not None:
        all_violations.extend(_scan_whole_file(corrections_log, eval_session_ids, "corrections_log"))

    verdict = "violated" if all_violations else "clean"
    return IsolationResult(verdict=verdict, violations=all_violations)


# ---------------------------------------------------------------------------
# Public: collect_eval_session_ids
# ---------------------------------------------------------------------------


def _encode_path_for_claude_projects(path: Path) -> str:
    """Encode an absolute path to the Claude projects dir convention.

    Claude maps every non-[a-zA-Z0-9] character in the absolute path to '-'.
    Example: ``/tmp/abi-eval-task-abc`` -> ``-tmp-abi-eval-task-abc``
    """
    return re.sub(r"[^a-zA-Z0-9]", "-", str(path))


def collect_eval_session_ids(
    workdir: Path,
    *,
    claude_projects_dir: Optional[Path] = None,
) -> tuple[set[str], Optional[str]]:
    """Gather every session id attributable to the eval run in *workdir*.

    Sources (in order, merged into one set):
    1. ``workdir/.fno/target-state.md`` frontmatter ``session_id:`` field.
    2. ``workdir/.fno/events.jsonl``: every ``session_id`` field value.
    3. Transcript ``.jsonl`` files under
       ``<claude_projects_dir>/<encoded-workdir>/``.

    The transcript directory encoding matches Claude Code's convention:
    every character in the absolute workdir path that is not ``[a-zA-Z0-9]``
    is replaced with ``-``.

    Args:
        workdir:              Absolute path to the eval workdir.
        claude_projects_dir:  Override for the Claude projects base directory
                              (defaults to ``~/.claude/projects``).  Tests
                              supply a tmp path here to stay fully isolated.

    Returns:
        ``(ids, transcript_path)`` where ``ids`` is the set of collected
        session ids and ``transcript_path`` is the absolute path string of
        the first transcript ``.jsonl`` file found (or ``None`` if absent).
    """
    if claude_projects_dir is None:
        claude_projects_dir = Path.home() / ".claude" / "projects"

    ids: set[str] = set()
    transcript_path: Optional[str] = None

    # ------------------------------------------------------------------ #
    # 1. target-state.md manifest                                         #
    # ------------------------------------------------------------------ #
    manifest = workdir / ".fno" / "target-state.md"
    if manifest.exists():
        try:
            for line in manifest.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if stripped.startswith("session_id:"):
                    # Strip surrounding quotes: manifest values may be
                    # quoted (other state files store the id unquoted).
                    value = stripped[len("session_id:"):].strip().strip("'\"")
                    if value:
                        ids.add(value)
        except OSError:
            pass

    # ------------------------------------------------------------------ #
    # 2. workdir events.jsonl                                             #
    # ------------------------------------------------------------------ #
    events_path = workdir / ".fno" / "events.jsonl"
    if events_path.exists():
        try:
            for line in events_path.read_text(encoding="utf-8").splitlines():
                stripped = line.strip()
                if not stripped:
                    continue
                try:
                    event = json.loads(stripped)
                    sid = (
                        event.get("session_id")
                        or event.get("data", {}).get("session_id")
                    )
                    if sid and isinstance(sid, str):
                        ids.add(sid)
                except (json.JSONDecodeError, AttributeError):
                    continue
        except OSError:
            pass

    # ------------------------------------------------------------------ #
    # 3. Transcript files under ~/.claude/projects/<encoded-workdir>/     #
    # ------------------------------------------------------------------ #
    encoded = _encode_path_for_claude_projects(workdir)
    project_dir = claude_projects_dir / encoded
    if project_dir.is_dir():
        try:
            transcript_files = sorted(project_dir.glob("*.jsonl"))
            if transcript_files:
                primary = transcript_files[0]
                transcript_path = str(primary)
                # Also collect session ids from transcript filenames (UUID stems)
                for tf in transcript_files:
                    stem = tf.stem
                    if stem:
                        ids.add(stem)
        except OSError:
            pass

    return ids, transcript_path


# ---------------------------------------------------------------------------
# Default real-state paths (used by runner when not overridden in tests)
# ---------------------------------------------------------------------------


def default_real_state_paths(repo_root: Path) -> dict[str, Path]:
    """Return the canonical real-state paths for isolation checking.

    These are the REAL paths - NOT the workdir-local redirects.  The point
    is to scan the actual operator state for any leaked eval session ids.

    Args:
        repo_root: The fno repo root (for repo-local events.jsonl).
    """
    home = Path.home()
    abilities_home = home / ".fno"
    return {
        "ledger_json": abilities_home / "ledger.json",
        "graph_json": abilities_home / "graph.json",
        "repo_events_jsonl": repo_root / ".fno" / "events.jsonl",
        "global_events_jsonl": abilities_home / "events.jsonl",
        "memory_dir": abilities_home / "memory",
        "corrections_log": home / ".claude" / "corrections.log",
    }


# ---------------------------------------------------------------------------
# Recovery guidance printer
# ---------------------------------------------------------------------------


def format_violation_report(result: IsolationResult) -> str:
    """Format a human-readable report of isolation violations.

    Each violation line includes:
    - the offending file path
    - the eval session id found
    - the line number
    - the suspected escape explanation

    Returns an empty string when ``result.verdict == "clean"``.
    """
    if result.verdict == "clean":
        return ""

    lines = [
        f"[eval] ISOLATION VIOLATED: {len(result.violations)} leak(s) detected",
        "",
    ]
    for v in result.violations:
        lines.append(f"  file:       {v.path}")
        lines.append(f"  session_id: {v.session_id}")
        lines.append(f"  line:       {v.line_number}")
        lines.append(f"  suspected:  {v.detail}")
        lines.append("")

    lines.append(
        "[eval] Action: check whether the eval workdir settings.yaml was loaded "
        "by the session (CWD must equal the workdir).  Known escapees that cannot "
        "be redirected: register-task.py (scripts/metrics/register-task.py:23) "
        "and paths.sh STATE_DIR (scripts/lib/paths.sh:11-13)."
    )
    return "\n".join(lines)
