"""Codegen: emit scripts/lib/paths.sh from the Pydantic schema.

Determinism contract: byte-identical output given identical schema input on
ANY machine.  HOME-anchored paths use the literal ``$HOME`` variable and
project-relative paths use ``$REPO_ROOT`` so the generated file is the same
regardless of which developer runs the codegen command.

Two-step: compute every accessor's template string, then emit the bash stub.
"""
from __future__ import annotations

import shlex

from fno.config import load_settings, SettingsModel


def _bash_quote(value: str) -> str:
    """Quote a value for bash assignment.

    If the value contains shell variable references ($HOME, $STATE_DIR, etc.)
    we must use double-quotes so bash expands them at runtime.  Otherwise use
    shlex.quote (single-quotes, safe for any characters including spaces).
    """
    if "$" in value:
        # Double-quote and escape any literal double-quotes or backslashes
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return shlex.quote(value)


def _home_relative(raw_value: str) -> str:
    """Convert a tilde-prefixed raw schema value to a $HOME-relative template.

    - "~/.fno/" -> "$HOME/.fno"
    - "~/.fno/sub" -> "$HOME/.fno/sub"
    - "/custom/abs/path" -> "/custom/abs/path"  (already absolute, no HOME)
    - ".fno/plans/" -> stays as-is (handled separately as project-relative)

    Trailing slashes are stripped for consistency.
    """
    stripped = raw_value.rstrip("/")
    if stripped.startswith("~/"):
        return "$HOME/" + stripped[2:]
    if stripped == "~":
        return "$HOME"
    return stripped


def _is_project_relative(raw_value: str) -> bool:
    """Return True if the raw value is a bare relative path (no ~, /, $, or {} templates).

    A value containing '{' anywhere (e.g. 'plans/{project}') is NOT project-relative:
    emitting it as '$REPO_ROOT/plans/{project}' produces unexpandable bash.
    The check disqualifies ANY occurrence of '{', not just at the start.
    """
    stripped = raw_value.strip()
    if not stripped:
        return False
    return not (
        stripped.startswith("/")
        or stripped.startswith("~")
        or stripped.startswith("$")
        or "{" in stripped
    )


def _has_template(raw_value: str) -> bool:
    """Return True if the raw value contains a {template} variable (not {{ escape)."""
    import re
    return bool(re.search(r"(?<!\{)\{([^{}]+)\}(?!\})", raw_value))


def emit_paths_sh(*, use_defaults: bool = False) -> str:
    """Return the bash stub as a string. Caller writes to disk via atomic rename.

    Args:
        use_defaults: When True, generate from schema defaults only (ignoring
            the user's settings.yaml). This produces machine-stable output
            suitable for checking into the repository. When False (default),
            reflect the user's current settings. The checked-in
            scripts/lib/paths.sh must always be generated with use_defaults=True.

    The output is machine-stable when use_defaults=True: regenerating on any
    developer's machine or CI runner produces the same bytes, because
    HOME-anchored paths use the literal ``$HOME`` shell variable and
    project-relative paths use ``$REPO_ROOT``.

    If state_dir or paths.* have been overridden to an absolute path (not
    tilde-prefixed), the literal absolute path is emitted.

    Template values ({vault}, {project}) are resolved at codegen time via
    the paths.*() accessors so shell consumers never see raw Python-style
    template tokens (Finding B).
    """
    import fno.paths as _paths

    if use_defaults:
        # Load a fresh SettingsModel with no user overrides. This guarantees
        # byte-identical output on any machine regardless of settings.yaml.
        settings = SettingsModel()
    else:
        settings = load_settings()
    cfg = settings.config

    lines = [
        "#!/usr/bin/env bash",
        "# AUTO-GENERATED by `fno paths emit-shell`. Do not hand-edit.",
        "# Regenerate after any change to settings.yaml or the schema:",
        "#   cd cli && uv run fno-py paths emit-shell --output ../scripts/lib/paths.sh",
        "",
        "# Self-set REPO_ROOT if unset so this file is safe to source under set -u.",
        "# Callers may still pre-set REPO_ROOT before sourcing to pin the value.",
        'REPO_ROOT="${REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"',
        'HOME="${HOME:-$(getent passwd "$(id -un)" 2>/dev/null | cut -d: -f6 || echo ~)}"',
        "",
    ]

    # STATE_DIR: home-relative or absolute.
    # If state_dir contains a template ({vault}, {project}), resolve it via
    # paths.state_dir() at codegen time so the emitted stub has an absolute path.
    state_dir_raw = cfg.state_dir.rstrip("/")
    if _has_template(state_dir_raw):
        state_dir_tmpl = str(_paths.state_dir())
    else:
        state_dir_tmpl = _home_relative(cfg.state_dir)
    lines.append(f"export STATE_DIR={_bash_quote(state_dir_tmpl)}")

    # Derive subdirs from STATE_DIR when no explicit override.
    # Template-containing overrides are resolved at codegen time.
    def _state_subpath(override: str | None, subdir: str) -> str:
        """Return a shell template for a path that derives from STATE_DIR."""
        if override is not None:
            raw = override.rstrip("/")
            if _has_template(raw):
                # Resolve via paths accessor equivalent - use _resolve from paths
                from fno.paths import _resolve
                return str(_resolve(raw))
            return _home_relative(raw) if raw.startswith("~") else raw
        return f"$STATE_DIR/{subdir}"

    lines.append(f"export GRAPH_JSON_PATH={_bash_quote(_state_subpath(cfg.paths.graph_json, 'graph.json'))}")
    lines.append(f"export LEDGER_JSON_PATH={_bash_quote(_state_subpath(cfg.paths.ledger_json, 'ledger.json'))}")
    lines.append(f"export BRIEFS_DIR={_bash_quote(_state_subpath(cfg.paths.briefs_dir, 'briefs'))}")
    lines.append(f"export FLEET_DIR={_bash_quote(_state_subpath(cfg.paths.fleet_dir, 'fleet'))}")
    lines.append(f"export POSTMORTEMS_DIR={_bash_quote(_state_subpath(cfg.paths.postmortems_dir, 'postmortems'))}")
    lines.append(f"export WORKTREES_BASE={_bash_quote(_state_subpath(cfg.paths.worktrees_base, 'worktrees'))}")
    lines.append(f"export MEMORY_DIR={_bash_quote(_state_subpath(cfg.paths.memory_dir, 'memory'))}")
    lines.append(f"export HOOK_LOGS_DIR={_bash_quote(_state_subpath(cfg.paths.hook_logs_dir, 'hook-logs'))}")

    # PLANS_DIR: project-relative by default.
    # Template-containing values are resolved at codegen time.
    plans_raw = cfg.plans_dir.rstrip("/")
    if _is_project_relative(plans_raw):
        plans_tmpl = f"$REPO_ROOT/{plans_raw}"
    elif _has_template(plans_raw):
        plans_tmpl = str(_paths.plans_dir())
    elif plans_raw.startswith("~"):
        plans_tmpl = _home_relative(plans_raw)
    else:
        plans_tmpl = plans_raw
    lines.append(f"export PLANS_DIR={_bash_quote(plans_tmpl)}")

    # INBOX_DIR: project-relative by default.
    # Template-containing overrides are resolved at codegen time.
    inbox_override = cfg.paths.inbox_dir
    if inbox_override is not None:
        inbox_raw = inbox_override.rstrip("/")
        if _has_template(inbox_raw):
            inbox_tmpl = str(_paths.inbox_dir())
        elif inbox_raw.startswith("~"):
            inbox_tmpl = _home_relative(inbox_raw)
        else:
            inbox_tmpl = inbox_raw
    else:
        inbox_tmpl = "$REPO_ROOT/.fno/inbox"
    lines.append(f"export INBOX_DIR={_bash_quote(inbox_tmpl)}")

    # HANDOFFS_DIR: vault-aware persistent location for target session handoffs.
    # Mirrors paths.handoffs_dir() resolution:
    #   override        -> emit override (template-resolved at codegen if needed)
    #   obsidian on     -> <vault>/internal/<project>/handoffs/ (resolved at codegen)
    #   default         -> $STATE_DIR/handoffs/<basename of $REPO_ROOT>
    # The default uses a shell command substitution so the checked-in stub stays
    # machine-stable; the project name resolves at source-time from the consumer's
    # repo, not the codegen runner's.
    handoffs_override = cfg.paths.handoffs_dir
    if handoffs_override is not None:
        handoffs_raw = handoffs_override.rstrip("/")
        if _has_template(handoffs_raw):
            handoffs_tmpl = str(_paths.handoffs_dir())
        elif handoffs_raw.startswith("~"):
            handoffs_tmpl = _home_relative(handoffs_raw)
        else:
            handoffs_tmpl = handoffs_raw
        lines.append(f"export HANDOFFS_DIR={_bash_quote(handoffs_tmpl)}")
    elif cfg.obsidian.enabled and cfg.obsidian.vault:
        handoffs_tmpl = str(_paths.handoffs_dir())
        lines.append(f"export HANDOFFS_DIR={_bash_quote(handoffs_tmpl)}")
    else:
        # When project.id is set, emit a static path that matches the Python
        # resolver's behavior (paths.handoffs_dir() uses config.project.id for
        # the project segment). project.id is validated as shell-safe via
        # `[A-Za-z0-9._-]+` so direct interpolation is safe.
        # When unset, fall back to a $REPO_ROOT basename expression that
        # resolves at source-time so the checked-in stub stays machine-stable.
        # _bash_quote cannot represent nested "..." inside $(...) inside "...";
        # the fallback emits the literal line.
        pid = cfg.project.id
        if pid:
            lines.append(f"export HANDOFFS_DIR={_bash_quote(f'$STATE_DIR/handoffs/{pid}')}")
        else:
            lines.append('export HANDOFFS_DIR="$STATE_DIR/handoffs/$(basename "$REPO_ROOT")"')

    # CONFIG_FILE: in defaults mode, emit a $STATE_DIR-relative path so the
    # checked-in stub has no machine-specific absolute paths. In live mode,
    # use the actual path that load_settings() loaded from so shell consumers
    # get the real location (e.g. project-local .fno/settings.yaml).
    if use_defaults:
        config_file_tmpl = "$STATE_DIR/settings.yaml"
        lines.append(f"export CONFIG_FILE={_bash_quote(config_file_tmpl)}")
    else:
        from fno.paths import config_file as _config_file
        actual_config = _config_file()
        lines.append(f"export CONFIG_FILE={_bash_quote(str(actual_config))}")

    # Lazy bash functions for paths that need per-call arguments.
    lines.append("")
    lines.append("paths_plan_file() {")
    lines.append('  local name="$1"')
    lines.append('  echo "${PLANS_DIR}/${name}"')
    lines.append("}")
    lines.append("")
    lines.append("paths_inbox_thread() {")
    lines.append('  local thread="$1"')
    lines.append('  echo "${INBOX_DIR}/${thread}"')
    lines.append("}")
    lines.append("")
    lines.append("# Mirrors fno.paths.project_log(): <repo>/.fno/<name>, anchored to")
    lines.append("# $REPO_ROOT (never CWD). Hooks route ad-hoc .fno/ writes through this")
    lines.append("# instead of hand-building \".fno/\" + name strings.")
    lines.append("paths_project_log() {")
    lines.append('  local name="$1"')
    lines.append('  echo "${REPO_ROOT}/.fno/${name}"')
    lines.append("}")
    lines.append("")

    return "\n".join(lines)
