"""Emit canonical Obsidian Base files for the backlog (x-6c2b waves 2-3).

One source of truth for the epic/mission progress views, replacing the
hand-synced roadmap bases (mux/protocol/harden) and their hand-stamped
frontmatter. The files are regenerable artifacts: each carries a generated
marker on its first line, and the emitter REFUSES to overwrite a target that
lacks the marker so a hand-authored base is never silently clobbered.

The .base files land in the (gitignored) Obsidian vault, not the repo - the
VERB is the shipped, tested deliverable; the emitted YAML is its output.
"""
from __future__ import annotations

from pathlib import Path

GENERATED_MARKER = "# GENERATED by `fno backlog bases`"

_PLANS_FOLDER = "internal/fno/plans"

# Shared priority glyph formula + counter property display names, reused by
# both bases so their columns read identically.
_PRIO_FORMULA = (
    'if(priority == "p1", "🔴 p1", '
    'if(priority == "p2", "🟡 p2", '
    'if(priority == "p0", "🚨 p0", "⚪ p3")))'
)

_EPICS_BASE = f"""\
{GENERATED_MARKER} - edits are overwritten. Regenerate: fno backlog bases
filters:
  and:
    - file.inFolder("{_PLANS_FOLDER}")
    - type == "epic"
formulas:
  prio: {_PRIO_FORMULA}
properties:
  file.name:
    displayName: Epic
  progress:
    displayName: Progress
  children_done:
    displayName: Done
  children_total:
    displayName: Total
  children_in_flight:
    displayName: In flight
  children_blocked:
    displayName: Blocked
  formula.prio:
    displayName: Priority
  parent_slug:
    displayName: Mission
views:
  - type: table
    name: Epics
    order:
      - file.name
      - progress
      - children_done
      - children_total
      - children_in_flight
      - children_blocked
      - formula.prio
      - status
    sort:
      - property: children_blocked
        direction: DESC
      - property: children_total
        direction: DESC
    columnSize:
      file.name: 380
  - type: table
    name: By mission
    groupBy:
      property: parent_slug
      direction: ASC
    order:
      - file.name
      - progress
      - children_done
      - children_total
      - formula.prio
"""

# filename -> content. Ordered epics-first for a stable receipt.
BASES: dict[str, str] = {
    "epics.base": _EPICS_BASE,
}


def write_base(path: Path, content: str) -> str:
    """Write ``content`` to ``path``, guarding a user-owned file.

    Returns a one-word action: ``written`` (created or refreshed a generated
    file), ``unchanged`` (byte-identical, no write), or ``refused`` (the target
    exists and its first line lacks the generated marker - a hand-authored base
    is never clobbered). Never raises on a normal filesystem.
    """
    if path.exists():
        try:
            first = path.read_text(encoding="utf-8").splitlines()[:1]
        except OSError:
            first = []
        if not first or not first[0].startswith(GENERATED_MARKER):
            return "refused"
        if path.read_text(encoding="utf-8") == content:
            return "unchanged"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return "written"
